### ISSUE TITLE
Does the current second-stage network support your platform?

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1003]
Hi  xilinx,

At present, we have a two-stage network, and cascade rcnn wants to be deployed on vck5000, but I only see a one-stage network in modelzoo. I want to ask whether the quantization and compilation of rcnn network is currently supported?

**Comment by jia0511** [comment]
Hi xilinx,

Can you give us an answer, whether the current two-stage model can be quantified normally using the vitis-ai tool？

**Comment by SuZhan0322** [comment]
Hi @jia0511,
Vitis-AI tools do not support two-stage models yet, thanks~

**Comment by jia0511** [comment]
@SuZhan0322 

Is there any plan for support in the future, and how can we support it?

**Comment by SuZhan0322** [comment]
Hi @jia0511 ,
It is planned to support this feature in VAI3.0 WeGo flow. thanks!

**Comment by jia0511** [comment]
@SuZhan0322 

Thank you for your support！
