### ISSUE TITLE
Steps to quantize, compile and run inference a yolov4 darknet model on ZCU102?

### ISSUE THREAD

**Issue by vongracia** [Xilinx/Vitis-AI#1005]
Hi all,

I'm trying to make inference on a ZCU102 using a yolov4 darknet model trained on custom 4K data, but I'm having issues. It is explained all here: https://github.com/Xilinx/Vitis-AI/issues/1002

Could anyone provide me a very good tutorial with code to achieve so? I've tried:
https://github.com/Xilinx/Vitis-AI-Tutorials/tree/1.3/Design_Tutorials/07-yolov4-tutorial

But I have problems.
Thanks in advance,

**Comment by qianglin-xlnx** [comment]
Hi @vongracia  
Which version of Vitis-AI do you use?
I see there is update version of 07-yolov4-tutorial, which is 1.4. Maybe you can try this: https://github.com/Xilinx/Vitis-AI-Tutorials/tree/1.4/Design_Tutorials/07-yolov4-tutorial

**Comment by vongracia** [comment]
Yes, thank you. I will use that from now on

**Comment by zhenzhen-AMD** [comment]
Hi @vongracia ，

Through analysis, the model contains "softplus",
Currently DPU does not support "softplus", so please replace "softplus" with other ops.

![image](https://user-images.githubusercontent.com/108107672/191954163-6b33dfd6-ac91-444f-bc28-0287a41a0061.png)

**Comment by vongracia** [comment]
Thanks @zhenzhen-AMD 

Do you mean when training the yolov4 using darknet? You mean replacing it by Relu?

Thanks

**Comment by zhenzhen-AMD** [comment]
Hi @vongracia ,

There are two solutions:
1. When training, you can replace 'softplus' with 'relu'. Eventually 'relu' will run on the DPU.
2. If you keep 'softplus', you need to set "add_shape_info=True" in the quantization stage. When compiling 'softplus' will be treated as 'unknown', and eventually it will run on the CPU.

Regards,
Zhenzhen

**Comment by zhenzhen-AMD** [comment]
Hi @vongracia ,
I will closed this issue. Please free open new issue If you have new problem.
