### ISSUE TITLE
Model Zoo link is invalid

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#1008]
I tried to download the link in Model Zoo, but found that it was no longer working.
like this :
https://www.xilinx.com/bin/public/openDownload?filename=resnet50_pruned_0_7_pt-vck5000-DPUCVDX8H-6pe-aieDWC-r2.5.0.tar.gz
![image](https://user-images.githubusercontent.com/51226649/189251519-08cd2644-60d1-40b0-a121-1d2ceba076b3.png)

**Comment by SuZhan0322** [comment]
Hi @jzymessi ,
Thanks for your feedback, and we have upload the xmodel tar.gz package, please try again.

**Comment by SuZhan0322** [comment]
Hi @jzymessi , 
Please reopen the issue if you have any other questions.
