### ISSUE TITLE
Does VITIS-AI3.0 support onnx to go to xmodel?

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1010]
This is a convenient way for users to deploy xmodel！

**Comment by qianglin-xlnx** [comment]
@jia0511 
Sorry about late reply.
Yes. Vitis-AI 3.0 directly support quantized onnx model on edge platform. 
For Onnx examples, refer to : https://github.com/Xilinx/Vitis-AI/tree/master/examples/vai_library/samples_onnx
