### ISSUE TITLE
What does NNDCT stand for?

### ISSUE THREAD

**Issue by michael-person** [Xilinx/Vitis-AI#1011]
This is not an issue with the code but I am curious what NNDCT stands for? It is such a large part of the PyTorch workflow so I can't help but wonder.

**Comment by niuxjxlnx** [comment]
@michael-person :

It is our internal project name of vai_q_pytorch (Vistis-AI pytorch quantizer). It means Neural Network Deep Compression Toolkit.

**Comment by michael-person** [comment]
Thank you!
