### ISSUE TITLE
`vai_c_tensorflow2` compilation error when the `ignore_layers` option is specified in the function call `vitis_quantize.VitisQuantizer.quantize_model`

### ISSUE THREAD

**Issue by williamliao28** [Xilinx/Vitis-AI#1023]
### Description of the issue:
When the `ignore_layers` option is specified in the function call `vitis_quantize.VitisQuantizer.quantize_model`, attempt to compile the output quantized_model with `vai_c_tensorflow2` will result in the following error

<img width="1519" alt="截圖 2022-09-22 14 46 16" src="https://user-images.githubusercontent.com/20777211/191850046-1e102fc7-47ed-490b-8aaf-084131d6723f.png">

### Steps to reproduce the issue:

 1. Quantize a float model with the `ignore_layers` options in the function call `vitis_quantize.VitisQuantizer.quantize_model` and save the quantized model:
 ```
quantizer = vitis_quantize.VitisQuantizer(float_model)
quantized_model = quantizer.quantize_model(calib_dataset=quant_dataset, fold_conv_bn=False, 
    ignore_layers=ignore_layers)
quantized_model.save(quant_model)
```
 2. Compile the quantized model with the following command:
```
vai_c_tensorflow2 \
            --model           build/quant_model/q_simple_CNN.h5 \
            --arch            $ARCH \
            --output_dir      build/compiled_$TARGET \
            --net_name        simple_CNN_$TARGET \
            --options '{"input_shape": "4,28,28,1"}'
``` 

### Possible cause of the error:
Layers listed in `ignore_layers` are not wrapped by any wrappers during quantization. In contrast, layer not in `ignore_layers` will be wrapped by either `VitisQuantize` or `QuantizeWrapper`. Thus, when the python script `tensorflow_translator.py` tries to execute

```
ksize = inner_layer_config.get("kernel_size")
```
in line 598, which is the previous function call before the error, the value of `ksize` will be `None` since `inner_layer_config` is still the config of previous quantized activation layer and a activation layer has no `kernel_size`.

The following is the simple CNN model I am testing with:
```
model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(16, kernel_size=5, strides=2, padding='same', input_shape=in_shape),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.Conv2D(32, kernel_size=5, strides=2, padding='same', trainable=False, use_bias=False),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.Conv2D(64, kernel_size=3, strides=2, padding='same', trainable=False, use_bias=False),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Activation('relu'),
        tf.keras.layers.Conv2D(10, kernel_size=3, strides=3),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Flatten()
    ])
```

I ignore the second and third `Conv2D` during quantization.

**Comment by zhenzhen-AMD** [comment]
Hi @williamliao28 ,
Could you please provide the float.h5 and quantized.h5 files? These would be very helpful in resolving the issue.

**Comment by zhenzhen-AMD** [comment]
Hi @williamliao28 ，
Currently, **vai_c_tensorflow2** does not support quantized models generated using the **ignore_layers** option.

**Comment by zhenzhen-AMD** [comment]
Closing this for now. Please re-open if there are any other concerns. Thanks.
