### ISSUE TITLE
Upgrade Docker base image?

### ISSUE THREAD

**Issue by vonschultz** [Xilinx/Vitis-AI#1026]
It seems like the Docker base image is Ubuntu 18.04. Are there any plans to upgrade? I would have expected Ubuntu 22.04, or possibly Ubuntu 20.04.

**Comment by janifer112x** [comment]
Hi @vonschultz,
we may expect to upgrade VitisAI base image to Ubuntu20.04 for VAI 3.0 release early Jan next year.
