### ISSUE TITLE
How could I find dpu_task.cpp in ZCU102 images?

### ISSUE THREAD

**Issue by yangyazhou97** [Xilinx/Vitis-AI#1031]
Hi Xilinx Community,
In  https://github.com/Xilinx/Vitis-AI/tree/master/examples/Vitis-AI-Library/samples/dpu_task/fadnet, I read fadnet.cpp ,  there is a line code " #include <vitis/ai/dpu_task.cpp", and I  only could find dpu.hpp in /usr/include/vitis/ai in ZCU102 images , but I also want to found out where is dpu.cpp ? 
Thanks.

**Comment by qianglin-xlnx** [comment]
Hi @yangyazhou97 
Find the dpu.cpp in https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Library/dpu_task/src/dpu_task.cpp

**Comment by yangyazhou97** [comment]
Yes, I could find dpu.cpp in github, but I want to find out where is dpu.cpp in ZCU102 images. Thanks

**Comment by qianglin-xlnx** [comment]
It has been compiled as a library in ZCU102 image. You can find the libvitis_ai_library-dpu_task.so under /usr/lib.
If you want to debug it, you have to compile the Vitis-AI-Library in debug mode then install it and debug your program.

**Comment by yangyazhou97** [comment]
I see, Thanks a lot.
I also have a question besides. In https://github.com/Xilinx/Vitis-AI/tree/master/examples/VART, there is many models about classification and video segmentation, but I have a model to do depth estimation by single image, how could I save the result through "cv::imwrite" or "cv::imshow", I learn two image depth estimation in https://github.com/Xilinx/Vitis-AI/tree/master/examples/Vitis-AI-Library/samples/dpu_task/fadnet, but it call “#include <vitis/ai/dpu_task.hpp>”， how could I save image by myself? Thanks.

**Comment by lishixlnx** [comment]
in line 594 in fadenet.cpp, after 
    resize(final_img, ret, cv::Size(ret_width, ret_height));
use 
   cv::imwrite("some.jpg", ret);

**Comment by yangyazhou97** [comment]
Yes, I know that. .Now I have a depth estimation model, 
I learned https://github.com/Xilinx/VitisAI/blob/master/examples/VART/squeezenet_pytorch/src/main.cc,  I enter ./squeezenet_pytorch  ./depth_estimation model ,how could I save depth image?

**Comment by lishixlnx** [comment]
please make your question clear. 
what do you mean by "save" depth image? 
I can't understand what do you want.

**Comment by yangyazhou97** [comment]
OK, there are many examples in https://github.com/Xilinx/Vitis-AI/tree/master/examples/VART, but many of them are classificaition models, after learning  https://github.com/Xilinx/VitisAI/blob/master/examples/VART/squeezenet_pytorch/src/main.cc, now I have a custom depth estimation model, how could I ouput depth image?

**Comment by lishixlnx** [comment]
you can do it in something like this:
  cv::Mat mat( height, width, CV_32FC1);
  for(int i=0; i<height; i++) {
    for(int j=0; j<width; j++) {
      mat.ptr<float>(i)[j] =  some_value_your_logic_calculated_from_model;
    }
  }
cv::imwrite("result_mat.png", mat);

**Comment by yangyazhou97** [comment]
Thank you so much, I think that's what I'm doing, but I still wrong the "image3". I post my code below.
#include <assert.h>
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cassert>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <queue>
#include <string>
#include <vector>
#include <time.h>
#include <chrono>
#include <algorithm>

#include "common.h"
/* header file OpenCV for image processing */
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;
using std::chrono::high_resolution_clock;
using std::chrono::milliseconds;

GraphInfo shapes;

const string baseImagePath = "./images/";
const string wordsPath = "./";

/**
 * @brief put image names to a vector
 *
 * @param path - path of the image direcotry
 * @param images - the vector of image name
 *
 * @return none
 */
void ListImages(string const& path, vector<string>& images) {
  images.clear();
  struct dirent* entry;

  /*Check if path is a valid directory path. */
  struct stat s;
  lstat(path.c_str(), &s);
  if (!S_ISDIR(s.st_mode)) {
    fprintf(stderr, "Error: %s is not a valid directory!\n", path.c_str());
    exit(1);
  }

  DIR* dir = opendir(path.c_str());
  if (dir == nullptr) {
    fprintf(stderr, "Error: Open %s path failed.\n", path.c_str());
    exit(1);
  }

  while ((entry = readdir(dir)) != nullptr) {
    if (entry->d_type == DT_REG || entry->d_type == DT_UNKNOWN) {
      string name = entry->d_name;
      string ext = name.substr(name.find_last_of(".") + 1);
      if ((ext == "JPEG") || (ext == "jpeg") || (ext == "JPG") ||
          (ext == "jpg") || (ext == "PNG") || (ext == "png")) {
        images.push_back(name);
      }
    }
  }

  closedir(dir);
}
void runSqueezenet(vart::Runner* runner) {
  vector<string> kinds, images;

  /* Load all image names.*/
  ListImages(baseImagePath, images);
  if (images.size() == 0) {
    cerr << "\nError: No images existing under " << baseImagePath << endl;
    return;
  }

  /* get in/out tensors and dims*/
  //auto outputTensors = runner->get_output_tensors();
  //auto inputTensors = runner->get_input_tensors();
  auto outputTensors = cloneTensorBuffer(runner->get_output_tensors());
  auto inputTensors = cloneTensorBuffer(runner->get_input_tensors());
  auto out_dims = outputTensors[0]->get_shape();
  auto in_dims = inputTensors[0]->get_shape();
  auto input_scale = get_input_scale(runner->get_input_tensors()[0]);
  auto output_scale = get_output_scale(runner->get_output_tensors()[0]);

  /*get shape info*/
  int inSize = shapes.inTensorList[0].size;
  int inHeight = shapes.inTensorList[0].height;
  int inWidth = shapes.inTensorList[0].width;

  int outSize = shapes.outTensorList[0].size;
  int cls = shapes.outTensorList[0].channel;
  int ot_h = shapes.outTensorList[0].height;
  int ot_w = shapes.outTensorList[0].width;
  int batchSize = in_dims[0];

  std::vector<std::unique_ptr<vart::TensorBuffer>> inputs, outputs;

  vector<Mat> imageList;
  //vector<int8_t> imageInputs(inSize * batchSize);

  int batch = inputTensors[0]->get_shape().at(0);
  int8_t* result = new int8_t[shapes.outTensorList[0].size * batch];
  int8_t* imageInputs = new int8_t[shapes.inTensorList[0].size * batch];
  cout<<"imageinputs.size: "<<shapes.inTensorList[0].size*batch;

  std::vector<vart::TensorBuffer*> inputsPtr, outputsPtr;
  std::vector<std::shared_ptr<xir::Tensor>> batchTensors;
  /*run with batch*/
  for (unsigned int n = 0; n < images.size(); n += batchSize) {
    unsigned int runSize =
        (images.size() < (n + batchSize)) ? (images.size() - n) : batchSize;
    in_dims[0] = runSize;
    out_dims[0] = batchSize;
    for (unsigned int i = 0; i < runSize; i++) {
      Mat image = imread(baseImagePath + images[n + i]);

      /*image pre-process*/
      Mat image2 = cv::Mat(inHeight, inWidth, CV_8UC3);
      resize(image, image2, Size(inHeight, inWidth), 0, 0, INTER_NEAREST);
      for (int h = 0; h < inHeight; h++) {
        for (int w = 0; w < inWidth; w++) {
          for (int c = 0; c < 3; c++) {
	    //imageInputs[i * inSize + h * inWidth * 3 + w * 3 + 2 + c] =(int8_t)(image2.at<Vec3b>(h, w)[c] * input_scale);
	    imageInputs[i * inSize + h * inWidth * 3 + w * 3 + 2 + c] =(int8_t)((float)image2.at<Vec3b>(h, w)[c] * input_scale);
          }
        }
      }
      imageList.push_back(image);
    }

    inputs.push_back(std::make_unique<CpuFlatTensorBuffer>(
        imageInputs, inputTensors[0].get()));
    outputs.push_back(
        std::make_unique<CpuFlatTensorBuffer>(result, outputTensors[0].get()));
    /*tensor buffer input/output */
    inputsPtr.clear();
    outputsPtr.clear();
    inputsPtr.push_back(inputs[0].get());
    outputsPtr.push_back(outputs[0].get());

    /*run*/
    auto job_id = runner->execute_async(inputsPtr, outputsPtr);
    cout << "outputs[0].get(): "<< outputs[0].get();
    //cout << "result = "<<result;
    //cout << "&result = "<<&result<<endl;
    runner->wait(job_id.first, -1);

    cout << "========================"<<endl;
    cout << "========================="<<endl;
    //Mat image2 = cv::Mat(inHeight, inWidth, CV_8SC3);
    Mat image2 = cv::Mat(inHeight, inWidth, CV_8UC3);
    Mat image3 = cv::Mat(inHeight, inWidth, CV_8UC3);
    cout << "inH: " << inHeight<<" inW: "<<inWidth<<endl;
    ///*

    for (int h = 0; h < inHeight; h++) {
        for (int w = 0; w < inWidth; w++) {
	    for(int c = 0; c < 3; c++)
		{
          	    image2.at<Vec3b>(h,w)[c] = result[h*inHeight + w];//*output_scale;
	  	}
      }
    }


    double minVal = 0.0;
    double maxVal = 0.0;
    minMaxLoc(image2, &minVal, &maxVal);
    cout <<"minVal: "<< minVal<<" "<<"maxVal: "<<maxVal<<endl;
    image3 = (image2-minVal)/(maxVal-minVal)*255;

    cv::imshow("image3.png",image3);
    cv::waitKey(10000);
    cv::imwrite("image3.png",image3);

    
    imageList.clear();
    inputs.clear();
    outputs.clear();
  }
}

/**
 * @brief Entry for runing ResNet50 neural network
 *
 * @note Runner APIs prefixed with "dpu" are used to easily program &
 *       deploy ResNet50 on DPU platform.
 *
 */
int main(int argc, char* argv[]) {
  high_resolution_clock::time_point beginTime = high_resolution_clock::now();
  // Check args
  if (argc != 2) {
    cout << "Usage: " << argv[0] << " <model_name>" << endl;
    return -1;
  }
  
  auto graph = xir::Graph::deserialize(argv[1]);
  auto subgraph = get_dpu_subgraph(graph.get());
  CHECK_EQ(subgraph.size(), 1u)
      << argv[0] << " should have one and only one dpu subgraph.";
  LOG(INFO) << "create running for subgraph: " << subgraph[0]->get_name();
  /*create runner*/
  auto runner = vart::Runner::create_runner(subgraph[0], "run");
  // ai::XdpuRunner* runner = new ai::XdpuRunner("./");
  /*get in/out tensor*/
  auto inputTensors = runner->get_input_tensors();
  auto outputTensors = runner->get_output_tensors();

  /*get in/out tensor shape*/
  int inputCnt = inputTensors.size();
  int outputCnt = outputTensors.size();
  TensorShape inshapes[inputCnt];
  TensorShape outshapes[outputCnt];
  shapes.inTensorList = inshapes;
  shapes.outTensorList = outshapes;
  getTensorShape(runner.get(), &shapes, inputCnt, outputCnt);

  int thread_number = 20;
  float total_frames = thread_number * 654;

  runSqueezenet(runner.get());

 
  return 0;
}

**Comment by yangyazhou97** [comment]
Actually, I'm not sure if the "result" is real output.

**Comment by lishixlnx** [comment]
I know what you mean.   The result is correct.
This image is  Mat(CV_32FC1),  not the common image of Mat(CV_8UC3).
The CV_32FC1 is used only by the opencv innerly use to store binary data,
not like the common picture that we can see.
the pictures that we can see normally is CV_8UC3 ( or CV_8UC1)。

you can change your CV_32FC1 to CV_8UC1 in order to show by imshow().
that need some special technical skill( for example, you need map the big float data to 0-255 int8 number)

**Comment by yangyazhou97** [comment]
Thank you so much, I have solved this question. I will try using the method you said. Thanks again.
