### ISSUE TITLE
Compile Error：The fix info is error or unsupported

### ISSUE THREAD

**Issue by Windhelm-H** [Xilinx/Vitis-AI#1058]
Hello 
    I encountered a problem when compiling with Vitis-AI 2.5. The log as

    [UNILOG][INFO] Compile mode: dpu
    [UNILOG][INFO] Debug mode: function
    [UNILOG][INFO] Target architecture: DPUCVDX8G_ISA3_C32B6
    [UNILOG][INFO] Graph name: IFNet, with op num: 320
    [UNILOG][INFO] Begin to compile...
    [0;31m[UNILOG][FATAL][XCOM_UNSUPPORT_QUANTIZATION][The fix info is error or unsupported.] elew0's quantization info's variation is too large.
    [m*** Check failure stack trace: ***
    Aborted (core dumped)

    how can I fix it？ many think

**Comment by niuxjxlnx** [comment]
@Windhelm-H ,

Can you upload your result of quantization?

**Comment by CNStanLee** [comment]
Hi, I met this again. The result of the quantization is attached below.
Thanks!!

[quant_info.json](https://github.com/user-attachments/files/20727438/quant_info.json)
