### ISSUE TITLE
pt_vehicle-color-classification_color_224_224_3.63G_2.5 faulty download link

### ISSUE THREAD

**Issue by NessAupera** [Xilinx/Vitis-AI#1059]
pt_vehicle-color-classification_color_224_224_3.63G_2.5 gpu model download link in the [model.yaml](https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/pt_vehicle-color-classification_CompCars_224_224_3.63G_2.5/model.yaml) doesn't work.

https://www.xilinx.com/bin/public/openDownload?filename=pt_vehicle-color-classification_color_224_224_3.63G_2.5.zip

**Comment by NessAupera** [comment]
Hi @wangxd-xlnx,
The link is still unavailable.

**Comment by wangxd-xlnx** [comment]
Hi @NessAupera,

It works now.

**Comment by NessAupera** [comment]
Thank you @wangxd-xlnx.
