### ISSUE TITLE
SSD Mobilenet V1 training issue

### ISSUE THREAD

**Issue by JaviMota** [Xilinx/Vitis-AI#1061]
Hi

Im trying to train the ssd mobilnet v1 with a custom dataset and applying transfer learning following the tensorflow object detection tutorial
https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_detection_qat_tf1.ipynb#scrollTo=Vy4Q_Uva9eii

According to your documentation it seems you also used this repo to train and quantize the example model. These are your instructions to export the model without preprocess and postprocess parts (README located in "tf_ssdmobilenetv1_coco_300_300_2.47G_1.4/code/test/export_tools"):

How to export models of tensorflow/models/research/object_detection without the preprocess and postprocess parts?
  1. First you should back up your exporter.py in YourPath/tensorflow/models/research/object_detection
  2. Then copy exporter_without_pre_post_process.py to YourPath/tensorflow/models/research/object_detection/exporter.py
  3. Finally run frozon_without_pre_post_process.sh to export the inference model without the preprocess and postprocess

After training the ssd mobilnet v1 (using tensorflow object detection repo), I was able to get the same output layers as the model you provide ssd_mobilenet_v1_coco.pb (concat and concat_1). The problem I have is, the model you provide and the model trained using the object detection repo dont seem to be the same. After using your custom "exporter.py" file, it creates a layer that the compiler is not able to compile it, "FakeQuantWithMinMaxVars".

Custom model:
![image](https://user-images.githubusercontent.com/31442693/195580621-9b5803b9-7bb9-43db-9f10-723cc960abd3.png)

ssd_mobilenet_v1_coco.pb: 
![image](https://user-images.githubusercontent.com/31442693/195580697-f6d699ba-4a4c-4d5c-834c-c2a334e2f8be.png)

My questions are:
- Why they look so different?
- How did you get the ssd_mobilenet_v1_coco.pb?
- Do you have some instructions to retrain with custom data the ssd mobilenet v1?

Thank you.

**Comment by jacobdbrown4** [comment]
@JaviMota were you able to figure this out?
