### ISSUE TITLE
Pytorch yolov5 quantization error

### ISSUE THREAD

**Issue by shoayi** [Xilinx/Vitis-AI#1078]
Hi!iI have some questions to ask you.This error occurs when i run this commond"python resnet18_quant.py --quant_model float" to quantize yolov5 model(use the code of "ultralytics"):
![image](https://user-images.githubusercontent.com/67035191/198839516-682f1fc1-858b-4533-b6f6-38579dbadc0f.png)
Have you encountered the same situation?The weights I trained and the code I modified are available at the following link:
链接：https://pan.baidu.com/s/1plB4lEBGayeDwmCjGAIW5Q 
提取码：mnox 
--来自百度网盘超级会员V5的分享

**Comment by niuxjxlnx** [comment]
@shoayi :

It seems that the network shape inference has problem? how about the float model inference? does it work or not?

**Comment by niuxjxlnx** [comment]
@shoayi ,

In your file resnet18_quant.py, function quantization, this line of code is for resnet18 on imagenet:
`input = torch.randn([batch_size, 3, 224, 224])`
It should be changed to your own model input shape (it seems that [1, 3, 640, 640]).

**Comment by IkrameBeggar** [comment]
> Hi!iI have some questions to ask you.This error occurs when i run this commond"python resnet18_quant.py --quant_model float" to quantize yolov5 model(use the code of "ultralytics"): ![image](https://user-images.githubusercontent.com/67035191/198839516-682f1fc1-858b-4533-b6f6-38579dbadc0f.png) Have you encountered the same situation?The weights I trained and the code I modified are available at the following link: 链接：https://pan.baidu.com/s/1plB4lEBGayeDwmCjGAIW5Q 提取码：mnox --来自百度网盘超级会员V5的分享

Hello can you please share with me the files in my email address: ikrame.bgr@gmail.com
