### ISSUE TITLE
Algorithm of convolution

### ISSUE THREAD

**Issue by WhiteCri** [Xilinx/Vitis-AI#1080]
Hello, 

I would like to look around performance and algorithm of convolution layer computation.
Can you provide us manual or resource for stuyding?

Thanks,

**Comment by wangxd-xlnx** [comment]
Hi @WhiteCri 

You could refer to this blog, it's concise and clear.
https://machinelearningmastery.com/convolutional-layers-for-deep-learning-neural-networks/

**Comment by WhiteCri** [comment]
Thank you for kind introduction, but I know how to calculate convolution layer. I think my question was not clear.

I want to learn how vitis-ai integrate data-reuse, pipeline, loop tiling or etc into convolution layer computation. Can you provide some concrete explanations?

**Comment by wangxd-xlnx** [comment]
Hi @WhiteCri 

I still don't quite understand what you're asking. Do you want to know how it is implemented on the dpu core?

**Comment by WhiteCri** [comment]
Oh yeah that's correct! Can you provide some introductions?

**Comment by qianglin-xlnx** [comment]
Hi @WhiteCri 
Sorry. Currently. Vitis-ai compiler is not open source. So we can't provide more information about it.
