### ISSUE TITLE
How to change batch size

### ISSUE THREAD

**Issue by tkkcc** [Xilinx/Vitis-AI#1096]
I success compile and execute a pytorch model on vck190 board. The default `{"target": "DPUCVDX8G_ISA3_C32B6"}` arch.json is passed to `vai_c_xir`. The output xmodel is set to 6 batch size but I only need single batch. So I switch to `{"target": "DPUCVDX8G_ISA3_C32B1"}` arch.json and it compiles. Then I got fingerprint mismatch error on execute. It's seems I have to set DPU to C32B1 first.

from https://docs.xilinx.com/r/en-US/pg389-dpucvdx8g/Configuration-Options, the BATCH_N can be used to change DPU arch, but I don't know what to do exactly.

**Comment by JasonXijieJia** [comment]
Hi @tkkcc 
  You can simply change `BATCH_SingleCU`  in file `vitis_prj/xvdpu_config.mk` as your requirement
  And then re-compile xmodel with the newly generated arch.json file from the project

**Comment by tkkcc** [comment]
Thanks.
