### ISSUE TITLE
Vitis AI optimizer

### ISSUE THREAD

**Issue by ksd777** [Xilinx/Vitis-AI#11]
Hello,

Could you please let me know where can we download Vitis AI Optimizer, together with usage instruction?

Best,
Karlis

**Comment by shua1zhang** [comment]
> Hello,
> 
> Could you please let me know where can we download Vitis AI Optimizer, together with usage instruction?
> 
> Best,
> Karlis

Hi, 

The AI optimizer will be accessed from https://www.xilinx.com/member/ai_optimizer.html. Please apply for access and evaluation license on the page.

Thank you.
