### ISSUE TITLE
Tensorflow 2 VitisQuantizer.quantize_model config not working

### ISSUE THREAD

**Issue by MaenMallah** [Xilinx/Vitis-AI#1104]
We are trying to quantize a TF2 (keras) model and deploy it on FPGA. We are succusfull at this, however, we have some issues regarding the values we get from the FPGA. . Some values deviate slightly which is expected and normal for us. However, some values change significantly .Unfortunately, we cannot share the models or data.

From our analysis, we think the problem has to do with overflow behaviour. The network's output has some outlier values (high negative values). The qauntized model has output quantization of S6.1 (denotation 1), lowest possible value is then -64. The floating point model has output values of (<-150), which should saturate (at least the last layer and possibly the saturation happens earlier through the network). The qauntized model (when run on PC) produces these values to be (-64 or something negative number). We still assume this is correct behaviour if the values are saturated when they overflow. Not all saturate to -64 is probably the result of values saturating during processing and not just the last layer. 

The main problem happens when we compile the model and run it on FPGA using the DPU. The same prodcued outputs behave very weirdly and all become (+64) This does not seem to be the result of wrap-around or saturation. Maybe it truncates the buffer but ignores the sign bit? Is this behaviour expected?

Here we tried to change the quantizer to get around this problem, however, the configs of the [quantize method](https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Quantizer/vai_q_tensorflow2.x/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py#L732) don't seem to take any effect. According to the [documentation ](https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Quantizer/vai_q_tensorflow2.x/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py#L732), we should be able to change the activation bits with kwargs but from the method documentation, it seems we can do it via configs dictionary. We tried both activation_bits = 16, and configs = {"activation_bits":16) but nothing worked and the resulting quantized model still shows 8 bit activations. Addtionally, we tried setting activation_method = 0 to force Non-overflow range optimization but also it didn't take any effect. Are we providing these configurations correctly or do we have to do it differrently? Does the DPU support 16-bit activations?

**Comment by gengxinwu** [comment]
Hi @MaenMallah. DPU does not support 16-bit activations. I would also suggest trying to change the activations quantization method from the default value 1 (Min_MSE method) to 0 (Non_Overflow method).

You can configure _activation_method_ for vitis quantizer just like this:
```
quantizer = vitis_quantize.VitisQuantizer(float_model)
quantized_model = quantizer.quantize_model(calib_dataset=calib_dataset, activation_method=0)
```

**Comment by MaenMallah** [comment]
Hello @gengxinwu, thanks for the reply. I somehow missed this reply. 

I already tried setting the activation_method to zero to force the Non_overflow method but it didn't affect the result. It seems that the config was overridden somewhere. I am not sure if it is an old version as it is been a while since I worked on that project.
