### ISSUE TITLE
YOLOv6 compatibility

### ISSUE THREAD

**Issue by williamlamjy** [Xilinx/Vitis-AI#1109]
Looking to run inference on a YOLOv6 model for real time video classification and was wondering if there is support or compatibility to use vitis to run this on an Ultra96 board.

**Comment by qianglin-xlnx** [comment]
Hi @williamlamjy 
YOLOv6 will be supported in VAI3.0.

**Comment by qianglin-xlnx** [comment]
Hi @williamlamjy 
VAI3.0 is alive now. For YOLOv6, refer to: https://github.com/Xilinx/Vitis-AI/tree/v3.0/examples/vai_library/samples/yolov6
