### ISSUE TITLE
Model Zoo, Multi-threaded Performance

### ISSUE THREAD

**Issue by afzalxo** [Xilinx/Vitis-AI#1110]
The model zoo lists the performance of different models in both single threaded and multi-threaded execution. What is the thread count utilized to obtain the results from multi-threaded configuration? The [README.md](https://github.com/Xilinx/Vitis-AI/tree/master/model_zoo) does not list the thread count utilized for evaluating the FPS numbers for any of the FPGAs.

Thanks

**Comment by afzalxo** [comment]
Could you kindly also specify the number of DPU cores in the DPU IP `DPUCZDX8G_ISA1_B4096` by default? It should be 2 cores if I'm not wrong.

**Comment by afzalxo** [comment]
> Could you kindly also specify the number of DPU cores in the DPU IP `DPUCZDX8G_ISA1_B4096` by default? It should be 2 cores if I'm not wrong.

Its 3 cores.

**Comment by xihuazhanghui** [comment]
If you use the official released images, you can use tool ` show_dpu ` to get the board dpu info.

**Comment by afzalxo** [comment]
This works, thanks a lot. Also, is there any way to check the power consumption of the chip? Save for attaching an external power meter.

**Comment by xihuazhanghui** [comment]
This feature did not release yet.

**Comment by afzalxo** [comment]
Thanks. Closing the thread for now.
