### ISSUE TITLE
In the vitis-ai2.5 version, is the mean normalization in the dpu_task code still done in the cpu?

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1114]
Hello xilinx,

I have checked the code of image mean and normalization processing under the current vitis-ai framework, and I want to confirm with you whether this part of processing is still completed on the cpu？

**Comment by jia0511** [comment]
![微信图片_20221214155528](https://user-images.githubusercontent.com/24822418/207538153-2ba71d78-5777-4803-a01e-cee4cb868f67.png)

**Comment by lishixlnx** [comment]
Yes. You are right.
