### ISSUE TITLE
bert downloaded an empty tarball

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1130]
https://www.xilinx.com/bin/public/openDownload?filename=pt_bert-tiny_SQuADv1.1_384_453M_3.0.zip
https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/tf_bert-base_SQuAD_128_22.34G_3.0/model.yaml
https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/pt_bert-large_%20SQuADv1.1_384_246.42G_3.0/model.yaml

**Comment by wangxd-xlnx** [comment]
Hi @jia0511 

Thanks for your feedback. We will fix these download links as soon as possible.

**Comment by wangxd-xlnx** [comment]
Fixed. @jia0511 You could have another try.

**Comment by jzymessi** [comment]
Hi @wangxd-xlnx :
     I want to deploy bert model on VCK5000. 
     Is there any corresponding deployment code or deployment process?

**Comment by wangxd-xlnx** [comment]
Hi @jzymessi 

The bert series models based on Gemm compiler deployed on VCK5000 will be released in Vitis-AI 3.0.1. It will take ~1 month, please stay tuned.

**Comment by wangxd-xlnx** [comment]
By the way, there is a demo you could refer to. Though it's from Vitis-AI 2.5, not the latest version. @jzymessi

https://github.com/Xilinx/Vitis-AI/tree/2.5/examples/Transformer

**Comment by jzymessi** [comment]
@wangxd-xlnx ：
Is bert deployment of vitis-ai version 3.0.1 called as xmodel?
