### ISSUE TITLE
Does vai_library ONNX Examples run on vck5000?

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#1132]
I found from the documentation that vitis-ai 3.0 vai_library supports running onnx examples, but it seems to only support running on the  Edge at present, does these onnx examples support running on vck5000?

**Comment by qianglin-xlnx** [comment]
Hi @jzymessi 
We do not test ONNX Examples on cloud platform, such as vck5000.  
For cloud platform, you can try WeGO.

**Comment by jzymessi** [comment]
Hi @qianglin-xlnx ：
     Thanks,I will try WeGO.
