### ISSUE TITLE
Vitis-ai3.0 does not support quantization to half precision？

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1139]
Hello xilinx,

It can be seen from the title of the document that it can be converted to fp16, but the content description is converted from fp16 to int8, so I want to confirm that the h5 model here is already an fp16 model. Currently, the quantizers of pytorch and tensorflow still cannot be converted to fp16 Format?

![2023-01-19 09-44-06屏幕截图](https://user-images.githubusercontent.com/24822418/213336167-3389f7bc-9b9b-46fa-aa28-60c5a8d76eba.png)

**Comment by jia0511** [comment]
There are some updates?

**Comment by renjiangyong** [comment]
you can try the vitis-3.5 version.@jia0511

**Comment by zhenzhen-AMD** [comment]
Hi @jia0511 ，
The h5 model in the sample code is in float32 format. The example depicts its conversion to float16.
