### ISSUE TITLE
when I setting up the Host,I meet this question?

### ISSUE THREAD

**Issue by tensorflowt** [Xilinx/Vitis-AI#114]
`Your environment is misconfigured, you probably need to 'unset LD_LIBRARY_PATH'
but please check why this was set in the first place and that it's safe to unset.
The SDK will not operate correctly in most cases when LD_LIBRARY_PATH is set.
For more references see:
  http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN80
  http://xahlee.info/UnixResource_dir/_/ldpath.html`

how can i solve it ?

thks

**Comment by qianglin-xlnx** [comment]
Hi @tensorflowt 
Please follow the prompts to execute this command first :   unset LD_LIBRARY_PATH 
Then execute the following command again:
source <petalinux_sdk>/environment-setup-aarch64-xilinx-linux
Note that <petalinux_sdk> is the location where you install the sdk-2020.1.0.0.sh.

**Comment by tensorflowt** [comment]
it's works,thank you.
