### ISSUE TITLE
Kria KV260 Setup Documentation Update Schedule

### ISSUE THREAD

**Issue by osamuraislice** [Xilinx/Vitis-AI#1142]
Thanks for releasing Vitis-AI V3.0. I will start development using this repository.🎉

I understood that the Vitis-AI/setup folder in the V2.5 branch has been moved to the Vitis-AI/board_setup folder.
[Vitis-AI/setup](https://github.com/Xilinx/Vitis-AI/tree/master/board_setup)

But, the links to the workflow and board setup documentation at the bottom of this page are broken.

I would like to use Vitis-AI V3.0 with Kria KV260, are there any plans to update the documentation?

**Comment by qianglin-xlnx** [comment]
Hi @osamuraislice 
Please refer to : https://xilinx.github.io/Vitis-AI/docs/board_setup/board_setup_mpsoc.html

**Comment by osamuraislice** [comment]
Thank you for your response.
I will check the [github.io](https://xilinx.github.io/Vitis-AI/docs/board_setup/board_setup_mpsoc.html) link and start developing on KV260.
I will close this issue now that the issue is resolved.
