### ISSUE TITLE
How to create quant model without origin float model

### ISSUE THREAD

**Issue by ZQ-zz** [Xilinx/Vitis-AI#1143]
I have my own training framework (conda based) and seems incompatible with vitis-ai quantization environment， so I install vai_q_pytorch from source code . I successd in 'calib' quant mode（with fast finetune）, but failed in 'export_xmodel'. 
Now I want to decople the training env (python, pytorch, vai_q_pytorch  and others) and the deploy environment (vitis ai docker,  vai_q_pytorch and xir). Then I use training env to get quant model, but how to export xmodel in deploy env without origin float model? maybe just use the quantize_result ?
![screenshot-20230120-162218](https://user-images.githubusercontent.com/28952272/213649350-3854bd7d-abfb-4da0-a05e-bda76ac18bcb.png)

**Comment by niuxjxlnx** [comment]
@ZQ-zz :

Origin float model is must to get quant model. 
Please strictly follow the steps of the example resnet18.
