### ISSUE TITLE
Vitis AI 3.0: building DPUCVDX8G_VAI_v3.0 TRD failed

### ISSUE THREAD

**Issue by li900309** [Xilinx/Vitis-AI#1148]
in ./vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/recipes-libs/aks/aks_3.0.bb downloaded from https://www.xilinx.com/bin/public/openDownload?filename=DPUCVDX8G_VAI_v3.0.tar.gz

there is a source URI point to a xilinx internal github address, which causes the petalinux build fail
![image](https://user-images.githubusercontent.com/7360000/215423846-4dc11684-1f19-4b73-befc-18b93de166ee.png)

**Comment by Xlnx78115** [comment]
This issue has been discovered in another case and following patch could resolve it.
[DPUCVDX8G_VAI_v3.0.tar.gz](https://www.xilinx.com/bin/public/openDownload?filename=DPUCVDX8G_VAI_v3.0.tar.gz) updating is on going.

diff --git a/vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/recipes-libs/aks/aks_3.0.bb b/vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/rec
index 143cf4e..e385103 100755
--- a/vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/recipes-libs/aks/aks_3.0.bb
+++ b/vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/recipes-libs/aks/aks_3.0.bb
@@ -4,13 +4,13 @@ DESCRIPTION = "An application to automatically and efficiently pipeline such gra
 LICENSE = "Apache-2.0"
 LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/Apache-2.0;md5=89aea4e17d99a7cacdbeed46a0096b10"
 
-SRC_URI = "git://gitenterprise.xilinx.com/VitisAI/aks.git;protocol=https;branch=master;lfs=0 \
-"
+require recipes-vitis-ai/vitis-ai-library/vitisai.inc
+S = "${WORKDIR}/git/src/AKS"
 
-FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
+PACKAGECONFIG:remove = " test"
+PACKAGECONFIG:remove = " python"
 
-SRCREV = "a2feee648ca81b77c212201de889d995926e4bcd"
-S = "${WORKDIR}/git"
+FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
 
 DEPENDS = "unilog xir vart boost python3-pybind11"
