### ISSUE TITLE
torch quantization documentation does not show how to bfloat16 quantize

### ISSUE THREAD

**Issue by rderp** [Xilinx/Vitis-AI#1151]
It seems like only the tensorflow quantizer supports floating point quantization, at least based on the documentation. We'd like this to be made available in torch quantizer apis. Can someone confirm that this feature works or not?

**Comment by rderp** [comment]
Actually, perhaps I jumped the gun. Appears like there is a resnet and mobilenet torch model quantization example. Documentation seems to imply that only bfloat16 quantization is supported in tensorflow in UG1414. Perhaps a similar thing for torch should be added.

**Comment by rderp** [comment]
Release notes say it is supported for release 3.0.

**Comment by niuxjxlnx** [comment]
@rderp ,

**bfloat16** is not quantized in vitis-ai pytorch quantizer 3.0 version. It only supports **float16**. 
This is because that Pytorch support of **bfloat16** is not completed.

**Comment by rderp** [comment]
@niuxjxlnx Is there an example of how to do float16 quantization with the SDK?

**Comment by rderp** [comment]
@niuxjxlnx could you reopen this around float16 rather than bfloat16?

**Comment by niuxjxlnx** [comment]
@rderp ，

It does not need any special setting or call any different function. You can quantize your float16 model by the approach of quantizing float32 model.
