### ISSUE TITLE
Is there any example for new network models?

### ISSUE THREAD

**Issue by lllkiller-jlll** [Xilinx/Vitis-AI#116]
Hi.

I found that the new models like face_landmark or plate detection/recognition are released in vitis ai v1.2 model zoo.

So, I want to use these models but I can't find any example for new models.

How can I use these models?

Do you have plans for updating new examples?

Thanks.

**Comment by qianglin-xlnx** [comment]
Hi @lllkiller-jlll 
Please find the samples under https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library/overview/samples/
