### ISSUE TITLE
:bug: Quantization print bug

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/Vitis-AI#1165]
When I QAT model in VitisAI3.0 env, I met a annoying print info:
![image](https://user-images.githubusercontent.com/42413198/217986680-ed694e82-986c-4640-a677-d185ee2ebc4d.png)

I check the source code and found the `output_size` of `py_nndct.nn.AdaptiveAvgPool2d` has changed to `[1,1]` in 3.0 compared to `1` in 2.5:
![image](https://user-images.githubusercontent.com/42413198/217987185-d7f73bf8-497d-4af1-87a5-2e815d3915e8.png)
![image](https://user-images.githubusercontent.com/42413198/217987258-6b9b71d5-b079-4a92-90f1-c321362c2bbf.png)

Therefore, the value of expression which in the red box of the figure below is always `true` because `self.output_size` is `[1,1]`:
![image](https://user-images.githubusercontent.com/42413198/217987723-9d4deaba-d26f-4470-95f0-c96b4b54e55a.png)

**Comment by LorenzoSun-V** [comment]
```
if (isinstance(self.output_size,
                   (tuple, list)) and tuple(self.output_size) !=
        (1, 1)) or (isinstance(self.output_size, int) and self.output_size != 1):
      print(
          "[WARNING] For AdaptiveAvgPooling, DPU only supports output size=1"
      )
```
I suppose the code above may solve the print bug.

**Comment by yuwang-xlnx** [comment]
> I check the source code and found the `output_size` of `py_nndct.nn.AdaptiveAvgPool2d` has changed to `[1,1]` in 3.0 compared to `1` in 2.5: ![image](https://user-images.githubusercontent.com/42413198/217987185-d7f73bf8-497d-4af1-87a5-2e815d3915e8.png) ![image](https://user-images.githubusercontent.com/42413198/217987258-6b9b71d5-b079-4a92-90f1-c321362c2bbf.png)
> 
Hi @LorenzoSun-V,

The scripts in above screenshots are used in PTQ, not QAT.
Can you confirm what the output_size of the Pooling layer is ? A simple way to do this is adding a print statement in https://github.com/Xilinx/Vitis-AI/blob/master/src/vai_quantizer/vai_q_pytorch/pytorch_binding/pytorch_nndct/nn/quantization/modules/pooling.py#L69:
`print(self.output_size)`

**Comment by LorenzoSun-V** [comment]
Hi @yuwang-xlnx , I have added the `print` code in `pooling.py` and the output is like:
![image](https://user-images.githubusercontent.com/42413198/218914749-a61b663c-4c55-482a-bbdb-a84c6c65bd1a.png)

`self.output_size` is equal to `[1, 1] indeed.

**Comment by yuwang-xlnx** [comment]
@LorenzoSun-V , Thanks for your feedfack . We'll fix this issue.
