### ISSUE TITLE
QUANTIZER_TORCH_XIR_MISMATCH

### ISSUE THREAD

**Issue by JF-Lee** [Xilinx/Vitis-AI#1177]
I want to install vai_q_pytorch from Vitis-AI-3.0 source code，which version of XIR should I install?

**Comment by Alexiazzf** [comment]
You should install XIR 3.0.

**Comment by JF-Lee** [comment]
> You should install XIR 3.0.

Thanks for you reply, btw, where can I download XIR3.0 package(conda-channel)?

**Comment by Alexiazzf** [comment]
You can refer to this link https://github.com/Xilinx/Vitis-AI/blob/master/docker/common/replace_pytorch.sh#L56
