### ISSUE TITLE
Cannot run AI profiler on VART 2.5 plinux 22.1 ZCU104

### ISSUE THREAD

**Issue by dextroza** [Xilinx/Vitis-AI#1180]
Hi,

I am getting error when trying to run ai profiler on VART 2.5, petalinux 22.1. I am trying to profile my c++ application on ZCU104.

The code:

`$ vaitrace ./app_zcu104.elf`,

The error occurs at the end of profiling:

`APM Stop Collecting

WARNING:root:Cannot open 'zyxclmm_drm/ip_layout'

INFO:root:Generating VTF

INFO:root:Processing xmodel information

INFO:root:SubGraph index duplication: [subgraph_data_upload_0|0]

Traceback (most recent call last):

 File "/usr/bin/vaitrace", line 186, in <module>

   main(*parseCmdLine())

 File "/usr/bin/vaitrace", line 181, in main

   vaitraceWriter.write(options)

 File "/usr/bin/xlnx/vaitrace/[vaitraceWriter.py](https://vaitracewriter.py/)", line 83, in write

   writer.vtf.convert.xat_to_vtf(rawData)

 File "/usr/bin/xlnx/vaitrace/writer/vtf/[convert.py](https://convert.py/)", line 331, in xat_to_vtf

   convert_dpu(xat.get('vart'))

 File "/usr/bin/xlnx/vaitrace/writer/vtf/[convert.py](https://convert.py/)", line 140, in convert_dpu

   dpu_profile_summary = dpu_parser.get_dpu_profile_summary()

 File "/usr/bin/xlnx/vaitrace/writer/parser/vart_parser.py", line 334, in get_dpu_profile_summary

   perf = workload * batch / avg_t * 1000 # to GOP/ms

ZeroDivisionError: float division by zero`

 

I also tried with `$ vaitrace -c config.json` where config.json is:

{
 "options":
 {
   "runmode": "normal",
     "cmd": "./app_zcu104.elf",
     "timeout": 20
 },
 "trace": {

     "enable_trace_list": ["vitis-ai-library", "vart", "opencv", "custom"],
 }
}

but getting the same error.

 

Could someone help me, please? Thanks!

**Comment by jileilxinlix** [comment]
hi @dextroza 
@MasayukiOmura  provides an effective way, maybe you could update the vart version.
thanks @MasayukiOmura

**Comment by MaistoV** [comment]
Did @MasayukiOmura method work? 

I reported the exact same issue [here](https://github.com/Xilinx/Vitis-AI/issues/1202) with Vitis-AI 2.0

**Comment by jileilxinlix** [comment]
> Hi,
> 
> I am getting error when trying to run ai profiler on VART 2.5, petalinux 22.1. I am trying to profile my c++ application on ZCU104.
> 
> The code:
> 
> `$ vaitrace ./app_zcu104.elf`,
> 
> The error occurs at the end of profiling:
> 
> `APM Stop Collecting
> 
> WARNING:root:Cannot open 'zyxclmm_drm/ip_layout'
> 
> INFO:root:Generating VTF
> 
> INFO:root:Processing xmodel information
> 
> INFO:root:SubGraph index duplication: [subgraph_data_upload_0|0]
> 
> Traceback (most recent call last):
> 
> File "/usr/bin/vaitrace", line 186, in
> 
> main(*parseCmdLine())
> 
> File "/usr/bin/vaitrace", line 181, in main
> 
> vaitraceWriter.write(options)
> 
> File "/usr/bin/xlnx/vaitrace/[vaitraceWriter.py](https://vaitracewriter.py/)", line 83, in write
> 
> writer.vtf.convert.xat_to_vtf(rawData)
> 
> File "/usr/bin/xlnx/vaitrace/writer/vtf/[convert.py](https://convert.py/)", line 331, in xat_to_vtf
> 
> convert_dpu(xat.get('vart'))
> 
> File "/usr/bin/xlnx/vaitrace/writer/vtf/[convert.py](https://convert.py/)", line 140, in convert_dpu
> 
> dpu_profile_summary = dpu_parser.get_dpu_profile_summary()
> 
> File "/usr/bin/xlnx/vaitrace/writer/parser/vart_parser.py", line 334, in get_dpu_profile_summary
> 
> perf = workload * batch / avg_t * 1000 # to GOP/ms
> 
> ZeroDivisionError: float division by zero`
> 
> I also tried with `$ vaitrace -c config.json` where config.json is:
> 
> { "options": { "runmode": "normal", "cmd": "./app_zcu104.elf", "timeout": 20 }, "trace": {
> 
> ```
>  "enable_trace_list": ["vitis-ai-library", "vart", "opencv", "custom"],
> ```
> 
> } }
> 
> but getting the same error.
> 
> Could someone help me, please? Thanks!

this error  fixed in version 3.0.1

**Comment by dextroza** [comment]
The issue is solve, we updated VART with "dnf upgrade vart" and it works. Thanks!
