### ISSUE TITLE
Error compiling  vai_library src code

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#1189]
I compile according to the official process : 
https://github.com/Xilinx/Vitis-AI/tree/master/src/vai_library
The following question arises:
![image](https://user-images.githubusercontent.com/51226649/222371616-5de45279-177a-42d7-a877-d03596c1ed83.png)

**Comment by SuZhan0322** [comment]
Hi @jzymessi , AILibrary code need to be compiled in the conda base env. Thanks!

**Comment by jzymessi** [comment]
Thanks!
