### ISSUE TITLE
Can't download Board Image of KV260 in Vitis AI v3.0

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#1192]
Hi,

I can't download kv260 image from below link
[https://xilinx-ax-dl.entitlenow.com/dl/ul/2023/01/06/R210770828/xilinx-kv260-dpu-v2022.2-v3.0.0.img.gz?hash=QsYjeGyUk6zkwxtph6Ka8Q&expires=1677887815&filename=xilinx-kv260-dpu-v2022.2-v3.0.0.img.gz](url)

Is this link broken?

**Comment by eerobert** [comment]
hi

https://xilinx.github.io/Vitis-AI/docs/board_setup/board_setup_mpsoc.html

please try the above link

**Comment by hill19850213** [comment]
It's the same situation for KV260, but the link of zcu102 and zcu104 are workable.

**Comment by eerobert** [comment]
the link works for me.. but require xilinx login

https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-kv260-dpu-v2022.2-v3.0.0.img.gz

i also attach the actual link from the board_setup_mpsoc page for reference

**Comment by hill19850213** [comment]
I have done the login and download this image, but chrome is still shown network error as below
<img width="642" alt="network error" src="https://user-images.githubusercontent.com/40138266/223006949-54147a96-b60b-40c2-92c8-001ef4f4f2d0.PNG">

**Comment by hill19850213** [comment]
Finally, I use vpn to download this file, it is success.
