### ISSUE TITLE
Before Posting Issues, Please Read

### ISSUE THREAD

**Issue by kamranjk** [Xilinx/Vitis-AI#12]
Please check the Vitis AI Forum before posting questions here. We have a community of experts and users on the Vitis AI forum ready to help you with all your questions! 

[Vitis AI Forum](https://forums.xilinx.com/t5/Machine-Learning/bd-p/Deephi)

**Comment by Ali-Flt** [comment]
I think the link to the Forum needs to be updated since the forum has entirely changed.
