### ISSUE TITLE
When I used the official FPS measurement progra（Vitis-AI-3.0） to test the VCK5000, the following abnormal situation occurred.

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#1204]
My host machine only has 24 threads. When testing the model, the specified thread parameter can exceed 24, and the FPS increases as the number of threads increases, but the FPS value specified by the official documentation was not achieved during the test.
![image](https://user-images.githubusercontent.com/51226649/227147843-0dd14888-ca51-4038-bad9-a47d19e27cca.png)

**Comment by rusetom** [comment]
I encountered the same problem.
