### ISSUE TITLE
Numpy version issue 

### ISSUE THREAD

**Issue by ash8327** [Xilinx/Vitis-AI#1207]
Hi,
For building the Vitis AI 3.0 Tensorflow2 container Numpy 1.14 is the requirement. Is it possible to use a newer version of Numpy or will it be updated in the near future? We have some requirements for newer version.

**Comment by renjiangyong** [comment]
hi，@ash8327,  you can update the numpy version in the Vitis AI 3.0 docker. BTW , The Vitis AI 3.5 docker will publish. the numpy version is 1.22.0 in Vitis AI 3.5 docker , you can try it .

**Comment by renjiangyong** [comment]
This issue is open for a long time, we will close it , if you still have some problem about this issue, you can reopen it, Thank you.
