### ISSUE TITLE
Import paths for `vitis_*` files/and Pylance support on VSCode

### ISSUE THREAD

**Issue by cabreraam** [Xilinx/Vitis-AI#1211]
Hi all,

The Python script I've written uses the following import statement:
```python
from tensorflow_model_optimization.quantization.keras import vitis_quantize
```

However, AFAICT, the actual path should be
```
/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py
```

When I run the script in the appropriate `conda` environment, the `from tensorflow_model_optimization.quantization.keras import vitis_quantize` does not fail, and `python` is able to find the correct file. How does this happen? It seems like the import statement is missing some additional paths.

To this end, using the [`pylance` VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) in VSCode, I am unable to resolve this path. But when using the following import statement:
```python
from tensorflow_model_optimization.python.core.quantization.keras.vitis import vitis_quantize  
```
Pylance can resolve the path.

How is it possible to specify just this:
```python
from tensorflow_model_optimization.quantization.keras import vitis_quantize
```

and not this:

```python
from tensorflow_model_optimization.python.core.quantization.keras.vitis import vitis_quantize  
```

Thanks!
Anthony

**Comment by zhenzhen-AMD** [comment]
Hi @cabreraam ,

The issue you're encountering might be related to the Pylance extension in VS Code, not a bug within our tool.

We suggest reporting this issue to the VS Code development team or seeking assistance within the VS Code community.

We sincerely apologize that we are not able to resolve your issue directly. However, should you encounter any other problems while using our tool, please feel free to reach out to us at any time.

Thank you for your understanding and support.
