### ISSUE TITLE
xlnx-dpu 80000000.dpuczdx8g: IRQ index 0 not found

### ISSUE THREAD

**Issue by theo06v** [Xilinx/Vitis-AI#1220]
Hi, I try to create a custom platform my ZCU104 with DPU TRD v4.1 and i'm using Vivado flow. 
There seems to be a problem with the DPU during the boot.
root@xilinx-zcu104-trd:~# dmesg | grep dpu
[ 4.698888] xlnx-dpu 80000000.dpuczdx8g: IRQ index 0 not found
[ 4.704718] xlnx-dpu: probe of 80000000.dpuczdx8g failed with error -22

Should I update the device tree in "system-user.dtsi"?
Also, should I add "CONFIG_dpu" in "user-rootfsconfig"?

**Comment by yangyecs** [comment]
Hi, 
the error message indicates that there might be an issue with interrupt. Please double check if the interrupt connection is correct in your Vivado Block design, there is no need to add eithor device tree node and configuration item in rootfs, as PetaLinux will handle it automatically, the only thing required is to enable the DPU driver in Linux Kernel
more details, please refer to this page 
https://github.com/Xilinx/Vitis-AI/blob/master/dpu/ref_design_docs/README_DPUCZ_Vivado.md
