### ISSUE TITLE
VAI_C Fatal 

### ISSUE THREAD

**Issue by badcook** [Xilinx/Vitis-AI#123]
when I try to compile cf_squeeze_imagenet in vitis-ai-1.0, I met this error:
[VAI_C][Fatal] Check failed for condition [layer_id < model.layer_size()] in [/home/dnnc/dnnc_impl/parser/caffe/caffeparser.cc:215] :Failed to find parameter for [prob] in caffemodel, make sure name in prototxt is consistent with that in caffemodel.
Is there any problem with the deploy.caffemodel and deploy.prototxt?

**Comment by lllkiller-jlll** [comment]
Which Vtisi AI version are you using?

If you use Vitis AI v1.2 now, you should better use cf_squeeze_imagenet_227_227_0.76G_1.2 deployed by Xilinx Model Zoo v1.2.

**Comment by badcook** [comment]
I use vitis-ai-1.0 and the model is from all_models_1.2

**Comment by qianglin-xlnx** [comment]
@badcook 
Please try the following:
![image](https://user-images.githubusercontent.com/58016351/88371375-7c3fdc00-cdc6-11ea-9e04-e16235bf976f.png)
For more details, please refer to readme.md after you unzip the cf_squeeze_imagenet_227_227_0.76G_1.2.zip
