### ISSUE TITLE
VAI_C-BACKEND

### ISSUE THREAD

**Issue by badcook** [Xilinx/Vitis-AI#124]
I got this error when compile vgg16 in Ultra96v2
[VAI_C-BACKEND][Check Failed: kernel_param * input_channel_group <= img_buf_depth][/home/dnnc/submodules/asicv2com/src/Operator/OperatorConv.cpp:75][DATA_OUTRANGE][Data value is out of range!] the kernel size is too much for current arch
*** Check failure stack trace: ***
Is that because this model not fits Ultra96?

**Comment by qianglin-xlnx** [comment]
@badcook 
Yes. For Ultra96v2 with B2304 DPU or B1600 DPU, vgg16_tf and vgg19_tf are not supported.
