### ISSUE TITLE
What mean is DPU output values?

### ISSUE THREAD

**Issue by lllkiller-jlll** [Xilinx/Vitis-AI#1241]
Hi.

I'm trying to using EfficientDet-d2 on DPU.
I downloaded a model from model-zoo, and I'm making program using VART.

And then, I finally saw DPU output tensors data as int8_t.
But most of values are minus.
I've been awared that the DPU output data is unsigned interger. But it seems like signed value.

What means is DPU output values?
For example, is 0xFF value meaning "very low accuracy"? or "very high accuracy"?

p.s. Is there any example source code about EfficientDet? If so, can I provide that?

**Comment by lishixlnx** [comment]
1. dpu output data is int8_t which is signed.
2. DPU output values are 5 groups of data,
  each group hold box-predict and class-predict.
  The value does not indicate the accuracy, it indicate the "class " and "box" predicted.
3. for the example, you can refer to [https://gitenterprise.xilinx.com/Vitis/vitis-ai-staging/tree/vai-3.5-update/examples/vai_library/samples/efficientdet_d2](url)
