### ISSUE TITLE
SSH into ZCU102

### ISSUE THREAD

**Issue by zijian98** [Xilinx/Vitis-AI#1258]
Host platform: Ubuntu 20.04
Target board: ZCU102
Using the latest SD card system image files (PetaLinux 2022.2)

Hi, does anyone knows how to SSH into the board? I have tried many times
```
ssh root@192.168.33.30
```
and entered the password: root
However, I keep getting root@192.168.33.30: Permission denied (publickey,password).

Pinging this address was successful
![Screenshot from 2023-06-16 12-59-33](https://github.com/Xilinx/Vitis-AI/assets/85977135/b8c9f023-3b6e-4e6f-a4a8-f4948cce2b0c)

Any suggested solutions?

**Comment by yangyecs** [comment]
Please refer to this page https://docs.xilinx.com/r/2022.2-English/ug1144-petalinux-tools-reference-guide/Login-Changes

**Comment by zijian98** [comment]
> Please refer to this page https://docs.xilinx.com/r/2022.2-English/ug1144-petalinux-tools-reference-guide/Login-Changes

I am getting petalinux-config command not found. 

The OS image was downloaded from https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Flashing-the-OS-Image-to-the-SD-Card and and I can access the USB-UART port directly using minicom but not through SSH connection.
