### ISSUE TITLE
ZCU102 doesn't show anything with the prebuilt linux SD image 

### ISSUE THREAD

**Issue by tkclimb** [Xilinx/Vitis-AI#126]
I flashed the prebuilt linux image provided below into my SD card and tried to boot the linux image on ZCU102 dev board. 
https://github.com/Xilinx/Vitis-AI/tree/19fca11b451e2825e573c989a44059f7731394ae/VART#setting-up-the-target

However, It doesn't show anything from the serial port.I did checked I followed the official booting flow of the board like the DIP switch settings and where I plugged in the serial cable, the UART software driver, therefore I was able to see the serial port as device files under `/dev/ttyUSB(X)` (X should be the number), but I couldn't see any messages on the console and couldn't type anything.
Is there anybody succeeded to boot the image correctly??

**Comment by likecaulfield** [comment]
Hi,

Have you managed to solve the issue?
