### ISSUE TITLE
cannot find -lvitis_ai_library-xnnpp

### ISSUE THREAD

**Issue by zijian98** [Xilinx/Vitis-AI#1263]
Image OS: Ubuntu 20
Vitis-Ai 2.5

I am attempting to build the yolov4 examples with the script, however I am getting the /usr/bin/ld: cannot find -lvitis_ai_library-xnnpp error. Latest vitis ai library already installed with sudo apt -y install vitis-ai-library.

Any fix for this issue?

Thank you

**Comment by lishixlnx** [comment]
1. Please use ldd command on the yolov4 test executable file to check if necessary lib is missing.
2. Please check that /usr/lib/libvitis_ai_library-xnnpp.so exists.
