### ISSUE TITLE
compile proxylessnas error

### ISSUE THREAD

**Issue by badcook** [Xilinx/Vitis-AI#127]
I met this problem when compile proxylessnas into *.elf
[VAI_C-BACKEND][Check Failed: shift_cut >= 0][/home/dnnc/submodules/asicv2com/src/SlNode/SlNodeConv.cpp:83][DATA_OUTRANGE][Data value is out of range!]

**Comment by qianglin-xlnx** [comment]
Hi @badcook
shift_cut = input_pos + weights_pos - output_pos 
And shift_cut  value must be >= 0. If shift_cut is <0, it can usually be one of the following reasons, could you please check the following.
1. If the original float model is not trained sufficiently, the accuracy is very poor, which leads to the unreasonable fixed-point position.
2. The original model training is very sufficient, but the use of false input images for fixed-point will also lead to unreasonable fixed-point position.
3. The quantization tool itself may have some bugs for new model, in this case, please contact your Xilinx FAE.

**Comment by badcook** [comment]
Thank you so much! I will check my model @qianglin-xlnx

**Comment by zxw602** [comment]
Hi @badcook ,

I met the same problem with you. Could you pls share me your updates? Have you already fixed it? Thanks!

Zxw

**Comment by qianglin-xlnx** [comment]
Hi @badcook 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
