### ISSUE TITLE
cannot import name 'decent_q' Vitis-AI 3.0 tf1

### ISSUE THREAD

**Issue by JaviMota** [Xilinx/Vitis-AI#1277]
Hi

I want to evaluate the quantized model using the script of the tf_ssdmobilenetv1 (taken from the example in vitis ai library) but Im getting this error:

**cannot import name 'decent_q'**

The error appears when I execute the following lines of code:

**if FLAGS.use_quantize:
        from tensorflow.contrib import decent_q**

Is the decent_q library necessary to evaluate a quantized model? In such case, how can I get it?

Im using the docker image xilinx/vitis-ai-tensorflow-gpu from Vitis-AI 3.0

Thank you.

**Comment by gengxinwu** [comment]
From Vitis-AI 3.0, tf1 has changed from a contributor to a Tensorflow plugin. Please try changing "from tensorflow.contrib import decent_q" to "import vai_q_tensorflow as decent_q".

**Comment by zhenzhen-AMD** [comment]
Closing this for now. Please re-open if there are any other concerns. Thanks.

**Comment by amonni5** [comment]
simil issue

 import tensorflow.contrib.decent_q
ModuleNotFoundError: No module named 'tensorflow.contrib.decent_q'

in evaluating step of 02-mnist-tutorial

vitis-ai 3.5 gpu
