### ISSUE TITLE
xrt 

### ISSUE THREAD

**Issue by MohamedRaizz** [Xilinx/Vitis-AI#1293]
how to download xrt .deb package for 2023.1 for MPSOC platfoms

**Comment by quentonh** [comment]
@MohamedRaizz I will respond via your forum.  Please consider closing this issue as it is not Vitis AI specific.

**Comment by MohamedRaizz** [comment]
> @MohamedRaizz I will respond via your forum query. Please consider closing this issue as it is not Vitis AI specific.
@quentonh thank you sir
