### ISSUE TITLE
Modify yolov5 post processing

### ISSUE THREAD

**Issue by zijian98** [Xilinx/Vitis-AI#1355]
Hi, may I know which file can I modify to change the post processing function in Vitis AI 3.0 as I have a modified yolov5 model with extra parameters. Thank You!

**Comment by lishixlnx** [comment]
xnnpp/include/vitis/ai/nnpp/yolov5.hpp
xnnpp/src/yolov5.cpp

**Comment by zijian98** [comment]
> xnnpp/include/vitis/ai/nnpp/yolov5.hpp xnnpp/src/yolov5.cpp

Thanks for the reply, however may I know how to recompile these modified cpp files so that I can deploy onto zcu102?
