### ISSUE TITLE
 generate xmodel but get error

### ISSUE THREAD

**Issue by holastq** [Xilinx/Vitis-AI#1356]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20231023 02:02:13.699882   590 tool_function.cpp:171] [UNILOG][WARNING] The operator named Transweather__Transweather_Tenc_Tenc__OverlapPatchEmbed_patch_embed1__LayerNorm_norm__ret_9, type: nndct_layer_norm, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
W20231023 02:02:13.731287   590 tool_function.cpp:171] [UNILOG][WARNING] The operator named Transweather__Transweather_Tenc_Tenc__Block_block1__ModuleList_0__Attention_attn__ret_53, type: nndct_select, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
W20231023 02:02:14.587817   590 tool_function.cpp:171] [UNILOG][WARNING] The operator named Transweather__Transweather_Tdec_Tdec__Block_dec_block1__ModuleList_0__Attention_dec_attn__29225, type: nndct_repeat, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
F20231023 02:02:14.627684   590 shape_inference.cpp:1760] [UNILOG][FATAL][XIR_INVALID_ARG_OCCUR][Invalid arg occurence!] xir::Op{name = Transweather__Transweather_Tdec_Tdec__Block_dec_block1__ModuleList_0__Attention_dec_attn__ret_943, type = matmul}'s two inputs shape unmatch, the multiplier's shape is {1, 64, 64, 64}, but the multiplicand's shape is {1, 64, 8, 64}, according to the definetion of xir::matmul, their shape are unmatching.
*** Check failure stack trace: ***
[1]+  Killed                  python tw_quant.py -quant_mode test -subset_len 1 -batch_size=1 -deploy
Aborted
```

class Attention_dec(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0., sr_ratio=1):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."
        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5
        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.kv = nn.Linear(dim, dim * 2, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)
        self.task_query = nn.Parameter(torch.randn(1,48,dim))
        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr = nn.Conv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm = nn.LayerNorm(dim)

    def forward(self, x, H, W):
        
        B, N, C = x.shape
        task_q = self.task_query
        task_q = task_q.unsqueeze(0).repeat(B,1,1,1)
        task_q = task_q.squeeze(1)#

        q = self.q(task_q).reshape(B, task_q.shape[1], self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        kv = self.kv(x).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]
        q = torch.nn.functional.interpolate(q, size=(v.shape[2],v.shape[3]))
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)
        print("attn:{}".format(attn.shape))
        print("v:{}".format(v.shape))
        x = (attn @ v).transpose(1, 2)#1 64 8 64
        x = x.reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x
```
It shows that  two inputs shape does not match when matmul, but I have no problem running and quantizing when just testing without deploy. The above problem only occurs when generating xmodel. I'm confused about that.

**Comment by lishixlnx** [comment]
this op is not supported for this special input format.
User need provide their own implementation for customer_op.
please refer to https://docs.xilinx.com/r/en-US/ug1354-xilinx-ai-sdk/Implementing-and-Registering-Custom-Operators
