### ISSUE TITLE
VITIS-AI for windows?

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#136]
Hello,

I am wondering if VITIS-AI is limited to linux distributions only. Since it is docker based it should be possible to execute in on Windows - however the docker_run.sh files are Linux specific. 

Is there any plan to get vitis-ai on windows or am I missing something?

**Comment by hanxue** [comment]
Hi @kevinkit , 

Vitis AI is distributed as Docker images - [any operating system that supports Docker ](https://github.com/Xilinx/Vitis-AI/blob/master/doc/install_docker/README.md)(specifically Docker 19.03.1 and above) can run Vitis AI. I have been able to run Vitis AI on a Windows 10 laptop with Docker for Windows installed. 

1. Install [Docker for Windows](https://docs.docker.com/docker-for-windows/install/)
2. Start Docker Desktop
3. Open up cmd, powershell or any Windows terminal, and you will be able to run all the `docker` commands

**Comment by kevinkit** [comment]
Hey, 

Thank you for your reply  - I am little bit confused : In the docker_run.sh file https://github.com/Xilinx/Vitis-AI/blob/master/docker_run.sh 

the docker run commands are very unix specific using folders that do not exist in windows like /opt/xilinx/overlaybins etc. will this cause any trouble?

**Comment by hanxue** [comment]
When you are running Docker for Windows, there is a thin layer of Linux, specifically Linux Container Support running on top of Windows. 

![image](https://user-images.githubusercontent.com/760008/92406436-9bbe7880-f16a-11ea-8f1b-78139f27ea8a.png)

In short, when using Docker for Windows and using the `docker` commands on Linux-based Docker images, you are running in a virtualized Linux environment. 

Paths such as /opt/xilinx/overlaybins and /workspace are available within the virtual Linux environment in Docker for Windows; they will not be mapped to the host Windows filesystem. Therefore, you do not have to worry about Linux file paths in Vitis AI not working on a Windows 10 machine running Docker.

**Comment by kevinkit** [comment]
Thank you really much for that explanation! This helps a lot, sadly I am forced to work with a very old windows version that is not supported by the newest docker file - looking forward for an upgrade !

**Comment by kevinkit** [comment]
It worked under windows with cpu docker, however it seems to be a little bit harder with gpu - how do I know my device id  that i need to parse? What can i do if it does not find the nvidia runtime?

**Comment by daivikbhatia** [comment]
Hi, How did you make it work for CPU? I installed latest version of docker, pulled the Vitis-AI repository from git in git bash and followed the rest of instructions,
I got this error while running docker:
find: ‘/dev/dri’: No such file or directory

and this error while building CPU docker:
failed to solve with frontend dockerfile.v0: failed to resolve dockerfile: failed to build LLB: error from sender: DockerfileCPU is not a directory

Please help!

**Comment by hanxue** [comment]
@kevinkit just noticed your follow up question. Unfortunately nvidia-docker is not supported in Windows, and as far as I understand there is no plans to make nvidia-docker available on Windows https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

**Comment by kevinkit** [comment]
@hanxue thank you, i got some success with the fact that windows is now supporting the linux subsystem, but it is so long ago that i do not quit recall it

**Comment by krishnajy** [comment]
Openvino  AI  system  works on windows 10 .  Uses Docker , Python , visual studio , builder c/c++ ,  tensorflow .. .....
