### ISSUE TITLE
nput_shapes should be 4-dimension int shape list (support unknown batch_size), e.g. ?,224,224,3 or 1,299,299,3'

### ISSUE THREAD

**Issue by cena001plus** [Xilinx/Vitis-AI#137]
**when i use vai_q_tensorflow to quantize the pb model which is about LSTM,  which input tensor has 3d type, for example （？，60， 8）， ? is batch size, 60 is time_step,  8 is input 's feature. and i found the examples almost is about CNN, i want to know how i fix this isues?**

```
vai_q_tensorflow quantize \
--input_frozen_graph  modelx.pb \
--input_nodes  input_node \
--input_shapes ?,60,8 \
--output_nodes output_node \
--input_fn input_fn \
--output_dir ./qauantize_results \
```

  _input_shapes = _parse_input_shapes(input_nodes, flags.input_shapes)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/decent_q.py", line 210, in _parse_input_shapes
    'Input_shapes should be 4-dimension int shape list (support unknown batch_size), e.g. ?,224,224,3 or 1,299,299,3'_

**Comment by qianglin-xlnx** [comment]
Hi @cena001plus 
So far as I know, LSTM model is not supported by vai_q_tensorflow.
