### ISSUE TITLE
Check failed: !get_factory_methods().empty()

### ISSUE THREAD

**Issue by a42385029** [Xilinx/Vitis-AI#1469]
root@pr02:~/Vitis-AI/examples/vai_runtime/resnet50# lsmod | grep -i dpu
root@pr02:~/Vitis-AI/examples/vai_runtime/resnet50# ./resnet50 /usr/share/vitis_ai_library/models/resnet50/resnet50.xmodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1119 17:36:31.009404  1023 main.cc:292] create running for subgraph: subgraph_conv1
F1119 17:36:31.019660  1023 dpu_controller.cpp:52] Check failed: !get_factory_methods().empty()
*** Check failure stack trace: ***
Aborted
root@pr02:~/Vitis-AI/examples/vai_runtime/resnet50# xdputil query
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1119 17:36:41.532882  1026 xrt_device_handle.cpp:44] Check failed: !get_factory_methods().empty()
*** Check failure stack trace: ***
/usr/bin/xdputil: line 20:  1026 Aborted                 /usr/bin/python3 -m xdputil $*
root@pr02:~/Vitis-AI/examples/vai_runtime/resnet50#

**Comment by sathy543** [comment]
Hi,Can you please share the solution for above error
Tq
