### ISSUE TITLE
Reference for Vitis AI Quantization 

### ISSUE THREAD

**Issue by FrankXinqi** [Xilinx/Vitis-AI#148]
Could I ask for the reference publication for quantization algorithm in Vitis AI? This is not mentioned in Vitis AI User Guide. I want to know which paper should I refer to when I use Vitis AI quantization.

If possible, the reference for pruning as well.

Many thanks.

**Comment by qianglin-xlnx** [comment]
Hi @FrankXinqi 
I'm afraid there is no reference for quantization algorithm. It's recommended that you can refer to the following 2 documents to use the quantization tools.
UG1414: https://www.xilinx.com/html_docs/vitis_ai/1_2/uim1570695919827.html
UG1333: https://www.xilinx.com/support/documentation/sw_manuals/vitis_ai/1_2/ug1333-ai-optimizer.pdf

**Comment by FrankXinqi** [comment]
Many thanks @qianglin-xlnx 
I was aware of the two documents. The reason I am asking for that is that VitisAI quantization does not perform desired result to reduce model size in a lot. 

If no refernce can be provided, please refer to #150. I am wondering if the algorithm only quantize FC layers, rather than CNN and FC layers.

**Comment by FrankXinqi** [comment]
Thanks for the information. If there are updates about quantization algorithms used in Vitis AI, please let me know. 

I close this issue now.
