### ISSUE TITLE
tf_superpoint quantization scripts

### ISSUE THREAD

**Issue by CroosJJSE** [Xilinx/Vitis-AI#1489]
hi, i am an 4th year undergraduate, involved in an project where i am implementing customized superpoint (pytorch) based SLAM on KRIA KR260, 
I am struggling to do quantizing and pruning using Vitis AI,
I saw the tf_superpoint model on model zoo,
if i can get that quantizing and pruning python scripts of tf_superpoint, it will be helpful for my project,
Your help is so appreciable
Thank you

**Comment by jimheaton** [comment]
I don't think this model was pruned, so we don't have scripts for that.
The training and quantization code should be here: https://www.xilinx.com/bin/public/openDownload?filename=tf_superpoint_3.5.zip

**Comment by CroosJJSE** [comment]
thank you,
i will check it
