### ISSUE TITLE
facedetect not working

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/Vitis-AI#15]
whatever face detect given in apps folder here was supported by ml-suite only not updated

**Comment by qianglin-xlnx** [comment]
Hi @durgabhavaniv 
I wonder if you have solved this issue. If not, I will submit this issue to the engineer in charge of it. If it has been resolved, please close this issue.
Note that if we do not receive any reply from you within 2 weeks, we will assume that this issue has been resolved and will close this issue. Thank you.

**Comment by qianglin-xlnx** [comment]
Hi @durgabhavaniv 
Since I haven't received your reply for a long time, I will close this issue. If you still have any questions, you can reopen this issue. Thank you.
