### ISSUE TITLE
are all tf versions supported?

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#155]
I tried to look through the docs but could not find any information about the supported tensorflow versions. 

Can I use it with tf 1.15.0 and / or tf. 2.x ? Is there any limitation?

Cheers,

kevinkit

**Comment by foolmarks** [comment]
Vitis-AI 1.2 supports TF 1.15.2 but not TF2.x

**Comment by kevinkit** [comment]
Thanks for the info, where did you find it?
Is there any plan to support tf2 in the future?

**Comment by qianglin-xlnx** [comment]
Hi @kevinkit 
TF2 is supported in VAI1.3 and later.
