### ISSUE TITLE
docker: Error response from daemon: Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#157]
I had this error when trying to run the gpu container. I could resolve it by changing the 

`--runtime=nvida `to `--gpus all `

as discussed here:

https://github.com/NVIDIA/nvidia-docker/issues/838 

I am not sure if this is related to the docker image and if should be changed in upcoming releases

**Comment by hanxue** [comment]
Hi @kevinkit ,

The nvidia-docker2 package has been updated to use `--gpus all` instead of `--runtime=nvidia`, see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker 

We will be updating the docker_run.sh script and documentation in the next release.

**Comment by serser** [comment]
For me, I need to install nvidia runtime by https://stackoverflow.com/questions/52865988/nvidia-docker-unknown-runtime-specified-nvidia
