### ISSUE TITLE
[DECENT_WARNING] Scale output to simulate DPU.

### ISSUE THREAD

**Issue by jimd6776** [Xilinx/Vitis-AI#170]
Hi,

When I try to quantize a model for Alveo U50 the quantizer throws the following warning:

> [DECENT_WARNING] Scale output of avg_pool node average_pooling2d_2/AvgPool to simulate DPU.

Then the evaluation on the quantized graph is very bad with low accuracy (and I think the DPU also runs slow with the xmodel as well). What is the meaning of this warning and how to prevent this?

Thanks in advance.

**Comment by Afef00** [comment]
@jimd6776  have you found the solution?
