### ISSUE TITLE
Is there the pose detection example for Alveo U250?

### ISSUE THREAD

**Issue by lllkiller-jlll** [Xilinx/Vitis-AI#172]
Hi.

I'm looking for pose detection example for Alveo U250.

I found the pose detection example in VART but it seems to be unavailable on U250.

Is there any pose detection example for Alveo U250?

**Comment by sumitn-xilinx** [comment]
Vitis AI 1.2 doesn't have a working openpose sample for U250. 
It should be available in the upcoming release (1.3).

**Comment by lllkiller-jlll** [comment]
Thanks for your reply @sumitn-xilinx.

May I ask when v1.3 is released?

**Comment by sumitn-xilinx** [comment]
In Dec '20.
