### ISSUE TITLE
Vitis AI Compiler for Caffe model error

### ISSUE THREAD

**Issue by JerrySciangula** [Xilinx/Vitis-AI#173]
Hi everyone,

I'm a student at Scuola Superiore Sant'Anna in Pisa. 

I'm trying to accelerate a YoloV3 model on a ZCU102 ultrascale+. It is a network of the Apollo simulator (https://github.com/lgsvl/apollo-5.0/tree/simulator/modules/perception/production/data/perception/camera/models/yolo_obstacle_detector/3d-r4-half). I can successfully quantize the model using vai_q_caffe and the tool correctly generates the 4 quantize_results files. 

When I try to compile the model using vai_c_caffe, it outputs: 

**[VAI_C][Error] Only Convolution/Deconvolution/DepthwiseConv/DepthwiseDeconv is supported, but group attribute value for current layer [conv6_1] is 2 
[VAI_C][Error] Parsing layer graph failed.**

Could anyone explain me the error and how to fix it, if it is possible?

**Comment by Mookel** [comment]
Hi, @JerrySciangula  our Compiler only supports normal convolution(group = 1) or depthwise-like convolution(group = input channel) because of DPU constraints, other group values are not supported yet. To fix this, you have to modify and re-train your model.
