### ISSUE TITLE
General question about DPU 

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#181]
When Looking at the DPU Ip Core i noticed that the DPU has one AXI Slave Input and three outputs, where one of these outputs is titled "DPU0_M_AXI_INSTR" - I suppose, that INSTR means INSTRUCTIONS - however, if the DPU is thought as Co-Prozessor and the Instructions are coming from the APU - why isn't there a Slave axi for Instructions, and why has the DPU a Master instruction axi ? Or is the MASTER INSTR output something different?

Thank you for your help

**Comment by foolmarks** [comment]
The DPU reads its instructions from the compiled model file (.elf for Zynq, .model for Alveo) which is in memory.It also reads and writes data to external memory.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kevin <notifications@github.com> Date: 15/10/2020  11:38  (GMT+01:00) To: Xilinx/Vitis-AI <Vitis-AI@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Xilinx/Vitis-AI] General question about DPU  (#181) 
When Looking at the DPU Ip Core i noticed that the DPU has one AXI Slave Input and three outputs, where one of these outputs is titled "DPU0_M_AXI_INSTR" - I suppose, that INSTR means INSTRUCTIONS - however, if the DPU is thought as Co-Prozessor and the Instructions are coming from the APU - why isn't there a Slave axi for Instructions, and why has the DPU a Master instruction axi ? Or is the MASTER INSTR output something different?
Thank you for your help

**Comment by kevinkit** [comment]
Thank you - so what is the INSTR Axi port for?

**Comment by JasonXijieJia** [comment]
Hi @kevinkit 
  The instructions are stored in DDR statically by the runtime. Then the master AXI INSTR port fetches the instructions from ddr in dma mode. 
  Thus the cpu could be released for other threads.
