### ISSUE TITLE
[DNNDK_XRT] Cannot find device, index: 0 when using dexplorer

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#183]
When starting my petalinux on a ZCU106 and executing the command `dexplorer -w ` I get the following message:

`[DNNDK_XRT] Cannot find device, index: 0 `

Is this a common behaviour? Why does it not find my DPU? Is it the device-tree? Did I forgot to install something?

**Comment by x3chen** [comment]
When XRT couldn't probe any device, dexplorer will report the error. 
Please review your platform first. u may find something different via commands "xbutil scan" and "cat /proc/interrupts"

**Comment by kevinkit** [comment]
![image](https://user-images.githubusercontent.com/6839921/96693919-17c1f800-1388-11eb-8338-b4d9a441ccc5.png)
![image](https://user-images.githubusercontent.com/6839921/96694212-76877180-1388-11eb-9769-992f0e6065d2.png)

I am an absolute newbie when it comes to embedded Linux - but it looks like to me that the DPU is not found at all? Can I check if this is due to my Hardware Design or if I messed up the device-tree somehow?

**Comment by x3chen** [comment]
ZOCL is linux kernel driver for xrt. "ZOCL: unknown" is incorrect. 
Have u added zocl node in device node? please check your project with official design.

**Comment by kevinkit** [comment]
Thank you very much, I added it by using `petalinux-config -c rootfs `  and then select in the user package

![image](https://user-images.githubusercontent.com/6839921/96713269-9d51a200-13a0-11eb-864d-2d2e3f8d4108.png)
Is that what is meant by device node or do I need to add it somewhere else, too? 
What is meant by the "official design" ? The TRD to include a dpu or the bsp ?

**Comment by x3chen** [comment]
please use "lsmod" to check zocl has been insmod
zocl.ko is in the directory /lib/modules/`uname -r`/extra

the official platform design is as follows:
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/blob/master/Xilinx_Official_Platforms/zcu104_base/petalinux/project-spec/meta-user/recipes-bsp/device-tree/files/system-user.dtsi

**Comment by Tsukasa0403** [comment]
Hi, I have the same problem, but I found out that there are missing packages in the user package.
How did you create the petalinux project? Please let me know. Thank you.
 
![螢幕擷取畫面 2020-10-22 171357](https://user-images.githubusercontent.com/73281446/96851017-1aa51180-148a-11eb-9a09-b6182fac087b.png)

**Comment by kevinkit** [comment]
@Tsukasa0403 i do not know if these too are related, maybe open up another issue for this on how to add user-packages

**Comment by qianglin-xlnx** [comment]
Hi @kevinkit 
As it has been a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please open a new issue for it. Thank you.
