### ISSUE TITLE
Missing dependency glog when trying to install libunilog via rpm

### ISSUE THREAD

**Issue by kevinkit** [Xilinx/Vitis-AI#187]
want to install the vitis-ai runtime libraries on my ZCU16 custom device. However, upon copying the respective files and trying the following command:

rpm -ivh --force --ignoresize libtarget-factory-1.2.0-r10.aarch64.rpm

 

I get greeted with this error message:

error: Failed dependencies:
libunilog >= 1.2.0 is needed by libtarget-factory-1.2.0-r10.aarch64
/bin/sh is needed by libtarget-factory-1.2.0-r10.aarch64

**Comment by qianglin-xlnx** [comment]
@kevinkit 
You can follow the step 5 in https://github.com/Xilinx/Vitis-AI/tree/v1.1/Vitis-AI-Library#setting-up-the-host to build the glog-0.4.0,  then install it on the target, as the following show.

![image](https://user-images.githubusercontent.com/58016351/97126333-841a6e00-1771-11eb-8056-4021c73cc0f5.png)

**Comment by kevinkit** [comment]
Thank you, I will try that.

Why is this mentioned in the v1.1, but not in v1.2 anymore?

**Comment by kevinkit** [comment]
I tried it, but sadly the error remains:

![image](https://user-images.githubusercontent.com/6839921/97161318-eed1a680-177d-11eb-983d-1a61258113e8.png)

Besides glog it also points out that /bin/sh is needed, however when I look at the folder /bin it is clearly there.

Nevetheless, I checked with `ldconfig -p | grep libglog` to show me the installed libraries:

![image](https://user-images.githubusercontent.com/6839921/97162064-f80f4300-177e-11eb-986d-faea290b8f4e.png)

However, when I check, libglog.so.0.4.0 is there. 
![image](https://user-images.githubusercontent.com/6839921/97162573-adda9180-177f-11eb-9dd3-cfa46f7c50ff.png)

**Comment by qianglin-xlnx** [comment]
@kevinkit 
add this option when install the lib: --nodeps
and try it again.

**Comment by kevinkit** [comment]
thank you very much - this resulted in promising results:

![image](https://user-images.githubusercontent.com/6839921/97164583-a23c9a00-1782-11eb-954a-ea81ae0bc089.png)
I will report back when this may lead to other errors, however for now I will close this issue. 

Again, thank you very much for your help
