### ISSUE TITLE
TVM instructions should note need for network to build Docker container

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/Vitis-AI#191]
More of a suggestion than an issue, but the build process expects to be able to downloads repos from within the Docker container so the command "bash ./build.sh ci_vai_1x bash" as given in https://github.com/Xilinx/Vitis-AI/blob/master/tvm/README.md should probably be "bash ./build.sh ci_vai_1x --net=host bash" for most (all?) cases.

This --net option is, however, documented in the build.sh script

**Comment by janifer112x** [comment]
Thanks for the suggestion, will check it.
