### ISSUE TITLE
My first question just after exploring the repository

### ISSUE THREAD

**Issue by xuzhenyu69** [Xilinx/Vitis-AI#20]
Is Vitis supported other Zynq-7000 platform except the platforms listed in the tutorial?

**Comment by sadicLiu** [comment]
Hi @xuzhenyu69 , have you found the answer? I want to run yolov3-tiny on Zynq-7045, but it seems Zynq-7000 is not supported.

**Comment by xuzhenyu69** [comment]
> Hi @xuzhenyu69 , have you found the answer? I want to run yolov3-tiny on Zynq-7045, but it seems Zynq-7000 is not supported.

Maybe you should custom your hardware platform by following this [https://github.com/gewuek/vitis_ai_custom_platform_flow](https://github.com/gewuek/vitis_ai_custom_platform_flow)

**Comment by sadicLiu** [comment]
@xuzhenyu69 I will try it, thanks a lot!
