### ISSUE TITLE
A possible bug in function IntegerComposition()

### ISSUE THREAD

**Issue by puffdrum** [Xilinx/Vitis-AI#200]
- path: Vitis-AI-Quantizer/vai_q_tensorflow/tensorflow/contrib/decent_q/utils/graph_quantizer.cc
- ques: when it comes to (16,16,8192), the “while” loop can be never jumped out of.
- suggestion on code modification: add "one_round_failed = true;" between line 1410 and line 1411.

**Comment by xieyi4650** [comment]
@puffdrum Yes, you are right. Thank you.

**Comment by qianglin-xlnx** [comment]
It's fixed in VAI1.3.
