### ISSUE TITLE
Questions about the implementation principle of quantizer

### ISSUE THREAD

**Issue by puffdrum** [Xilinx/Vitis-AI#201]
Hi, everyone!

I try to understand the quantization algorithm of this quantizer. Is there a reference paper for the algorithm implementation of this quantizer?

**Comment by qianglin-xlnx** [comment]
@puffdrum 
Please refer to https://github.com/Xilinx/Vitis-AI/issues/148
Also, you can find the opensource of quantizer here: https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Quantizer
