### ISSUE TITLE
Vitis AI PointPillars can offer models ? onnx?

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#210]
Vitis AI运行PointPillars模型，实现高精度多类别的3D目标检测

**Comment by qianglin-xlnx** [comment]
@zyxcambridge 
PointPillars model is supported in VAI1.3. It will be released soon.

**Comment by andyluo7** [comment]
Please refer to https://github.com/Xilinx/Vitis-AI/blob/master/models/AI-Model-Zoo/model-list/pt_pointpillars_kitti_12000_100_10.8G_1.3/model.yaml

**Comment by zyxcambridge** [comment]
> Please refer to [https://github.com/Xilinx/Vitis-AI/blob/master/models/AI-Model-Zoo/model-list/pt_pointpillars_kitti_12000_100_10.8G_1.3/model.yaml](https://github.com/Xilinx/Vitis-AI/blob/master/models/AI-Model-Zoo/model-list/pt_pointpillars_kitti_12000_100_10.8G_1.3/model.yaml?rgh-link-date=2020-12-22T19%3A05%3A46Z)

你们的时延 FPS 包括 detection 也就是后处理部分吗，包括 nms 吗？
Does your delay FPS include detection, which is the post-processing part, including NMS?

**Comment by zyxcambridge** [comment]
> > Please refer to [https://github.com/Xilinx/Vitis-AI/blob/master/models/AI-Model-Zoo/model-list/pt_pointpillars_kitti_12000_100_10.8G_1.3/model.yaml](https://github.com/Xilinx/Vitis-AI/blob/master/models/AI-Model-Zoo/model-list/pt_pointpillars_kitti_12000_100_10.8G_1.3/model.yaml?rgh-link-date=2020-12-28T02%3A58%3A11Z)
> 
> 你们的时延 FPS 包括 detection 也就是后处理部分吗，包括 nms 吗？
> Does your delay FPS include detection, which is the post-processing part, including NMS?

  __TIC__(PP_total)
  __TIC__(PP_pre)
  pre_->process_net0(points);
  __TOC__(PP_pre)

  __TIC__(anchor_and_dpu)  // about 19ms, so it's shorter than the dpu0+dpu1+pp_middle time.
  thread anchor_mask_t(&PointPillarsPost::get_anchors_mask , post_.get() , pre_->pre_dict_); 
   //  anchor_mask_t.join();  // move fronter for easy debug

  thread process_net1_cleanmem_t(&PointPillarsPre::process_net1_cleanmem , pre_.get() );

  __TIC__(PP_dpu0)
  m0_.configurable_dpu_task_->run(0);
  __TOC__(PP_dpu0)

  process_net1_cleanmem_t.join();
  __TIC__(PP_middle)
  pre_->process_net1();
  __TOC__(PP_middle)

  __TIC__(PP_dpu1)
  m1_.configurable_dpu_task_->run(0);
  __TOC__(PP_dpu1)

   anchor_mask_t.join();
  __TOC__(anchor_and_dpu)

  __TIC__(PP_post)
  auto results = post_->post_process( );
  __TOC__(PP_post)
  __TOC__(PP_total)
