### ISSUE TITLE
Why the format of weights is float32 in the deploy.caffemodel after quantization?

### ISSUE THREAD

**Issue by zxw602** [Xilinx/Vitis-AI#218]
Hi everyone,

I am running a Resnet 50 example on Vitis-AI with ZCU104. After quantization, "deploy.caffemodel" was generated. And here is the problem:  I opened the "deploy.caffemodel" via Netron. However, it seems like the format of weights is still float 32 after quantization, instead of INT8. So, I am writing to figure out that is there any "dequantization" part during the final process of model quantization (which converts INT8 to Float 32 back again) ? Or there is just something going wrong with my code? Could anyone help me on this? Many thanks!! 

I attached the snapshot here for review.
![snapshot](https://user-images.githubusercontent.com/55753324/101728817-05e01400-3af2-11eb-9f0e-b747f75fb11e.JPG)

**Comment by niuxjxlnx** [comment]
The values are (INT8*quantization step) as our design, which are float values. In following deployment stage, INT8 value will be extracted from the float values. So what's you see is as expected and has no problem.

**Comment by zxw602** [comment]
Thank you so much for your reply. That helps a lot 💯
