### ISSUE TITLE
How to compile quantization xmodel(in pytorch)

### ISSUE THREAD

**Issue by vasdvczxc** [Xilinx/Vitis-AI#219]
I am trying to compile an example model resnet18 xmodel. I ran the below command in the Vitis-ai-user guide. 

(test_env) root@System-Product-Name:/workspace# vai_c_xir -i ../Vitis-AI-Quantizer/vai_q_pytorch/example/quantize_result/ResNet_int.xmodel -a /opt/vitis_ai/compiler/arch/DPUCZDX8G/ZCU104/arch.json -o ../Vitis-AI-Quantizer/vai_q_pytorch/example/quantize_result/ -n ResNet

However, I got an error like below.

bash: vai_c_xir: command not found

If anyone knows about this issue, please give me some solution.

**Comment by qianglin-xlnx** [comment]
Hi @david132048 
It seems that you are using VAI1.2. Which docker container do you use?
If possible, I recommend you use VAI1.3.

**Comment by Hikaru-Furuta** [comment]
vai_c_xir -x ResNet_int.xmodel -a /opt/vitis_ai/compiler/arch/DPUCZDX8G/ZCU104/arch.json -o ./ -n ResNet_int.xmodel

**Comment by wanghong4compiler** [comment]
Hi @vasdvczxc ,
Does this issue still exist? Or, you've solved this issue?

**Comment by qianglin-xlnx** [comment]
HI @vasdvczxc 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
