### ISSUE TITLE
The loss of calibration iteration always equals to zero

### ISSUE THREAD

**Issue by zxw602** [Xilinx/Vitis-AI#223]
Hi guys :),

I am running vai_q_caffe to generate a quantized model by the line "vai_q_caffe quantize -model float.prototxt -weights float.caffemodel". And the command executed successfully without any bugs. However, I noticed that the loss of calibration iteration always equals to zero during the process. Here is an example below. Could anyone give me any clue about this? What should I do to pinpoint the cause of the problem? Many thanks!

![image](https://user-images.githubusercontent.com/55753324/102563986-7e0f9080-4115-11eb-9d57-e2638bfc59e0.png)

**Comment by Songxinlei** [comment]
I got the same problem .And I got other error when I deploy the prototxt and caffe. That is the same layer name in the prototxt file.Do you have the problem?

**Comment by niuxjxlnx** [comment]
"loss" will not be maintained in calibration stage and its value does not affect calibration.
Please check the quantized model accuracy directly and compile the quantized model.

**Comment by qianglin-xlnx** [comment]
Hi @zxw602 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
