### ISSUE TITLE
Error building docker gpu version 

### ISSUE THREAD

**Issue by vasdvczxc** [Xilinx/Vitis-AI#225]
I'm trying to build gpu_docker. However, I got some errors.. 

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Source/CMakeFiles/CMakeLib.dir/build.make:2961: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmInstallFilesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1206: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3052: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmLoadCommandCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3039: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmLoadCacheCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2636: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFindCommon.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3689: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmVariableWatchCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3494: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTargetCompileOptionsCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3533: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTargetLinkDirectoriesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2532: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmExecProgramCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3325: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmSetSourceFilesPropertiesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3078: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmMakeDirectoryCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:452: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmComputeLinkDepends.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:933: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFileAPICMakeFiles.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2792: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGetPropertyCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2935: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmInstallCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3442: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmSubdirCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2610: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFileCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2155: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmake.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:959: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFileInstaller.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1908: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmState.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3637: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmUnsetCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1869: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmSourceFile.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3130: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmOptionCommand.cxx.o' failed
g++: internal compiler error: Killed (program cc1plus)
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmInstallFilesCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Source/CMakeFiles/CMakeLib.dir/build.make:3676: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmVariableRequiresCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3182: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmProjectCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3793: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGlobalGhsMultiGenerator.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2623: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFindBase.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2467: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmCoreTryCompile.cxx.o' failed
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmLoadCommandCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmLoadCacheCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFindCommon.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmVariableWatchCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTargetCompileOptionsCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTargetLinkDirectoriesCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmExecProgramCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmSetSourceFilesPropertiesCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmMakeDirectoryCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmComputeLinkDepends.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFileAPICMakeFiles.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGetPropertyCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmInstallCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmSubdirCommand.cxx.o] Error 4
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFileCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmake.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFileInstaller.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmState.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmUnsetCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmSourceFile.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmOptionCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmVariableRequiresCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Source/CMakeFiles/CMakeLib.dir/build.make:2909: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmIncludeGuardCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2688: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFindPathCommand.cxx.o' failed
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmProjectCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGlobalGhsMultiGenerator.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFindBase.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmCoreTryCompile.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmIncludeGuardCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFindPathCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmStringReplaceHelper.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmLinkItem.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Source/CMakeFiles/CMakeLib.dir/build.make:3403: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmStringReplaceHelper.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1427: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmLinkItem.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3208: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmQTWrapUICommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1999: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTest.cxx.o' failed
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmQTWrapUICommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Source/CMakeFiles/CMakeLib.dir/build.make:868: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmExtraKateGenerator.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1531: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmMakefile.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3546: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTargetLinkLibrariesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1232: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGlobalCommonGenerator.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3585: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTargetSourcesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3013: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmLinkLibrariesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3559: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmTargetPrecompileHeadersCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2779: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGetFilenameComponentCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1115: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmGeneratorExpressionDAGChecker.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2480: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmCreateTestSourceList.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2376: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmBuildNameCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:465: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmComputeLinkInformation.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3143: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmOutputRequiredFilesCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:608: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmDependsFortran.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:3117: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmMessageCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1583: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmMakefileUtilityTargetGenerator.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1362: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmInstallSubdirectoryGenerator.cxx.o' failed
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTest.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmExtraKateGenerator.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmMakefile.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTargetLinkLibrariesCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGlobalCommonGenerator.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTargetSourcesCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmLinkLibrariesCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmTargetPrecompileHeadersCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGetFilenameComponentCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmGeneratorExpressionDAGChecker.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmCreateTestSourceList.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmBuildNameCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmComputeLinkInformation.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmOutputRequiredFilesCommand.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmDependsFortran.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmMessageCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmMakefileUtilityTargetGenerator.cxx.o] Error 4
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmInstallSubdirectoryGenerator.cxx.o] Error 4
Source/CMakeFiles/CMakeLib.dir/build.make:1375: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmInstallTargetGenerator.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:2662: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmFindLibraryCommand.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:1674: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmPolicies.cxx.o' failed
Source/CMakeFiles/CMakeLib.dir/build.make:855: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmExtraEclipseCDT4Generator.cxx.o' failed
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmInstallTargetGenerator.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmFindLibraryCommand.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmPolicies.cxx.o] Error 4
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmExtraEclipseCDT4Generator.cxx.o] Error 4
make[1]: *** [Source/CMakeFiles/CMakeLib.dir/all] Error 2
CMakeFiles/Makefile2:2184: recipe for target 'Source/CMakeFiles/CMakeLib.dir/all' failed
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/bash -c cd /tmp; wget --progress=dot:mega https://github.com/Kitware/CMake/releases/download/v3.16.1/cmake-3.16.1.tar.gz     && tar xvf cmake-3.16.1.tar.gz     && cd cmake-3.16.1     && ./configure     && make -j     && make install     && rm -fr /tmp/*     && ldconfig' returned a non-zero code: 2

How can I fix it?

**Comment by giuseppeCoccia** [comment]
Same error also for me. Is the `cmake 3.16.1` build broken?

**Comment by andyluo7** [comment]
you may run out of system memory. https://github.com/kaldi-asr/kaldi/issues/3781

**Comment by hanxue** [comment]
Hi @vasdvczxc @giuseppeCoccia ,

We have not encountered this issue before. And like @andyluo7 said, this could be a resource constraint / hardware issue. 

The latest version of Vitis AI 1.3.1 no longer builds cmake, and installs from a deb package. Can you try to clone this repository again and build the GPU docker image?

https://github.com/Xilinx/Vitis-AI/blob/master/setup/docker/docker/DockerfileGPU

**Comment by giuseppeCoccia** [comment]
Hi @hanxue , sorry for not updating this issue.
As you said, it was a memory problem and I was able to build it on another machine with more memory available.
Thanks for your help.

**Comment by hanxue** [comment]
Hi @giuseppeCoccia , glad to know the cause of the error, and was resolved.

**Comment by hanxue** [comment]
Hi @giuseppeCoccia 

I know that the issue has been resolved, I got another report of a similar issue about docker build failed without sufficient memory. Any chance you recall the amount of memory that is insufficient, and how much memory does the machine with successful build has?

**Comment by rpitonak** [comment]
Hello @hanxue,

In my case machine with `16Gb` RAM (`g4dn.xlarge` EC2 machine) is not sufficient and will run out of RAM at this step:
https://github.com/Xilinx/Vitis-AI/blob/d02dcb6041663dbc7ecbc0c6af9fafa087a789de/setup/docker/dockerfiles/vitis-ai-gpu.Dockerfile#L151-L161

As well as this step needs more than `20Gb`:
https://github.com/Xilinx/Vitis-AI/blob/d02dcb6041663dbc7ecbc0c6af9fafa087a789de/setup/docker/dockerfiles/vitis-ai-gpu.Dockerfile#L162-L174

Build on the machine with `32Gb` is working fine.
