### ISSUE TITLE
Is DPU-for-RNN supported for Alveo U50?

### ISSUE THREAD

**Issue by lllkiller-jlll** [Xilinx/Vitis-AI#234]
Hi.

I read DPU-for-RNN in (https://github.com/Xilinx/Vitis-AI/tree/master/dsa/DPU-for-RNN).
In this document, DPU for RNN is supported for U25 and U50LV. But document of RNN tool usage(https://github.com/Xilinx/Vitis-AI/tree/master/tools/RNN) said that RNN compiler generate the instructions for U25 and U50.
It makes me confused. Is DPU for RNN supported for Alveo U50? Or just supported for U50LV?

**Comment by qianglin-xlnx** [comment]
Hi @lllkiller-jlll 
Thank you for your feedback. It's a typo in https://github.com/Xilinx/Vitis-AI/blob/master/tools/RNN/README.md.
RNN supports U25 and U50LV.

**Comment by lllkiller-jlll** [comment]
Hi @qianglin-xlnx .

Could you tell me why DPU-RNN is supported only U50LV, not U50?
