### ISSUE TITLE
pycaffe caffe.set_device  will occupy gpu memory,and use cpu to inference.

### ISSUE THREAD

**Issue by York1996OutLook** [Xilinx/Vitis-AI#236]
caffe.set_mode_gpu()    # 用了这个才是真的在gpu上推理
        caffe.set_device(gpu)   # 设置用哪个gpu

**Comment by qianglin-xlnx** [comment]
Hi @York1996OutLook 
Could you describe the issue you encountered? Which model and which code? Thank you.

**Comment by York1996OutLook** [comment]
in caffe\cf_FPN-resnet18_Endov_240_320_13.75G_1.3\code\test\test.py
113    caffe.set_device(int(args.gpu))

above code line didnt work well. 
and the inference is execute on the cpu,so its very slow, you should add 'caffe.set_mode_gpu()' before ' caffe.set_device(int(args.gpu))'.

**Comment by York1996OutLook** [comment]
and in your examples,some code is has both of them, some not.
it was confused

**Comment by wanglixilinx** [comment]
hi, @York1996OutLook , thx for your comments.  Sorry for my  careless.  I will fix it later.

**Comment by wangxd-xlnx** [comment]
Fixed. Thanks all.
