### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'LeakyRelu' in binary running on cb56f6cc53b2. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#24]
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'LeakyRelu' in binary running on cb56f6cc53b2. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by foolmarks** [comment]
Make sure to import the contrib.decent_q module:

import tensorflow.contrib.decent_q

**Comment by zyxcambridge** [comment]
I  have import ，the problem is  about the tensorflow version ，xilinx  version is 1.12，my model for yolov3 is  1.13.1
