### ISSUE TITLE
pointpillars  52.48 ms  	zcu104  include nms ？

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#242]
__TIC__(PP_total)
  __TIC__(PP_pre)
  pre_->process_net0(points);
  __TOC__(PP_pre)

  __TIC__(anchor_and_dpu)  // about 19ms, so it's shorter than the dpu0+dpu1+pp_middle time.
  thread anchor_mask_t(&PointPillarsPost::get_anchors_mask , post_.get() , pre_->pre_dict_); 
   //  anchor_mask_t.join();  // move fronter for easy debug

  thread process_net1_cleanmem_t(&PointPillarsPre::process_net1_cleanmem , pre_.get() );

  __TIC__(PP_dpu0)
  m0_.configurable_dpu_task_->run(0);
  __TOC__(PP_dpu0)

  process_net1_cleanmem_t.join();
  __TIC__(PP_middle)
  pre_->process_net1();
  __TOC__(PP_middle)

  __TIC__(PP_dpu1)
  m1_.configurable_dpu_task_->run(0);
  __TOC__(PP_dpu1)

   anchor_mask_t.join();
  __TOC__(anchor_and_dpu)

  __TIC__(PP_post)
  auto results = post_->post_process( );
  __TOC__(PP_post)
  __TOC__(PP_total)

**Comment by andyluo7** [comment]
Yes, it includes post-processing.
