### ISSUE TITLE
WAA-TRD pre-built link is wrong

### ISSUE THREAD

**Issue by ping-Huang** [Xilinx/Vitis-AI#243]
In WAA-TRD detection preprocess Pre-built flow chapter 2.2, the link of "bin.tar.gz" is wrong.
Can someone provide the correct link to help me build the detection preprocess flow successfully?

**Comment by andyluo7** [comment]
Fixed with https://www.xilinx.com/bin/public/openDownload?filename=Vitis-AI.1.3-WAA-TRD.bin.tar.gz
