### ISSUE TITLE
"exec: \"/etc/login.sh\": permission denied": unknown

### ISSUE THREAD

**Issue by York1996OutLook** [Xilinx/Vitis-AI#244]
(base) sm@dl4028:/etc$ sudo docker start f03db547386b
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/etc/login.sh\": permission denied": unknown
Error: failed to start containers: f03db547386b

**Comment by hanxue** [comment]
Root is not required to run Docker containers - just make sure your user account (e.g. `sm`) is added to the `docker` group on the host. 

Could you try without `sudo`?

**Comment by qianglin-xlnx** [comment]
Hi @York1996OutLook 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
