### ISSUE TITLE
Support instructions for alveo u200 are missing.

### ISSUE THREAD

**Issue by daivikbhatia** [Xilinx/Vitis-AI#245]
Hi, there are no installation instructions for alveo u200 card, they are removed recently and the old links does not work. Can you please provide installation instructions for alveo u200 like they are present for u50, u280 and etc..

**Comment by qianglin-xlnx** [comment]
Hi @daivikbhatia 
You can find the installation instructions for the alveo u200 card in the following link 
https://github.com/Xilinx/Vitis-AI/tree/master/setup/alveo/u200_u250
