### ISSUE TITLE
Missing bellpeppe-994958.JPEG in the example folder

### ISSUE THREAD

**Issue by boba-milk-tea** [Xilinx/Vitis-AI#247]
https://github.com/Xilinx/Vitis-AI/blob/master/dsa/DPU-TRD/prj/Vivado/README.md

Running this command:
env LD_LIBRARY_PATH=samples/lib samples/bin/resnet50 img/bellpeppe-994958.JPEG on ZCU102 Board

Missing img/bellpeppe-994958.JPEG in the app folder.

Please add bellpeppe-994958.JPEG to:
Xilinx/Vitis-AI/dsa/DPU-TRD/app/img

Thanks.

**Comment by qianglin-xlnx** [comment]
Hi @boba-milk-tea 
In VAI1.3, we have removed the img folder. But you can still find the img folder in the following link:
https://github.com/Xilinx/Vitis-AI/tree/v1.2.1/DPU-TRD/app/img
Or you can test the program with your own images.
