### ISSUE TITLE
Running perpetual demo

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/Vitis-AI#252]
Hi,

Most of the things from https://github.com/Xilinx/ml-suite migrated to Vitis-AI, but https://github.com/Xilinx/ml-suite/tree/master/apps/perpetual_demo was not here

Can someone help me with this?

**Comment by Rampagee** [comment]
Hi, there,

This demo is removed from github. Some original ML suite related stuff can be found in:
https://github.com/Xilinx/Vitis-AI/tree/master/examples/DPUCADX8G
And we provide a new systematic web based Nepture framework for your reference:
https://github.com/Xilinx/Vitis-AI/tree/master/demo/neptune
