### ISSUE TITLE
tf yolov3-coco models can public ?

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#26]
tf_yolov3_voc_416_416_65.63G have exists;

can you share the tensorflow-yolov3-coco dataset models ?

**Comment by qianglin-xlnx** [comment]
@zyxcambridge 
Hi, so far as I know, tensorflow-yolov3-coco is not supported by the Vitis AI.

**Comment by qianglin-xlnx** [comment]
HI @zyxcambridge 
Since tensorflow-yolov3-coco is not supported by the Vitis AI, I am going to close this issue. If you have any suggestions or questions, you can re-open this issue. Thank you.
