### ISSUE TITLE
2020.2 DPU Image Invalid Bitstream on ZCU104

### ISSUE THREAD

**Issue by abdelrahmanhussein** [Xilinx/Vitis-AI#260]
Hi,

I downloaded the ZCU104 image (version 2020.2) from the VART page in this repo. On the development board, I tried to run the dexplorer -w command to see the DPU configurations, but I got this error message:
`root@xilinx-zcu104-2020_2:~# dexplorer -w`
`[DNNDK_XRT] Invalid bitstream: /usr/lib/dpu.xclbin` 

I created the image using the balenaEtcher tool.

**Comment by qianglin-xlnx** [comment]
Hi @abdelrahmanhussein 
"dexplorer" tool can't work on the official image which has installed VART. You refer to https://github.com/Xilinx/Vitis-AI/issues/186
