### ISSUE TITLE
Getting Segmentation Fault while running the pre-trained resnet50 model

### ISSUE THREAD

**Issue by PavanSai-39** [Xilinx/Vitis-AI#271]
Hi Team,

I am using the Alveo U200 card, I followed all the steps provided in the **Getting Started** Documentation and the steps provided for Vitis-ai from the **Vitis-ai-1.3** Documentation.

While running the Pre-trained model from the Vitis-AI Model Zoo, I am facing the Segmentation Issue.

1) When I ran the resnet50 (shared-object file) I could perform the Inferencing and everything went well.

2) But, when I run the resnet50_mt (multi-threaded python script) I am getting the Segmentation Fault.

 I am using the Vitis-ai-1.3 (docker image). Please let me know where I am doing wrong.

Thanks
![Xilinx_4](https://user-images.githubusercontent.com/45734995/105293138-0be00f00-5bdf-11eb-9e20-a961a9b4907b.png)
![Xilinx_5](https://user-images.githubusercontent.com/45734995/105293173-0da9d280-5bdf-11eb-9598-26feebdebf29.png)

**Comment by qianglin-xlnx** [comment]
@PavanSai-39 
Please refer to https://forums.xilinx.com/t5/AI-and-Vitis-AI/Getting-Segmentation-Fault-while-running-the-already-provided/td-p/1197279
