### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by zohourih** [Xilinx/Vitis-AI#273]
Looking at the content of this repo, it seems to me that the following two directories are exact replicas of each other:

https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Library/overview/samples
https://github.com/Xilinx/Vitis-AI/tree/master/demo/Vitis-AI-Library/samples

There is probably not much point having another instance [incomplete] of "Vitis-AI-Library" under "demo".

**Comment by qianglin-xlnx** [comment]
@zohourih 
Thank you for your feedback. We will remove all the samples under https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Library/overview/ in VAI1.3.1.
For Vitis-AI-Library samples, please refer to https://github.com/Xilinx/Vitis-AI/tree/master/demo/Vitis-AI-Library/samples.
