### ISSUE TITLE
AttributeError: module 'xir' has no attribute 'Graph'

### ISSUE THREAD

**Issue by Mwuschnig** [Xilinx/Vitis-AI#280]
When I try to run demo/VART/resnet50_mt_py.py 
I get the error 

File "resnet50.py", line 173, in main
    g = xir.Graph.deserialize(argv[2])
AttributeError: module 'xir' has no attribute 'Graph'

is there an error in the demo and how to use correctly deserialize?

**Comment by qianglin-xlnx** [comment]
@Mwuschnig 
Do you use the custom system image? If yes, please remove xir directory and runner.so under /usr/lib/python3.7/site-packages, then install the VART runtime 1.3.0  and try it again. Thank you.

**Comment by Mwuschnig** [comment]
It seems that did solve the problem.
