### ISSUE TITLE
PetaLinux build problem

### ISSUE THREAD

**Issue by nimaomidsajedi** [Xilinx/Vitis-AI#292]
Hello everyone,
I am working on my thesis and I am using DPU-TRD as a part of my master thesis. I am trying to run the provided DPU-TRD example (https://github.com/Xilinx/Vitis-AI/blob/master/dsa/DPU-TRD/prj/Vivado/README.md) and I am following all of the given commands for building the PetaLinux. **Unfortunately, the project stuck in the PetaLinux build stage. Can you please help me to find the problem? Is it normal to take this much time? Or am I missing something?**

It spends more than 10 hours building the PetaLinux and it is still not complete. I had to cancel the building due to the stuck in the running tasks. I appreciate a lot any and any comments on this issue.

Thank you very much!

![dpu-trd_petalinux](https://user-images.githubusercontent.com/56468728/107567823-7e447d80-6be6-11eb-9290-44a3ef1301bf.png)

**Comment by jimheaton** [comment]
Petalinux builds can take a long time depending on your machine. If you have not already downloaded the sstate-cache, and have a slow network, all the additional downloads that occur during the build process can also take a long  time.
