### ISSUE TITLE
refinedet training 

### ISSUE THREAD

**Issue by AhmadMKhan** [Xilinx/Vitis-AI#294]
I would like to train vgg16 bn network , as I observed it is not similar to conventional vgg16 network. Where can I get feature extractor prototxt or its network definition?

**Comment by lji72** [comment]
https://github.com/cvjena/cnn-models
https://github.com/davidgengenbach/vgg-caffe
https://github.com/BVLC/caffe/wiki/Model-Zoo#models-used-by-the-vgg-team-in-ilsvrc-2014

The above links may help you。
