### ISSUE TITLE
unsupported torch.einsum or torch.mm

### ISSUE THREAD

**Issue by shuiliuliushui** [Xilinx/Vitis-AI#296]
Hi,
When I try to quantize my own model where I used torch.mm to implement tensor multiplication, I get an error.
aten_op 'mm' parse failed(unsupported)

So I try to use einsum. It doesn't work

If I want to implement multiplication, what should I do?

**Comment by niuxjxlnx** [comment]
So far vai_q_pytorch does not support matrix mulplication OP.  But it will be supported soon in next update or released version.

**Comment by shuiliuliushui** [comment]
Thank you
