### ISSUE TITLE
add more functions   yolov3 and yolov3-tiny      inference time and map

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#3]

**Comment by zyxcambridge** [comment]
ai-modelzoo add yolov3-tiny

**Comment by sumitn-xilinx** [comment]
Vitis AI supports TinyYoloV3 for Alveo and YoloV3 for both Alveo and Mpsoc.

You can find multiple YoloV3 variants in the model zoo - https://github.com/Xilinx/Vitis-AI/tree/master/AI-Model-Zoo
And you can find instructions to run TinyYoloV3 for alveo here - https://github.com/Xilinx/Vitis-AI/tree/master/alveo/apps/yolo

**Comment by wilderfield** [comment]
@zyxcambridge, are you clear on this? If no, please clarify your issue.
