### ISSUE TITLE
Why is dpcma.ko not in this repository?

### ISSUE THREAD

**Issue by ttymrz** [Xilinx/Vitis-AI#303]
Hi.
I am using MPSoC DPU in Vivado flow with VART.
Since Vivado flow requires dpcma.ko, I am using dpcma.ko extracted from [xilinx-zcu102-trd.bsp](https://github.com/Xilinx/Vitis-AI/tree/master/dsa/DPU-TRD/prj/Vivado/dpu_petalinux_bsp). 
I think this method is incompatible with yocto and difficult to understand.
Are there any plans for dpcma.ko to be in this repository?

**Comment by qianglin-xlnx** [comment]
hi @ttymrz 
dpcma.ko is a universal driver. You can find the dpcma source in xilinx-zcu102-trd/project-spec/meta-user/recipes-modules/dpcma
And so far as I know, there is no plan to put dpcma in this repository.

**Comment by ttymrz** [comment]
Thank you
