### ISSUE TITLE
Vitis-AI support for Ultra96-V2 Development Board

### ISSUE THREAD

**Issue by daivikbhatia** [Xilinx/Vitis-AI#305]
Hi, I'm wondering if Vitis-AI can support Ultra96-V2 Development Board the way it supports Alveo cards and ZCU102. 
If yes then can someone please share an instruction link?

**Comment by andyluo7** [comment]
Vitis AI supports Ultra96-v2. Please check: https://www.hackster.io/AlbertaBeef/vitis-ai-1-3-flow-for-avnet-vitis-platforms-cd0c51
