### ISSUE TITLE
A simple question－What is Gops

### ISSUE THREAD

**Issue by Hikaru-Furuta** [Xilinx/Vitis-AI#307]
As is written in the descpription of Model Zoo, 
Model Name,  for example cf_resnet50_imagenet_224_224_7.7G, are expressed in the way like F_M_(D)_H_W_(P)_C_V.
And "C" specifies the computation of the model: how many "Gops" per image.
please teach me what deos "Gops" represent in detail

**Comment by andyluo7** [comment]
Giga operations per second.

**Comment by Hikaru-Furuta** [comment]
@andyluo7  Thanks for your help
