### ISSUE TITLE
vitis_quantize.VitisQuantizer.dump_model

### ISSUE THREAD

**Issue by Nunigan** [Xilinx/Vitis-AI#308]
In the vai_q_tensorflow version the dump function had the option dump_float, which was very handy.
The vai_q_tensorflow2 equivalent (vitis_quantize.VitisQuantizer.dump_model) has not such an option as it seems.
Is this true or am I missing something?

**Comment by qianglin-xlnx** [comment]
Hi @Nunigan 
In VAI1.3, there is no dump_float function for vai_q_tensorflow2. We will add this feature in VAI1.4. Thank you.
