### ISSUE TITLE
Black screen when running examples

### ISSUE THREAD

**Issue by Morett07** [Xilinx/Vitis-AI#31]
Hello,

I have a zcu 104 and I try to start examples as it is explain here : 

https://github.com/Xilinx/Vitis-AI/blob/master/mpsoc/runtime_docker.md

I flashed the sd card with this img : xilinx-zcu104-dpu-v2019.2.img.gz and Etcher

then I successfully installed xilinx_vai_board_package like it is described in Vitis user guide p26 : 

https://www.xilinx.com/support/documentation/sw_manuals/vitis_ai/1_0/ug1414-vitis-ai.pdf#unique_34

I managed to cross-compile applications in runtime docker, I tried the following examples : 

    - from dnndk : 
        - resnet50
        - adas_detection
        - segmentation

    - from dnndk : 
        - adas_detection
        - segmentation

For all of these examples I obtain a black screen and the the board freezes. 

I tried standalone connection (Display port) and ssh.

I haven't any signals on HDMI tx.

By ssh a black pop up appears and the board  freezes.

![example](https://user-images.githubusercontent.com/59084881/72341762-5d4fe700-36cb-11ea-8123-9bdc8e1b1995.png)

I tried to see kernel log but I see nothing suspicious.

![dmesg](https://user-images.githubusercontent.com/59084881/72342085-1ca49d80-36cc-11ea-9c4a-162cf272b90a.png)

Did miss something on the setup ?

Best regards,

Matthieu

**Comment by mullerrwd** [comment]
I can second the problems described by @Morett07. See issue #45.

**Comment by qianglin-xlnx** [comment]
Hi @Morett07 
I wonder if you have solved this issue. If not, I will submit this issue to the engineer in charge of it. If it has been resolved, please close this issue.
Note that if we do not receive any reply from you within 2 weeks, we will assume that this issue has been resolved and will close this issue. Thank you.

**Comment by qianglin-xlnx** [comment]
Note: You may need to run command irps5401 to trigger the power management patch for ZCU104 to avoid system hang or power off issue when running Vitis™ AI examples.

**Comment by qianglin-xlnx** [comment]
Hi @Morett07  The following issue is same as you and it's solved. You can find the solution here. Let me know if you still have any problem.
https://github.com/Xilinx/Vitis-AI/issues/45

**Comment by qianglin-xlnx** [comment]
Hi @Morett07 
Since I haven't received your feedback for a long time, I will close this issue.If you still have a question, you can reopen it. Thank you
