### ISSUE TITLE
unsupported operand type(s) for +:  'Nonetype' 

### ISSUE THREAD

**Issue by dingguodong-826** [Xilinx/Vitis-AI#316]
Hello, I made the following error when I requantified the Inceptionv3 of the PyTorch version, please help me check it!![image](https://user-images.githubusercontent.com/57715990/109968487-bba3b300-7d2d-11eb-8380-5118a78602a0.png)

**Comment by niuxjxlnx** [comment]
It seems that no model evaluation iteration before "Exporting quant config". So calibration is not done yet before exporting quantization result.

**Comment by niuxjxlnx** [comment]
This kind of problem has been fixed since Vitis-AI 1.4.
