### ISSUE TITLE
hard-coded magic number in vai_c_tensorflow for LeakyReLu?

### ISSUE THREAD

**Issue by busche** [Xilinx/Vitis-AI#317]
Hi all,

I was creating a CNN with keras on tensorflow 1.15 containing the following layers:

```
x2_conv1=tf.keras.layers.Conv2D(filters=n_hidden_1, kernel_size=(2,2), activation=None, name='conv2D_1',data_format='channels_last')(x2_reshape1)
x2_conv1=tf.keras.layers.LeakyReLU(alpha=0.3)(x2_conv1)
```

(note the alpha=0.3 parameter here ...) and got the following error in vai_c_tensorflow using the Vitis-AI-gpu:latest image:

  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 1925, in __generate_xmodel
    ), f"[ERROR] The negative slope for LeakyRelu must be 0.1015625: actual: {node.alpha}"
AssertionError: [ERROR] The negative slope for LeakyRelu must be 0.1015625: actual: 0.30000001192092896

having manually checked the contents of /opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py, I found  **0.1015625 to be hard-coded in the code**.

Changing my implementation to `x2_conv1=tf.keras.layers.LeakyReLU(**alpha=0.1015625**)(x2_conv1)` resulted in no complaints from vai_c_tensorflow.

However, I doupt that there is any reason for having 0.1015625 as a magic number here ... is there?

Best
  André

**Comment by qianglin-xlnx** [comment]
Hi @busche 
This is a constraint on the DPU. 0.1015625 is a value more fiendly for DPU, which will consumes less resource overhead and get higher performance.
