### ISSUE TITLE
4-bit DPU availability?

### ISSUE THREAD

**Issue by kerocc** [Xilinx/Vitis-AI#324]
Hello,

In the latest Vitis AI release notes, we could find the "4-bit DPU demo on ZCU102" was made available.

Hence I was wondering if a release date is already known, to use the 4-bit DPU further than a demo version?
Could we expect this for Vitis AI 1.4? Or should we wait another Vitis AI update?

Thanks for your answer.

**Comment by qianglin-xlnx** [comment]
Hi @kerocc 
So far as I know, there is no plan for 4-bit DPU in VAI 1.4.

**Comment by kerocc** [comment]
Thank you for this information.
Have a great day.
