### ISSUE TITLE
How to expand the rootfs size

### ISSUE THREAD

**Issue by pcjustin** [Xilinx/Vitis-AI#328]
I built the rootfs from another project `Vitis_Embedded_Platform_Source`, and add some packages into the petalinux. But the rootfs size is over 2GB. It built failed that generate the SD image on Vitis-AI.

Can anyone help me modify the rootfs size?

**Comment by tianfang-fafafa** [comment]
hi pcjustin, the size of rootfs in pre-built SD image is over 2GB, could you please share me the err info ?

**Comment by pcjustin** [comment]
Hi @tianfang-fafafa 

I found the root cause because it's Vitis 2020.1 bug. `mkfsImage.sh` setup the fixed rootfs size to 2048MB. I checked out the Vitis 2020.2 and the bug is fixed.
