### ISSUE TITLE
Error in README file 

### ISSUE THREAD

**Issue by DaniilNelubin** [Xilinx/Vitis-AI#330]
Change petalinux link in this file https://github.com/Xilinx/Vitis-AI/blob/1.3.1/tools/Vitis-AI-Runtime/VART/quick_start_for_edge.md
I think the link needs to be changed from (https://www.xilinx.com/bin/public/openDownload?filename=vitis_ai_2020.1-r1.3.1.tar.gz) to (https://www.xilinx.com/bin/public/openDownload?filename=vitis_ai_2020.2-r1.3.1.tar.gz)

**Comment by qianglin-xlnx** [comment]
Hi @DaniilNelubin 
Thank you for your feedback. Now the bug has been fixed.
