### ISSUE TITLE
() is missing in parse_log.py

### ISSUE THREAD

**Issue by satoru-i** [Xilinx/Vitis-AI#337]
When I use 'Vitis-AI/models/AI-Model-Zoo/caffe-xilinx/tools/extra/parse_log.py', an errors shows,

  File "/workspace/tutorials/caffe-xilinx/tools/extra/parse_log.py", line 166
    print 'Wrote %s' % output_filename

I think () is missing in the sentence.

print ('Wrote %s' % output_filename) is correct.

**Comment by lji72** [comment]
Wich version of python do you use?

**Comment by satoru-i** [comment]
Thank you for your reply.

I'm using caffe-xilinx in docker (vitis-ai-gpu:latest), so python version is 3.6.12.
I copied the caffe-xilinx directory under the tutorials directory and use it.

**Comment by lji72** [comment]
Ok, I see. Actually, The caffe-xilinx you copied can be only used with python 2 and there is a caffe-xilinx of python 3 in docker.

**Comment by satoru-i** [comment]
I thought AI-Model-Zoo/caffe-xilinx would work in docker. Thank you.
