### ISSUE TITLE
xmodel and elf

### ISSUE THREAD

**Issue by LinErDeng** [Xilinx/Vitis-AI#338]

**Comment by LinErDeng** [comment]
How to produce .elf file not .xmodel file

**Comment by lllkiller-jlll** [comment]
Hi @LinErDeng.

Do you want to use dpuv2 for edge devices?
If so, you can use "dnnc-dpuv2" instead of vai compiler.

**Comment by kevinkit** [comment]
@lllkiller-jlll can you give a little bit more information about this command? Is it in the docker image? How can I use it? Where is it documented? Thank you !

**Comment by wanghong4compiler** [comment]
Hi @kevinkit ，
From Vitis-AI v1.3 the *.elf file is not generated anymore by the tool. Instead of that *.xmodel will be used even for deploying models on edge devices.
