### ISSUE TITLE
Vitis-AI-Libraries for Alveo cards

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/Vitis-AI#35]
@wilderfield 
Clarification needed (can be applicable to Alveo cards)
this given  libraries are only applicable to zu102,zu104 boards?  https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library

**Comment by sumitn-xilinx** [comment]
Yes, deployment code in Vitis-AI-Library is for zynq boards. For alveo, you can use code from following:

https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/vitis_ai_alveo_samples
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/deployment_modes
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/apps/yolo

**Comment by mahinlma** [comment]
@sumitn-xilinx , Thank you.
