### ISSUE TITLE
tf_yolov3_voc

### ISSUE THREAD

**Issue by Bigemul** [Xilinx/Vitis-AI#352]
Hi everyone

I would like to use new Vitis API for YOLO. However, I can't seem to find the equivalent of `tf_yolov3_voc` (`from pynq_dpu.edge.dnndk.tf_yolov3_voc_py.tf_yolov3_voc import *`) to use get_class which is required to use YOLO. Could you tell me what is the equivalent in the new API?

Thank you

**Comment by qianglin-xlnx** [comment]
Hi @Bigemul 
I have asked my colleagues from other team and no one knew about this. It seems that you use DPU-PYNQ. Maybe you can post this issue in https://github.com/Xilinx/DPU-PYNQ/issues. I think there will be the right person to help you.
