### ISSUE TITLE
Vitis AI Profiler environment problem in platform setting

### ISSUE THREAD

**Issue by HSqure** [Xilinx/Vitis-AI#354]
Hi, there is a confusion about **Getting Started with Vitis AI Profiler** in `Vitis AI User Guide, UG1414 (v1.3) December 17, 2020, (page 123)`

### Document Screenshot

----------------------------------------------------------------------------------------------------------
![Screenshot from 2021-03-30 11-45-32](https://user-images.githubusercontent.com/25448018/112930902-bc254300-914d-11eb-935d-67ef19aaa84c.png)
----------------------------------------------------------------------------------------------------------

### Question description
According part **Installing the Vitis AI Profiler** in document, I finished: 

**Step a**:

![kernel2](https://user-images.githubusercontent.com/25448018/112939664-74f37e00-915e-11eb-9bc8-37a7ecb8e512.png)

And **Step b**:

![kernel1](https://user-images.githubusercontent.com/25448018/112939653-702eca00-915e-11eb-9ebe-8cab5587b384.png)

**BUT** at **Step c**, I can't find option `[*] packagegroup-petalinux-self-hosted` when I run `petalinux-config -c rootfs`:

![rootfs](https://user-images.githubusercontent.com/25448018/112939996-095de080-915f-11eb-8260-46a39c360a55.jpg)

I try to skip the **step c**, finally I got this running result with demo adas_detection_waa when I using `vaitrace` command:

![run](https://user-images.githubusercontent.com/25448018/112941663-9013bd00-9161-11eb-8327-5ca08d8cf64a.png)

Need help to solve this problem, thanks!

**Comment by tianfang-fafafa** [comment]
hi @HSqure ,  you can try "Petalinux Package Groups  --->  packagegroup-petalinux-self-hosted   --->  [*] packagegroup-petalinux-self-hosted " , please

**Comment by tianfang-fafafa** [comment]
![image](https://user-images.githubusercontent.com/80665242/113001839-c7a35900-91a3-11eb-9fb5-620a18b480c2.png)

**Comment by HSqure** [comment]
> hi @HSqure , you can try "Petalinux Package Groups ---> packagegroup-petalinux-self-hosted ---> [*] packagegroup-petalinux-self-hosted " , please

Thanks for your answer! I will try it.

**Comment by HSqure** [comment]
> hi @HSqure ,  you can try "Petalinux Package Groups  --->  packagegroup-petalinux-self-hosted   --->  [*] packagegroup-petalinux-self-hosted " , please

Hi @tianfang-fafafa  I tried to configure it as document and your suggestion, but same error shows as before:

sh: nm: command not found
ERROR:root:[nm --version] not exists, please check the document

**Comment by tianfang-fafafa** [comment]
hi，could you please share me more information？  which platform do you use?

**Comment by HSqure** [comment]
> hi，could you please share me more information？ which platform do you use?

Thanks for your reply!

The platform file I made is for `Zynq UltraScale+ MPSOC XCU15EG`. That application can fully functioning as long as I don't use `vaitrace`. 

Are there any clue about missing `GNU nm` package?

**Comment by tianfang-fafafa** [comment]
hi @HSqure , we have ever resolved this issue via email. can we close this issue ?

**Comment by HSqure** [comment]
> hi @HSqure , we have ever resolved this issue via email. can we close this issue ?

OK.
