### ISSUE TITLE
vai_c_tensorflow2 compilation error [UNILOG][FATAL][XCOM_DATA_OUTRANGE][Data value is out of range!]

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#357]
Hi

I finetuned one of our custom tf2 resnet50 model with vitis ai 1.3.2 , and I got a compilation error after finetuning as below
![Screenshot from 2021-03-31 18-06-59](https://user-images.githubusercontent.com/40138266/113147595-7eb2d980-9263-11eb-8511-60e2fe7df0fc.png)
How to fix it?

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
The error shows that the fixinfo is invalid. Could you check the following when you do the quantization.
1. Use the real images not fake images for calibration.
2. Use more than 100 images
BTW, have you successfully compiled the custom_tf2_resnet50 model without finetune?

**Comment by hill19850213** [comment]
Hi @qianglin-xlnx ,
1.What is the meaning of real images and fake image?

2.There is no compilation error before finetuning.

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
Since there is no compilation error without finetuning, it probably not be the issue of image.
We will add the verification of fixed information during finetuning. It will be in the next release.

**Comment by hill19850213** [comment]
Hi @qianglin-xlnx ,
It will be 1.3.3 or 1.4.0?

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
It has been fixed in VAI1.4.0 and later.
