### ISSUE TITLE
U280 or U280 ES1 card support

### ISSUE THREAD

**Issue by yanyh15** [Xilinx/Vitis-AI#36]
U280 is not listed in the supported card from this repo or from user guide (https://www.xilinx.com/support/documentation/sw_manuals/vitis_ai/1_0/ug1414-vitis-ai.pdf). How U280 is supported? It should, but not tested? If you can tell steps of adding U280 support, we can give a try and bring a PR for review. 

We have a ES version of U280, hope this is ok. 

Thank you

**Comment by qianglin-xlnx** [comment]
Hi @yanyh15 
Vai1.2 is live now and U280 card is supported by Vai1.2.  Please take a try. Thank you.
