### ISSUE TITLE
Error quantizing a CNN model

### ISSUE THREAD

**Issue by FrancoCapraro** [Xilinx/Vitis-AI#363]
Hello. im using the vitis-ai-lstm docker (GPU Docker + conda LSTM) and vai_tensorflow_imdb example as start point. My model is:

`    
model = Sequential()

model.add(Conv2D(32, (3,3), strides=(1,1), padding="valid", activation='relu', input_shape=(pixeles_int,pixeles_int,1)))

model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, 3, activation='relu'))

model.add(MaxPooling2D((2,2)))

model.add(Dropout(0.2))

model.add(Dense(64))  

model.add(Dropout(0.2))

model.add(Flatten())

model.add(Dense(nClasses,activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.load_weights(model_path)

single_batch_data = X_test[:1, ]

input_signature = tf.TensorSpec(single_batch_data.shape[1:], tf.float64)

quantizer = tf_quantizer(model, 
                             input_signature, 
                             quant_mode = args.quant_mode,
                             bitwidth = 16)

rebuilt_model = quantizer.quant_model
`

The error is:
NotImplementedError: Unable to parse <class 'tensorflow.python.keras.layers.convolutional.Conv2D'>

I check this [https://www.xilinx.com/html_docs/vitis_ai/1_3/tensorflow_2x.html#awh1604908613160](url) to see the supported operations and Conv2D is supported.
It can be the imports of my code ?

**Imports:**
import numpy as np
import os
import argparse
from os import environ
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence
from tensorflow.python.eager import context
from tensorflow.keras.layers import  Dropout
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.activations import relu
from tensorflow.keras.layers import Flatten

from tf_nndct.graph import builder
from tf_nndct.quantization.api import tf_quantizer

Another question, the TimeDistributed operation will be available in the future ?

**Comment by yuwang-xlnx** [comment]
Hi @FrancoCapraro,

vai_q_tensorflow2 and vitis-ai-lstm are different tools.
vitis-ai-lstm only supports a limited number of LSTM networks and operations which does not include Conv2D.

For your case, you should use vai_q_tensorflow2 to do quantization:
`conda activate vitis-ai-tensorflow2`
