### ISSUE TITLE
quantize  result problem

### ISSUE THREAD

**Issue by zhvn100** [Xilinx/Vitis-AI#365]
According to vitis-ai's tutorial, i  quantized exmple model - resnet18 , when i run following order,python resent18_quant.py   --quant_mode calib --subset 200 ,the output result is as follow:
![image](https://user-images.githubusercontent.com/56665570/113881276-dc5c9e00-97ee-11eb-9388-e770c0b30dfb.png)
loss is 0.597766 ,top-1 and top-5 are zero , is this situation normal?
please someone can answer me , thx

**Comment by qianglin-xlnx** [comment]
Hi @zhvn100 
It's abnormal. The running result is shown below.
![image](https://user-images.githubusercontent.com/58016351/114195694-4312c080-9983-11eb-9378-4c55f87bf193.png)

**Comment by zhvn100** [comment]
@qianglin-xlnx  hi，thank you for answering my question.  I  download the resnet18.pth  and prepare 200 pictures in imagenet.Then , according to tutorial , i run 'python resnet18_quant.py --quant_mode calib --subset_len 200 ' in vitis-ai-cpu docker . What should i do to figure out this mistake?

**Comment by clement-remillieux** [comment]
HI @zhvn100 @qianglin-xlnx ,

I have the same issue, did you found the solution ?

**Comment by niuxjxlnx** [comment]
Hi, @zhvn100:

There are some desription about loss and accuracy displayed in calibration stage. Please refer to
https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Quantizer/vai_q_pytorch/README.md#run-and-output-results
