### ISSUE TITLE
DPU

### ISSUE THREAD

**Issue by dingguodong-826** [Xilinx/Vitis-AI#369]
Hello, thank you and your team very much for your work, I would like to ask:

1. The provided routines are basically carried out on ZCU102 and ZCU104. If I want to implement them on my own development board (AU4EV), what work do I need to do

2. How do I build a DPU on my own development board
3. what can I do to build the image of my board like zcu102_base_2020.1?

Thank you very much!

**Comment by Eagle223** [comment]
Hello,
[https://forums.xilinx.com/t5/AI-and-Vitis-AI/A-GUI-flow-to-create-Vitis-AI-custom-platform/td-p/1102174](url) may help you.
