### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by shijinbose** [Xilinx/Vitis-AI#37]
Hi Team,
We are facing an issue while installing the Vitis-AI in our system. When we run ./docker_build.sh from Load&Run Docker Container section, The system through an error message every time. Please find the screenshot of the error message. 
![image](https://user-images.githubusercontent.com/7498925/73353716-f5e48a80-42b9-11ea-92ad-4fe6cdab6315.png)
 We have tried on both ubuntu18.04 and 16.04. 
Please guide me to resolve the issue.
Thanks & Regards,
Shijin Bose
shijinbose@gmail.com

**Comment by qianglin-xlnx** [comment]
Hi @shijinbose 
I wonder if you have solved this issue. If not, I will submit this issue to the engineer in charge of it. If it has been resolved, please close this issue.
Note that if we do not receive any reply from you within 2 weeks, we will assume that this issue has been resolved and will close this issue. Thank you.

**Comment by qianglin-xlnx** [comment]
Hi @shijinbose 
I'm going to close this. Please feel free to reopen if there are additional issues. Thank you.
