### ISSUE TITLE
Implementing VART ADAS example in Python

### ISSUE THREAD

**Issue by peterdors** [Xilinx/Vitis-AI#379]
Hello, I would like to try and use the Python API to reimplement the current ADAS example in C++ for VART. Would this be possible to implement with the current Python API? The only examples I find in VART using Python API involve image classification so I am unsure of how to complete this. 

Thanks!

**Comment by qianglin-xlnx** [comment]
Yes, you can implement VART ADAS example with Python API。

**Comment by peterdors** [comment]
Okay thank you for the confirmation. Are there any examples to come out with newer releases of Vitis AI that would have these implemented in Python?

**Comment by qianglin-xlnx** [comment]
Hi @peterdors 
You can refer to https://github.com/Xilinx/Vitis-AI/blob/master/demo/VART/resnet50_mt_py/resnet50.py
For the pre-process and post-process fucntion, users need to implement these functions themselves.
