### ISSUE TITLE
Why is there no example for zcu106？

### ISSUE THREAD

**Issue by DivineZeng** [Xilinx/Vitis-AI#38]

**Comment by andyluo7** [comment]
ZCU106 is not supported. Please use ZCU104 instead.

**Comment by kevinkit** [comment]
Is there any plan from XILINX to support the ZCU106?

**Comment by jimheaton** [comment]
There is no official plan to support Vitis-AI on the ZCU106.
However I have created  a port of the ZCU104 DPU TRD to ZCU106: https://github.com/jimheaton/Vitis-AI-DPU_TRD-for-ZCU106

This uses the Vitis Flow for the DPU, and requires Vitis 2019.2 and supports the Vitis-AI 1.1 release.

**Comment by kevinkit** [comment]
Thank you! 

Just out of curiosity: is there a specific reason why the ZCU106 will not be officially supported and is not planned to be supported?

Greetings
