### ISSUE TITLE
Vitis AI pytorch quantization problem for yolov5 model

### ISSUE THREAD

**Issue by JerrySciangula** [Xilinx/Vitis-AI#382]
Hi everyone,
I'm trying to accelerate a Pytorch YoloV5s model. Here you have the [link](https://github.com/ultralytics/yolov5) to the model.

When quantizing, the following error is arised:

![Schermata da 2021-04-17 13-21-49](https://user-images.githubusercontent.com/49304738/115288051-46f7cd00-a151-11eb-8e46-5571565d6c2c.png)

Could anyone help me trying to understand this issue and possibly explain me how to resolve it?

**Comment by niuxjxlnx** [comment]
Hi, @JerrySciangula :

In this conda env "vitis-ai-pytorch", version of pytorch is 1.4. Is this version for your YoloV5s model? 
From the error, it looks like YoloV5s does not work with pytorch 1.4.

**Comment by JerrySciangula** [comment]
Hi @niuxjxlnx, thank you for the reply.
No, unfortunately the YoloV5s model works with Pytorch version >= 1.7. Is there anyway to fix the issue?

**Comment by niuxjxlnx** [comment]
hi, @JerrySciangula 

Pytorch 1.7 will be supported in Vitis-AI 1.4.

**Comment by JerrySciangula** [comment]
Hi, @niuxjxlnx 

Thank you very much.

**Comment by kct890721** [comment]
Could you give me your E-mail,I have some question to ask you
