### ISSUE TITLE
Install C++ libraries on board (ZCU102)

### ISSUE THREAD

**Issue by Cliu2** [Xilinx/Vitis-AI#383]
Hi,

I wrote a customized application in C++, but with some dependency libraries. I want to compile the program on my ZCU102 and run it, but an error pops because the libraries have not been installed.

The libraries I need to install are: `tclap, jsoncpp, and Eigen3`.
With Ubuntu, I can do `sudo apt install XXX` to install these libraries, but I wonder how can I install them on the ZCU102?

Thank you very much.

**Comment by Eagle223** [comment]
Hello,
You can download rmp packages you need and use rpm to install it, or compile from source code.

**Comment by Cliu2** [comment]
Thank you for the help. I tried compiling from source code and works for me.
