### ISSUE TITLE
Plans to support latest U250 XDMA shell ?

### ISSUE THREAD

**Issue by boxerab** [Xilinx/Vitis-AI#394]
Currently, Vitis-AI only seems to work with 2018 shell.

**Comment by wilderfield** [comment]
@boxerab you are correct. The released accelerators were built against the 2018 shell. The install instructions should guide you to use that one. I have the latest shell on my development machine in the lab right now :-) . At the next release, we will move to 2020.2 shell and corresponding accelerator "xclbins", with XRT 2021.1 support.

**Comment by boxerab** [comment]
@wilderfield glad to hear! As I have other applications that I would like to use the latest shell with.
Looking forward to the next release.
