### ISSUE TITLE
Custom pointpillars model on ZCU104

### ISSUE THREAD

**Issue by reddittoob** [Xilinx/Vitis-AI#395]
Hi, I'm trying to run custom pointpillars model on ZCU 104.

However, I have a problem when I ran on ZCU board.

My result is like below.
![00000078_bev](https://user-images.githubusercontent.com/30588581/116050608-a35b6f00-a6b2-11eb-9d54-96e8a2ac7ced.jpg)

My problem is too many object is detected. 

I thought training, quantization, and compile were all done. I don't know why this problem. 

Additionally, I have a more question. When I run pointpillars model on ZCU104, It seems to apply calibration automatically. Also, I guess my problem was occurred because of calibration. Can I remove calibration?

Please let me know about this.

Thank you.

**Comment by lishixlnx** [comment]
please try to run the model with python code before compile it and check the result if it's ok.

**Comment by reddittoob** [comment]
There is not visualization and evaluation can't run because I trained model without images and calibration. So, my evaluation results have only zero.

**Comment by lishixlnx** [comment]
first please try to find out if your trained model is correct.
that can be test by python code.

**Comment by reddittoob** [comment]
What python code can be used test?

I have one more question. When I create ground truth, I resized a 3d bounding box height to make correct gt. 

Is this affect to train process?

**Comment by lishixlnx** [comment]
for first question:
since you have trained your model, 
does your trained model run correctly?
Only if you are sure the trained model runs well then you can continue with the quantize, compile, etc.
You need run the model each step to make sure it's correct.

**Comment by reddittoob** [comment]
Thank you for your reply.

I tried to test my trained model, however, I cannot run my model because I didn't have image and calibration.

**Comment by lishixlnx** [comment]
do you mean binary points file when you say "image"?
I can't understand that you can train your model but can't run your model.

**Comment by reddittoob** [comment]
In pointpillars code, I need binary points, images, and calibration. I mean just "image".

However, I didn't have image and calibration. I have just binary points and labeling data.

**Comment by reddittoob** [comment]
No, I mean just image used in code.

In testing code, image and calibration data are needed.
