### ISSUE TITLE
Clarification Regarding E2E Latency Numbers

### ISSUE THREAD

**Issue by zohourih** [Xilinx/Vitis-AI#398]
I wanted to clarify the way the E2E latency numbers are calculated and posted on this page:

https://github.com/Xilinx/Vitis-AI/tree/master/models/AI-Model-Zoo#performance-on-zcu104

Specifically, in the case of ZCU104, there are two DPU engines instantiated and the benchmarking is done with a batch size of 2 by default based on this message:

https://github.com/Xilinx/Vitis-AI/issues/275#issuecomment-766762849

However, the E2E latency seems to be calculated simply by inverting the FPS, which would be incorrect in this case since the batch size is not one and the latency will be the same whether batch size is 1 or 2 in this case since each frame is processed independently by either of the two DPU engines, and batch-1 performance will NOT scale across multiple DPU engines.

As an example, in the case of Resnet 50, the single-threaded FPS is reported as 75.1 which is with a batch size of 2. The E2E latency in this case would be 1000/(75.1/2)=26.63 ms, and not the 13.29 ms that is in the table.

I would appreciate it if someone clarifies this since these latency numbers can be outright incorrect and quite misleading the way they are currently being calculated.

**Comment by jimheaton** [comment]
The E2E latency number is using a single thread (one DPU, batch size =1), and in this case the frame rate is inverses of the latency. 

The multithreaded throughput value uses 2 DPUS, batch size =2.

**Comment by zohourih** [comment]
@jimheaton Based on the the reply from @qianglin-xlnx, that is not the case. Single-threaded is still batch size of 2 and number of threads is independent of batch size, unless the person doing the benchmarking modified the Xilinx benchmark code to enforce batch size of 1 as mentioned under that Github issue.

**Comment by jimheaton** [comment]
@zohourih. Issue #275 was a question about the Alveo U50 DPU. 
For Zynq and ZynqUltraScale+ DPUs: One thread = 1 DPU, batch size 1.

**Comment by qianglin-xlnx** [comment]
Hi @zohourih 
Just as @jimheaton  said, for DPU on edge, the batch size is 1. 
For ZCU104, we can integrate 2 DPU core, that batch size of each DPU core is 1. The number of DPU core is not the batch num.

**Comment by zohourih** [comment]
@jimheaton @qianglin-xlnx All right, I understand your point. I will close the issue, then.
