### ISSUE TITLE
lnk error 

### ISSUE THREAD

**Issue by zyxcambridge** [Xilinx/Vitis-AI#4]
https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library

https://www.xilinx.com/bin/public/openDownload?filename=vitis_ai_model_ZCU102_2019.2-r1.0.deb

![image](https://user-images.githubusercontent.com/1818981/70023882-b9efba80-15d3-11ea-8995-6821a877661f.png)

ZCU104 model deb is  ZCU102 not 104

**Comment by wilderfield** [comment]
Thanks for flagging
