### ISSUE TITLE
Where to get the arch.json for zynq 7010 when use Vitis AI Compiler ?

### ISSUE THREAD

**Issue by zuokanmingyuli** [Xilinx/Vitis-AI#40]
hi,
I have configured the docker-based model quantization tool (CPU version). However, I encountered the following problems when I use the Vitis AI Compiler tools.
The commond 'vai_c_tensorflow' need a parameter --arch arch.json. But for zynq 7010，where can I get the arch.json ?  Or is there any document for edit it ?

**Comment by qianglin-xlnx** [comment]
Hi @zuokanmingyuli 
I am afraid you have to create the zynq7010.json file by yourself. You can refer to ZCU102.json to create your zynq7010.json. If you use Vai1.1, you will find it under /opt/vitis_ai/compiler/arch/dpuv2/ZCU102 when you run the docker container. 

![image](https://user-images.githubusercontent.com/58016351/81796043-782e4d00-953f-11ea-8b29-156d3a1226d8.png)

**Comment by qianglin-xlnx** [comment]
HI @zuokanmingyuli 
Since I haven't received your reply for a long time, I'm going to close this issue. If you still have any questions, please fell free to reopen it. Thank you very much.
