### ISSUE TITLE
Compatibility with Ampere 30xx GPUs

### ISSUE THREAD

**Issue by david-rgd** [Xilinx/Vitis-AI#403]
Hi, I was trying to use Vitis-AI tools with an RTX 3070 GPU.

I upgraded some packages to comply with the [support matrix](https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html), but it seems it breaks the compatibility.

Has someone managed to get a GPU docker running with a 30xx GPU?

**Comment by qianglin-xlnx** [comment]
Hi @david-rgd 
please refer to https://github.com/Xilinx/Vitis-AI/issues/648
