### ISSUE TITLE
vai_c_caffe ERROR: NO FRONT END SPECIFIED

### ISSUE THREAD

**Issue by benedictusalvian** [Xilinx/Vitis-AI#408]
I am following Avnet's workshop on Vitis AI with Ultra96v2 by Watson Chow. In the tutorial, the model quantizes and compiles perfectly without issue. So far, I have quantized a ResNet50 model following the tutorial, but I got the following error when trying to compile and generate DPU instruction for the model:

![image](https://user-images.githubusercontent.com/55914367/117484410-9cc5d500-af99-11eb-9852-95cf3c25995d.png)
 
These are the contents of _2_caffe_compile_for_v2.sh_:

![image](https://user-images.githubusercontent.com/55914367/117484552-cc74dd00-af99-11eb-96d0-b82cd5f89edd.png)

And the contents of /workspace/Tool-Example/boards/${EDGE_TARGET}/${EDGE_TARGET}.json is

where EDGE_TARGET = ULTRA96V2

{
    "target"   : "dpuv2",
    "dcf"      : "/workspace/Tool-Example/boards/ULTRA96V2/dpu_ultra96v2.dcf",
    "cpu_arch" : "arm64"
}

I've read some solutions and tried renaming the target from "dpuv2" to "DPUCZDX8G" in the .json file, but it just crashes the script. I cannot open and edit the .dcf file as it is in binary.

![image](https://user-images.githubusercontent.com/55914367/117484810-2e354700-af9a-11eb-8a1d-dd4a3e76e1e4.png)

I am using Ubuntu 20.04.1 LTS running on top of Windows 10 WSL 2.

Any help is greatly appreciated.

**Comment by benedictusalvian** [comment]
I've managed to get the compilation to start by running an older version of vitis-ai-cpu (v1.1.56) that recognizes _dpuv2_. I ran `./docker_run.sh xilinx/vitis-ai-cpu:1.1.56` instead of `/docker_run.sh xilinx/vitis-ai-cpu:latest`.

However, now the compilation hangs indefinitely for no apparent reason.

![image](https://user-images.githubusercontent.com/55914367/117560940-e8c16880-b0c4-11eb-9284-ccb5b0bc6346.png)

**Comment by qianglin-xlnx** [comment]
Hi @benedictusalvian 
Could you please update to Vitis-AI 1.3? If yes, then you can refer to https://www.hackster.io/AlbertaBeef/vitis-ai-1-3-flow-for-avnet-vitis-platforms-cd0c51

**Comment by benedictusalvian** [comment]
> 
> 
> Hi @benedictusalvian
> Could you please update to Vitis-AI 1.3? If yes, then you can refer to https://www.hackster.io/AlbertaBeef/vitis-ai-1-3-flow-for-avnet-vitis-platforms-cd0c51

Thank you so much for the help!
