### ISSUE TITLE
Can I build and run val_q_torch with torch 1.7? Please help. 

### ISSUE THREAD

**Issue by htran170642** [Xilinx/Vitis-AI#411]
![image](https://user-images.githubusercontent.com/70887055/118113038-f736b980-b40f-11eb-81d0-09f849ef4ac5.png)

I used torch 1.7.1

**Comment by niuxjxlnx** [comment]
pytorch 1.7.1 is not supported in Vitis-AI 1.3, but will be supported in Vitis-AI 1.4.

**Comment by niuxjxlnx** [comment]
Pytorch 1.7 version has been supported in Vitis-AI 1.4, and pytorch 1.8, 1.9 version have been supported in Vitis-AI 2.0.
Further more, solution to change pytorch versions among the supported version range is released, please refer to the related part about script replace_pytorch.sh in user guide.
