### ISSUE TITLE
VART example   ./resnet50 model_dir_for_zcu102/resnet50.elf

### ISSUE THREAD

**Issue by ctlinglingliu** [Xilinx/Vitis-AI#412]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1127 02:58:52.117494  1117 main.cc:288] create running for subgraph: resnet50_0
Aborted

**Comment by qianglin-xlnx** [comment]
Hi @ctlinglingliu 
Could you please provide more information, such as image, dpu or runtime you used?

**Comment by qianglin-xlnx** [comment]
Hi @ctlinglingliu 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
