### ISSUE TITLE
alveo u280 error during the performance test for face detection

### ISSUE THREAD

**Issue by berankilic** [Xilinx/Vitis-AI#426]
Hi,

I am following [quick start for alveo](https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Library/README.md#quick-start-for-alveo) for running the example models and when I try to run the performance test for face detection, I get the following error:

```
I0528 07:56:52.808877   910 benchmark.hpp:176] writing report to <STDOUT>
I0528 07:57:04.140395   910 benchmark.hpp:203] waiting for 0/60 seconds, 8 threads running
I0528 07:57:14.140538   910 benchmark.hpp:203] waiting for 10/60 seconds, 8 threads running
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: CU timeout 1
Aborted (core dumped)
```
You can check  [outputs before the error](https://justpaste.it/4zkii) and [xbutil query](https://justpaste.it/2o7k4) during the process in case it is useful.
I would be glad if anyone helps.

**Comment by wanghy-xlnx** [comment]
Hi @berankilic ,
Please refer to [Issue-405](https://github.com/Xilinx/Vitis-AI/issues/405). The densebox model was found some issues on DPUCAHX8L, so please try another sample instead of face detection.
