### ISSUE TITLE
change demo source code did not work

### ISSUE THREAD

**Issue by weberxzq** [Xilinx/Vitis-AI#429]
I ran a demo of platedetect from Vitis-AI-Library and got the correct result. Now I want to understand how the whole process works and modified some source code such as platedetect.cpp, platedetect_imp.cpp by adding some std::cout flags and print some value. However, it seems that none of the changes works, nothing is printed by std::cout. Even if I commented some original lines of code, then compile and run the demo again, it still gives me the correct results. 

I am very confused, why changing the source code in /workspace/tools/Vitis-AI-Library/platedetect/src(or include) has no impact on the demo? Is it because I changed the wrong file? Or the cmake compilation is doing something that I did not know. Please let me know how to modify the source code so that I can better understand the whole process. 

Thanks,

**Comment by levent9402** [comment]
Hi,
It looks like your program is not compiled. Can you check the build date of the executable？
If the build time is not up to date, please refer to the documentation to check that it was compiled correctly.
Regards.
