### ISSUE TITLE
Different structure in Config file for vaitrace

### ISSUE THREAD

**Issue by Fabioni** [Xilinx/Vitis-AI#436]
Hey,

in <https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Profiler#configuration> the following structure for the config file for vaitrace is shown:

```python
{
  "options": {
    "runmode": "normal",
    "cmd": "/home/root/Vitis_AI/examples/VART/samples/resnet50/resnet50 /usr/share/vitis_ai_library/models/resnet50/resnet50.xmodel",
    "timeout": 10
  },
  "trace": {
    "enable_trace_list": ["vitis-ai-library", "opencv", "vart", "custom"]
  },
  "trace_custom": []
}
```

in <https://www.xilinx.com/html_docs/vitis_ai/1_3/profiling.html#fwc1591338728789__section_k2s_rq1_vmb> the following one is shown:

```python
{
  "options”: {
      "runmode": "normal",
      "cmd": "/usr/share/vitis-ai-library/sample/classification/test_jpeg_classification resnet50 sample.jpg",
      "output": "./trace_resnet50.xat",
      "timeout": 3
  },
  "trace": {
      "enable_trace_list": ["vitis-ai-library", "vart", "custom"],
      "trace_custom": []
  }
}
```
 only the first one with trace_custom *outside* of trace is working for me.
I tried with `Vitis-AI/demo/VART/resnet50` and `"trace_custom": ["TopK", "CPUCalcSoftmax"]`

**Comment by li900309** [comment]
thanks @Fabioni , This is an error in the Vitis-AI user document, we have corrected it. The instructions in the github page are correct
