### ISSUE TITLE
xdputil shows -  No module named 'tools_extra_ops'

### ISSUE THREAD

**Issue by Maharshi-Aupera** [Xilinx/Vitis-AI#439]
Hi Xilinx Community,

I have been trying to debug the xmodel and use tools provided by Xilinx here: https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Library/usefultools

However, when I try to use `xdputil` is first shows the numpy package missing related error then it shows this `No module named tools_extra_ops`. 

Is a script with this name `tools_extra_ops.py` missing from the repository or I am running this on a wrong device and with a wrong conda environment? Please suggest how to solve this.

Thanks.

**Comment by Maharshi-Aupera** [comment]
I think I found them it is in the `src/` directory, do I need to build it?

**Comment by qianglin-xlnx** [comment]
Hi @Maharshi-Aupera 
An easy way to use xdpuil is to install the VART1.3.2. After the installation, you can directly run xdputil. 
Note that, xputil is not supported in Vivado flow. It will be fixed in VAI1.4.

**Comment by Maharshi-Aupera** [comment]
Thanks @qianglin-xlnx, I will give it a try and close the issue asap.
