### ISSUE TITLE
Custom plugin in PyTorch flow

### ISSUE THREAD

**Issue by SiyuanChen-Nanjing** [Xilinx/Vitis-AI#442]
Hi, I'm trying to accelerate [PWCNet ](https://github.com/sniklaus/pytorch-pwc) for optical flow prediction with DPU on ZCU104, using the pytorch flow. However, the network has two custom layers (warping and correlation) that are not supported by the vai-q-torch quantizer or DPU. 

I want to avoid running them on CPU because of the overhead of going back and forth, so I'm considering implementing custom HLS plugins for them.  The Vitis AI user guide has a [section](https://www.xilinx.com/html_docs/vitis_ai/1_3/compiling_model.html#buj1605502791825) that talks about implementing a plugin with a sample that I found [here](https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Runtime/VART/plugin-samples/samples/plugin-smfc/plugin-smfc.cpp), but I can't find anything about implementing a plugin for the torch quantizer. 

Is there a way to extend the torch quantizer so that the custom layers can be converted to something that later can be recognized by the VAI compiler plugin? I would also appreciate the help if you could point me to any tutorials on implementing an HLS plugin for DPU.

Thanks in advance for your time!

**Comment by niuxjxlnx** [comment]
vai-q-torch quantizer does support customized layers deployment on DPU.
