### ISSUE TITLE
Issue with Vitis AI Profiler (No such file or directory: '/sys/kernel/debug/tracing/trace_clock')

### ISSUE THREAD

**Issue by Luc-Meunier** [Xilinx/Vitis-AI#448]
Hi,

I am trying to use the Vitis AI Profiler following the tutorial https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Profiler.
I am using an Alveo U280, and Vitis AI Docker container for CPU.

The following command causes the issue "**FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/tracing/trace_clock'**".
`sudo vaitrace ./resnet50 /usr/share/vitis_ai_library/models/resnet50/resnet50.xmodel
`

![image](https://user-images.githubusercontent.com/83921379/122020899-7596ca80-cdc5-11eb-8bad-183513387f32.png)

I am new to Linux and Vitis and I don't know how to solve this issue...

Thank you for your help.
Best regards,

Luc

**Comment by qianglin-xlnx** [comment]
Hi @Luc-Meunier 
Could you please check the following?
![image](https://user-images.githubusercontent.com/58016351/122069369-b6bfc680-ce27-11eb-85c5-c026927428c6.png)

**Comment by Luc-Meunier** [comment]
Hello,
Thanks for helping me.

I added the line `-v /sys/kernel/debug:/sys/kernel/debug --privileged=true \` in the _docker_run.sh_ file.

![err1_docker_run](https://user-images.githubusercontent.com/83921379/122076037-d12f7b00-cdfa-11eb-9a53-85dbbbba834e.PNG)

However, I still get the error message **ERROR:root:This tool need run as 'root'**.
And I get an **std::runtime error** :

![err2_root](https://user-images.githubusercontent.com/83921379/122076049-d4c30200-cdfa-11eb-8088-e0801ad2c893.PNG)

**Comment by karan18205** [comment]
Facing same issue. It says Xilinx_xrt not set. Anyone any leads?

**Comment by wilderfield** [comment]
source /opt/xilinx/xrt/setup.sh

^ this script is responsible for setting that environment variable. Ideally it would have been set for you.

**Comment by karan18205** [comment]
Yes, solved it thanks.

**Comment by Luc-Meunier** [comment]
Thank you, but unfortunately I still can't run _vaitrace_ (still XILINX_XRT not set despite sourcing the script).
Could you tell me what am I missing ?

![err](https://user-images.githubusercontent.com/83921379/122555483-a3387980-d03a-11eb-8138-bd26fb140e2c.PNG)

**Comment by SuZhan0322** [comment]
The latest VAI release has fixed this issue, please reopen this issue if there any other problems. thanks！

**Comment by hocken-li** [comment]
> The latest VAI release has fixed this issue, please reopen this issue if there any other problems. thanks！

My VAI is 3.0. Aslo source /opt/xilinx/xrt/setup.sh
But still have the problem, how to solve it?

**Comment by SuZhan0322** [comment]
Hi @hocken-li , Can you share your steps and error message. Thanks!
