### ISSUE TITLE
The link of install Docker is invalid

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#456]
Hi,
The link of install Docker is invalid, coould you please to fix it?
![image](https://user-images.githubusercontent.com/40138266/123385587-49026000-d5c8-11eb-8f59-9c27ba09c4ba.png)

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
Thank you for your feedback. This issue has been fixed in VAI2.0.
