### ISSUE TITLE
Tensorflow2 quantization / compilation issue: input layer got quantized un-wantedly

### ISSUE THREAD

**Issue by luke-avionics** [Xilinx/Vitis-AI#472]
I went through the quantization flow and got to compilation. However it complains some param_info was None (as shown below), I printed out more and found that Input layer is also quantized and its info is None
![image](https://user-images.githubusercontent.com/16768961/126206359-dd3383b9-53f4-4eb2-91c4-3a0ff6400fe1.png)
I am not sure quantizing the input layer is normal or not as it has no parameters. The following is part of my model definition 
![image](https://user-images.githubusercontent.com/16768961/126206565-e920c926-c857-4f2b-a7a5-e9642c61a5ed.png)

**Comment by luke-avionics** [comment]
something wrong with tqdm?

**Comment by zhenzhen-Xilinx** [comment]
This problem can be solved, please use the latest version.
