### ISSUE TITLE
【WAA-TRD】pre-build for U200/U250

### ISSUE THREAD

**Issue by simplelins** [Xilinx/Vitis-AI#473]
Hi, I need integration of pre/post processing accelerator with DPU fot the u200/u250 platform, where can I get the pre-project like U50 (https://github.com/Xilinx/Vitis-AI/tree/master/dsa/WAA-TRD/proj/pre-built/classification-pre_DPUv3e)?
or how to do some update for u200/u250?

**Comment by qianglin-xlnx** [comment]
Same issue as https://github.com/Xilinx/Vitis-AI/issues/474
