### ISSUE TITLE
still can't find packagegroup-petalinux-vitisai in vai 1.4

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#481]
Hi, 
I have referred the below step and do petalinux-upgrade, but I still can't find packagegroup-petalinux-vitisai

![image](https://user-images.githubusercontent.com/40138266/126852872-239078c3-b453-4517-8654-7b1f9276d6b6.png)

Can you share more detail?

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
So far as I know, the Petalinux tool updates containing VAI1.4 content is not released. It will be released 1 month later. Before that, you can install VART by the released packages under https://gitenterprise.xilinx.com/Vitis/vitis-ai-staging/tree/master/setup/mpsoc/VART/2021.1

**Comment by hill19850213** [comment]
Hi @qianglin-xlnx ,
This link https://gitenterprise.xilinx.com/Vitis/vitis-ai-staging/tree/master/setup/mpsoc/VART/2021.1 is not available for me. Can you provide other link?

**Comment by qianglin-xlnx** [comment]
@hill19850213 
Sorry about the mistake. It's https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc/VART/2021.1

**Comment by hill19850213** [comment]
@qianglin-xlnx 
I try to use dnf to install packagegroup-petalinux-vitisai , but there is an error as below:
![image](https://user-images.githubusercontent.com/40138266/127610002-00fbf04e-d575-4216-a577-1ffbf6b45a65.png)
What is the problem?

Thanks
Sitting

**Comment by qberthet** [comment]
@hill19850213 : I think you have to copy the rpm package to the target system and then install them locally with dnf (not tried yet).

@qianglin-xlnx : It seems that an update_1 is out ([http://petalinux.xilinx.com/sswreleases/rel-v2021/sdkupdate/2021.1_update1/aarch64](http://petalinux.xilinx.com/sswreleases/rel-v2021/sdkupdate/2021.1_update1/aarch64)), but it appear to be broken: I have updated my Petalinux installation with it but then when I try to configure a newly-created project, I get 

```
Extracting SDK......xz: (stdin): Compressed data is corrupt
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Failed to Extract Yocto SDK.
```
which seems to indicate that the binary blob in aarch64 is corrupt.
Do you have a clue? Or should I create a new issue?
Thanks in advance.

**Comment by nhphuong91** [comment]
> @hill19850213 : I think you have to copy the rpm package to the target system and then install them locally with dnf (not tried yet).
> 
> @qianglin-xlnx : It seems that an update_1 is out (http://petalinux.xilinx.com/sswreleases/rel-v2021/sdkupdate/2021.1_update1/aarch64), but it appear to be broken: I have updated my Petalinux installation with it but then when I try to configure a newly-created project, I get
> 
> ```
> Extracting SDK......xz: (stdin): Compressed data is corrupt
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> ERROR: Failed to Extract Yocto SDK.
> ```
> 
> which seems to indicate that the binary blob in aarch64 is corrupt. Do you have a clue? Or should I create a new issue? Thanks in advance.

I'm having the same problem. Have you managed to fix it? @qberthet

**Comment by qianglin-xlnx** [comment]
Hi @nhphuong91  and @hill19850213 
Could you try the following?
![image](https://user-images.githubusercontent.com/58016351/143536037-f44d7098-be4d-4417-9fa6-da89bf5562d3.png)

**Comment by nhphuong91** [comment]
> Hi @nhphuong91 and @hill19850213 Could you try the following? ![image](https://user-images.githubusercontent.com/58016351/143536037-f44d7098-be4d-4417-9fa6-da89bf5562d3.png)

@qianglin-xlnx it works! Thanks!

**Comment by hill19850213** [comment]
@qianglin-xlnx it works. Thanks!
