### ISSUE TITLE
Is VART available for Alveo U250?

### ISSUE THREAD

**Issue by virusfunk** [Xilinx/Vitis-AI#482]
I used Alveo U250 from 2 year ago, but it seems there is no profiling API(like VART) for Alveo U250. Do you have a plan to support Alveo U250 in Vitis-AI 1.5? I asked it before a year ago, and you guys said "The IP for these 2 Alveo board would be released soon.".. In my view, the U250 looks like an abandoned platform.

**Comment by andyluo7** [comment]
@virusfunk , U200/U250 is fully supported in VART except for profiling and there are multiple full tutorials under examples/DPUCADF8H on using U200/U250. Please check it out. 
There is also a DPU TRD on U200 https://github.com/Xilinx/Vitis-AI/tree/master/dsa/WAA-TRD/proj/build/classification-pre_DPUv3int8. 
We also plan to add profiling for U200/U250 in near future.
