### ISSUE TITLE
Information about available options for custom DPU for Ultrascale 96 v2

### ISSUE THREAD

**Issue by daivikbhatia** [Xilinx/Vitis-AI#483]
Hi,
I'm trying to form custom DPU for Ultrascale96 v2 using Vitis. I tried to form it with DPU IP B2304 but I ran into an error saying, this design requires 421 DSPs cells but only 360 are available. 

Can you please tell me what configuration options are available for Ultrasclae 96v2 so that I can design DPU accordingly or can you please share where such information is provided for Ultrascale 96v2?

**Comment by foolmarks** [comment]
You need to cross-reference the resources required for your DPU configuration (see PG338 https://www.xilinx.com/support/documentation/ip_documentation/dpu/v3_3/pg338-dpu.pdf) with the available resources in the Zynq ZU3 device on the Ultra96v2.
