### ISSUE TITLE
使用Vitis AI量化训练Pytorch模型出现问题

### ISSUE THREAD

**Issue by zhangchenchen-novauto** [Xilinx/Vitis-AI#487]
看报错！但所我已经改了里面含有Add节点的地方
![testt](https://user-images.githubusercontent.com/84957934/127324626-45ab7f69-d68c-45f3-866d-04173a5ae776.png)

第335行，
```
# x = x + out[module.layers[0]]
 x = self.skip_add[i](x, out[module.layers[0]])
```
[models.txt](https://github.com/Xilinx/Vitis-AI/files/6893139/models.txt)

执行到这句代码就出现了上面的错误
```
quantizer = torch_quantizer(quant_mode='calib',
                              module=model,
                              input_args=input,
                              bitwidth=8,
                              qat_proc=True)
```

**Comment by yuwang-xlnx** [comment]
Hi @zhangchenchen-novauto,

Which Vitis-AI verison did you use ? Can you share the quant_info.json and python script in .qat ?

**Comment by zhangchenchen-novauto** [comment]
**Vitis-AI1.4** 
这是.qat/ 文件夹下面的文件

[quant_info.json.txt](https://github.com/Xilinx/Vitis-AI/files/6897804/quant_info.json.txt)
[Darknet.py.txt](https://github.com/Xilinx/Vitis-AI/files/6897807/Darknet.py.txt)

**Comment by yuwang-xlnx** [comment]
> Hi @yuwang-xlnx
> **Vitis-AI1.4**
> 这是.qat/ 文件夹下面的文件
> 
> [quant_info.json.txt](https://github.com/Xilinx/Vitis-AI/files/6897804/quant_info.json.txt)
> [Darknet.py.txt](https://github.com/Xilinx/Vitis-AI/files/6897807/Darknet.py.txt)

It seems that the replacement of torch.add/+ is not correct. 
A simple example:

```
from pytorch_nndct.nn.modules import functional

def __init__(self):
  self.add = functional.Add()
  ...

def forward(self, x):
  ...
  x = self.add(x, y)
```

**Comment by zhangchenchen-novauto** [comment]
Hi @yuwang-xlnx 
我感觉我的替换好像没有问题，在问题提问的 **model.txt**   https://github.com/Xilinx/Vitis-AI/files/6893139/models.txt 有我的网络描述
![Screenshot from 2021-07-29 14-48-13](https://user-images.githubusercontent.com/84957934/127445140-6c64b024-e1c7-4c1b-b062-9e56ae25bb70.png)
![Screenshot from 2021-07-29 14-48-32](https://user-images.githubusercontent.com/84957934/127445142-76489c26-7163-4feb-8c8b-4fc76e76cade.png)

**Comment by yuwang-xlnx** [comment]
Hi @zhangchenchen-novauto ,

There should be xxx.py and quant_info.json in the .qat directory, can you share these two files ?
