### ISSUE TITLE
Custom model has four outputs, VAI Compiler generates single output.

### ISSUE THREAD

**Issue by vtorres621** [Xilinx/Vitis-AI#488]
Hello, 
I am running a custom model through the Vitis AI flow.  I need to postprocess the output of 3 intermediate layers inside the model as well as the final output .  My pytorch model reflects this.  The model's forward function generated by VAI Quantizer also returns 4  required outputs:
`return self.output_module_18,self.output_module_34,self.output_module_50,self.output_module_66`

But when I compile the subgraphs, the .xmodel has only the output of the final layer.  

![graph](https://user-images.githubusercontent.com/31051189/127407189-6618b4c6-f189-4676-9fc4-a120af5b955d.png)

I have seen other models from the model zoo (like yolov3, tinyyolo, etc) "download" the output of an intermediate layer:
![tiny_yolov3](https://user-images.githubusercontent.com/31051189/127407269-971c21b8-b699-449d-8aab-349a792ad5ad.png)

 How can I do this with my custom model?

 
Let me know if you need more information.

EDIT:

I found this on the documentation (UG1414: VAI_C Usage):
![image](https://user-images.githubusercontent.com/31051189/127410994-0f44997f-7aee-494b-8df1-28d1e77d13ae.png)

But I am not sure where to fin the "op_name0".

**Comment by hoadv-qh** [comment]
Hi @vtorres621,

>But I am not sure where to fin the "op_name0".

In your graph, you can see such "Tensor: CNN__CNN_Sequential_xxx".
I think you can try to pass name of tensor, "CNN__CNN_Sequential_xxx", to the option?

**Comment by vtorres621** [comment]
Hello @hoadv-qh,

Thanks for your help, I was trying this with Vitis AI 1.3 but it didn't worked.  
I updated to 1.4 and I was able to get multiple outputs using this --options command on VAI_C/

Thanks!

**Comment by hoadv-qh** [comment]
Hi @vtorres621,

I'm glad that can help.
Hope you can do well for next steps with DPU.

**Comment by hoadv-qh** [comment]
Hi @vtorres621,

I'm glad that can help.
Hope you can do well for next steps with DPU.
