### ISSUE TITLE
Error when compiling quantized LSTM with vai_c_xir

### ISSUE THREAD

**Issue by chtapodi** [Xilinx/Vitis-AI#507]
I am attempting to compile a quantized LSTM model for the ZCU102, and am getting a fatal error.
```

`(vitis-ai-pytorch) Vitis-AI /workspace/tools/RNN/rnn_compiler > vai_c_xir -x quantize_result/xmodel/Lstm_StandardLstmCell_layer_0_forward_int.xmodel -a /opt/vitis_ai/compiler/arch/DPUCZDX8G/ZCU102/arch.json -n LSTM
**************************************************
* VITIS_AI Compilation - Xilinx Inc.
**************************************************
[UNILOG][INFO] Target architecture: DPUCZDX8G_ISA0_B4096_MAX_BG2       
[UNILOG][INFO] Compile mode: dpu
[UNILOG][INFO] Debug mode: function
[UNILOG][INFO] Target architecture: DPUCZDX8G_ISA0_B4096_MAX_BG2       
[UNILOG][INFO] Graph name: Lstm_StandardLstmCell_layer_0_forward, with 
op num: 80[UNILOG][INFO] Begin to compile...
[UNILOG][WARNING] xir::Op{name = Lstm_StandardLstmCell_layer_0_forward__ft_input_2_new, type = depthwise-fix} has been assigned to CPU: [DPUCZDX8G_ISA0_B4096_MAX_BG2 does not have alu-engine].
[UNILOG][WARNING] xir::Op{name = Lstm_StandardLstmCell_layer_0_forward__it_cct_new, type = depthwise-fix} has been assigned to CPU: [DPUCZDX8G_ISA0_B4096_MAX_BG2 does not have alu-engine].
[UNILOG][WARNING] xir::Op{name = Lstm_StandardLstmCell_layer_0_forward__h_next_new, type = depthwise-fix} has been assigned to CPU: [DPUCZDX8G_ISA0_B4096_MAX_BG2 does not have alu-engine].
[UNILOG][FATAL][XCOM_ITEM_UNDEFINED][The requested item is not finded or defined!]
*** Check failure stack trace: ***
Aborted`

```
I cannot figure out how to check further details about the error to figure out exactly what is going wrong.

Thank you

**Comment by BraunPhilipp** [comment]
Are the layers supported by Xilinx as a default? If not I would work my way back from a reference LSTM example.

**Comment by dongxuedx** [comment]
Looks like you're using the CNN compiler, if you want to compile  LSTM model, The RNN compiler is needed.

**Comment by hanxue** [comment]
Hi @chtapodi ,

The RNN workflows are at https://github.com/Xilinx/Vitis-AI/tree/v2.0/demo/DPU-for-RNN . For RNN workflows, you will need to build the RNN docker https://github.com/Xilinx/Vitis-AI/tree/v2.0/demo/DPU-for-RNN

**Comment by zhenzhen-AMD** [comment]
Hi @chtapodi ,
Has the problem been resolved? Do you have any other questions? If there are no more issues, we will close this issue. There is a problem later, please reopen the issue. Thank you.

**Comment by dongxuedx** [comment]
[AMD Official Use Only - General]

HI. You can close it. Thank you.


From: zhenzhen-AMD-Xilinx ***@***.***>
Reply-To: Xilinx/Vitis-AI ***@***.***>
Date: Friday, July 22, 2022 at 10:38
To: Xilinx/Vitis-AI ***@***.***>
Cc: dzhy Xilinx ***@***.***>, Comment ***@***.***>
Subject: Re: [Xilinx/Vitis-AI] Error when compiling quantized LSTM with vai_c_xir (#507)
Resent-From: dzhy Xilinx ***@***.***>

CAUTION: This message has originated from an External Source. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.


Hi @chtapodi<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchtapodi&data=05%7C01%7Cdong.han%40amd.com%7Cc97699856457481f960908da6b8b3f9c%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637940543060359062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0w7dij1Vm7wVjqVWmlKGU4NPCh1ecMvNwpC63id302Y%3D&reserved=0> ,
Has the problem been resolved? Do you have any other questions? If there are no more issues, we will close this issue. There is a problem later, please reopen the issue. Thank you.
