### ISSUE TITLE
aten_op 'view' parse failed(the layout of activation of reshape is ambiguous)

### ISSUE THREAD

**Issue by puffdrum** [Xilinx/Vitis-AI#508]
Hi, everyone. I use `models.py` from [this project](https://github.com/tanluren/yolov3-channel-and-layer-pruning) to train and quantize my yolov4-tiny model and successfully running the evaluation program at the latest Vitis-AI GPU docker with `python quant.py --quant_mode float`.
However, when I run `python quant.py --quant_mode calib`, I've met errors: `aten_op 'meshgrid' parse failed(unsupported)` and `aten_op 'clone' parse failed (unsupported)`. Then I replace these operations and met an error that I cannot solve:
```
aten_op 'view' parse failed(the layout of activation of reshape is ambiguous)
```
![1](https://user-images.githubusercontent.com/70867945/129140953-0aeb9fb8-18fc-4a48-925b-9c06bf23f238.PNG)

There are several 'view' ops in `models.py` . I don't understand this error. Looking for some help, thanks!

**Comment by puffdrum** [comment]
My project is [here](https://github.com/puffdrum/v4tiny_pt_quant).

**Comment by hoadv-qh** [comment]
Hi @puffdrum  

I think you should exclude yolo layers from quantization.
In my understanding, yolo layers should be by CPU (convert output to human readable).
For DPU, it only takes 1 Input (image data) and will return 2 output that is 2 layer before yolo in .cfg file.

**Comment by niuxjxlnx** [comment]
Please refer to yolox model in vitis-ai modelzoo on how to quantize it. Some preprocess and post-process layers should not be quantized. https://github.com/Xilinx/Vitis-AI/tree/master/models/AI-Model-Zoo/model-list. Close this issue first.
