### ISSUE TITLE
[v1.3.2] Undefined symbol in vai_c_caffe in newly built gpu-based docker image

### ISSUE THREAD

**Issue by nickfraser** [Xilinx/Vitis-AI#512]
I get the following error when running `vai_c_caffe` on a newly built gpu-based docker image of the `v1.3.2` tag of Vitis-AI.

An example is below:
```
(vitis-ai-caffe) Vitis-AI /workspace/resnet50-dropout0.005-vai > vai_q_caffe finetune -solver solver.prototxt -weights quantize_results/quantize_train_test.caffemodel -gpu 0
vai_q_caffe: symbol lookup error: /opt/vitis_ai/conda/envs/vitis-ai-caffe/bin/../lib/libcaffe-nv.so.0.15: undefined symbol: _ZN6google21kLogSiteUninitializedE
```

Looks like it's related to the `glog` version. I will post a workaround or submit a PR if I find a fix.

**Comment by hanxue** [comment]
Hey @nickfraser ,


Appreciate your PR! 

The glog dependency was fixed in Vitis AI 1.4 onwards. If you have not already, I suggest using Vitis AI 2.0.0


Cheers,
Hanxue
