### ISSUE TITLE
[vai 1.4 - oom error ]tf2 fast fintune on custom resnet50

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#519]
Hi,

I have enabled the tf2 fast finetune on my custom resent50, here is my code.

`          model = vitis_quantize.VitisQuantizer(model).quantize_model(calib_dataset=quant_dataset,
                                                                  include_cle=True, 
                                                                  cle_steps=10,
                                                                  include_fast_ft=True,
                                                                  fast_ft_epochs=10)   `

I got an oom error as below. I also tried to adjust the fast_ft_epochs to other value but the oom error was still happened.
![image](https://user-images.githubusercontent.com/40138266/130398100-5e148ccd-4d9c-4f19-ad62-8e9f944bc17b.png)

My VGA VRAM is 8 GB, but it seems it is not enough. Do you any recommend about oom?

**Comment by xieyi4650** [comment]
try reduce `calib_batch_size` you can set it in vitis_quantize.VitisQuantizer(model).quantize_model

**Comment by renjiangyong** [comment]
@hill19850213  Does OOM resolve? this issue is existed for a long time, I will close this issue, if you have any problem you can reopen it ,thank you .
