### ISSUE TITLE
Build time is too slow

### ISSUE THREAD

**Issue by paroque28** [Xilinx/Vitis-AI#54]
I have a 40 thread Xeon CPU and the build time is too slow

INFO: [v++ 60-791] Total elapsed time: 1h 46m 14s

The command I used:
$ make KERNEL=DPU_SM DEVICE=zcu102

My question is: Does this have multithreading enabled by default?

**Comment by qianglin-xlnx** [comment]
Hi @paroque28 
Yes. Multithreading is enabled by default when you compile the project. It's true that the whole build will take a long time. Most of the time is spent on systhesis and implementation step.
