### ISSUE TITLE
error with ConvolutionFixedLayer<Dtype>::Forward_cpu ?

### ISSUE THREAD

**Issue by Richsheep** [Xilinx/Vitis-AI#542]
Recently using caffe-xilinx to evaluate quantized caffe model base on x86,
But the output of the quantized model seems to be too different from the original floating-point model
Code below seems wrong, pls check L120 and L135, should it be:

```cpp
                 fixed_blobs[1]->mutable_cpu_data(), this->bias_dec_pos_ ); 
```

Will this problem affect my quantized evaluate result?

https://github.com/Xilinx/Vitis-AI/blob/f61061eef7550d98bf02a171604c9a9f283a7c47/models/AI-Model-Zoo/caffe-xilinx/src/caffe/layers/conv_fixed_layer.cpp#L115-L120

https://github.com/Xilinx/Vitis-AI/blob/f61061eef7550d98bf02a171604c9a9f283a7c47/models/AI-Model-Zoo/caffe-xilinx/src/caffe/layers/conv_fixed_layer.cpp#L130-L135

**Comment by niuxjxlnx** [comment]
Hi, @Richsheep:

The code at L120 and L135 are correct as expected. You can refer to the comment. Weight and bias needs enlarge and shrink with the same scale. It will not affect quantized model accuracy.
