### ISSUE TITLE
Autonomous driving visual 3D typical network

### ISSUE THREAD

**Issue by yyqgood** [Xilinx/Vitis-AI#543]
Hello, are there any plans to adapt to the typical network of autonomous driving monocular 3D object detection and stereo 3D object detection?

Looking forward for your response, thank you!

**Comment by wangxd-xlnx** [comment]
Hi @yyqgood 
For Autonomous driving visual network, monocular 3D object detection is in research now. But stereo 3D is not in research plan.

**Comment by qianglin-xlnx** [comment]
Hi @yyqgood 
Since we haven't received your reply for a long time, I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
