### ISSUE TITLE
DNNDK n2cube create kernel vs create task.

### ISSUE THREAD

**Issue by daivikbhatia** [Xilinx/Vitis-AI#547]
Hi,
I found out that we can make multiple kernels and multiple tasks of same kernel in DNNDK. What's the difference logically in this and which one will be better for a higher FPS while using multiprocessing?

**Comment by max271828** [comment]
multiple kernels will occupy more resource of the hardware, but multiple tasks don't. You 'd better to use multiple tasks if you want the higher FPS.
