### ISSUE TITLE
Broken link to Vitis AI User guide

### ISSUE THREAD

**Issue by xterryo** [Xilinx/Vitis-AI#55]
https://github.com/Xilinx/Vitis-AI/tree/master/mpsoc

Vitis AI User Guide link is broken

**Comment by qianglin-xlnx** [comment]
Hi @xterryo 
Thank you for your feedback. Vitis AI User Guide link has been updated in https://github.com/Xilinx/Vitis-AI/tree/master/mpsoc.

**Comment by qianglin-xlnx** [comment]
Hi @xterryo 
Since I haven't received your reply for a long time and the issue you mentioned is fixed in Vai1.1, I will close this issue. Thank you.
