### ISSUE TITLE
vai_q_pytorch quantization bert

### ISSUE THREAD

**Issue by dogragon** [Xilinx/Vitis-AI#550]
Hi!
I am trying to deploy the bert model to Alveo U280, and want to know whether the vai_q_pytorch supports bert quantization.

**Comment by wangxd-xlnx** [comment]
Hi @dogragon 

At present, bert quantization is not supported by vai_q_pytorch. We are planning to support it in next version.

The new version is expected to be released in the middle of 2022, so stay tuned.
