### ISSUE TITLE
Checksum mismatch with GPU model downloads

### ISSUE THREAD

**Issue by yetimoss** [Xilinx/Vitis-AI#554]
There are several GPU model downloads in the Vitis-AI repository with computed checksums that don't match the ones listed in the model.yaml files.  

**The models are:**

1. pt_FPN-resnet18_covid19-seg_352_352_22.7G_1.4
2. pt_pointpillars_kitti_12000_100_10.8G_1.4
3. pt_pointpillars_kitti_12000_100_10.8G_1.4
4. pt_salsanextv2_semantic-kitti_64_2048_0.75_32G_1.4
5. tf_rcan_DIV2K_360_640_0.98_86.95G_1.4

See attached text file for more details:
[Vitis-AI-Repo_bad_checksums_gpumodels.log](https://github.com/Xilinx/Vitis-AI/files/7346779/Vitis-AI-Repo_bad_checksums_gpumodels.log)

**Comment by wangxd-xlnx** [comment]
Hi @yetimoss,
these 4 models have been updated in download package, and MD5 checksum updated in 1.4.1 repo. Now 1.4.1 is very close to release. Then the package and MD5 will be consistent.
