### ISSUE TITLE
No response after invoking the running of DPU for my custom model

### ISSUE THREAD

**Issue by wanghao16020510036** [Xilinx/Vitis-AI#558]
Before executing the following code, everything is normal. 
```C++
auto job_id = runner->execute_async(inputsPtr, outputsPtr);
runner->wait(job_id.first, -1);
```
After invoking DPU, this thread is suspended and has no response for a very long time and I can' t kill it. I want to know the possible reasons and what should I do.

**Comment by qianglin-xlnx** [comment]
Hi @wanghao16020510036 
Has this issue been solved?

**Comment by qianglin-xlnx** [comment]
Hi @wanghao16020510036 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
