### ISSUE TITLE
Vitis AI on custom board petalinux 2021.1

### ISSUE THREAD

**Issue by mmterkc** [Xilinx/Vitis-AI#562]
Hi, I am working on integrating Vitis ai on a custom platform. But petalinux v2021.1 doesn't have it. Are any tutorials integrating Vitis ai on a custom platform. I want to run python code on dpu like tutorials in these repos

**Comment by tianfang-fafafa** [comment]
hi @mmterkc, are you able to get recipes of vitis ai by esdk? (v2021.1)

**Comment by qianglin-xlnx** [comment]
Hi @mmterkc 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
