### ISSUE TITLE
Question with prototxt accuracy layer

### ISSUE THREAD

**Issue by FurballClaire** [Xilinx/Vitis-AI#566]
Hi, 
I'm trying to re-train cf_plate-recognition_96_288_1.75G_1.4 with my own dataset, and have a question about accuracy checking.
In trainval.prototxt there are 8 accuracy layers, and also 8 accuracy value in training log 
(as below : Test net output #7 ~ Test net output #14)

Does that mean I should add up the value from Test net output #7 to Test net output #14 to be the final accuracy? So the accuracy for example would be 0.046875 + 0.046875 + 0.09375 + ... + 0 = 0.6875 ?

_I1013 09:27:46.493047  1877 solver.cpp:523]     Test net output #7: char-1/top-1 = 0.046875
I1013 09:27:46.493052  1877 solver.cpp:523]     Test net output #8: char-2/top-1 = 0.046875
I1013 09:27:46.493055  1877 solver.cpp:523]     Test net output #9: char-3/top-1 = 0.09375
I1013 09:27:46.493059  1877 solver.cpp:523]     Test net output #10: char-4/top-1 = 0.140625
I1013 09:27:46.493062  1877 solver.cpp:523]     Test net output #11: char-5/top-1 = 0.125
I1013 09:27:46.493067  1877 solver.cpp:523]     Test net output #12: char-6/top-1 = 0.09375
I1013 09:27:46.493069  1877 solver.cpp:523]     Test net output #13: char-7/top-1 = 0.140625
I1013 09:27:46.493073  1877 solver.cpp:523]     Test net output #14: color/top-1 = 0_

layer {
  name: "char-1/top-1"
  type: "Accuracy"
  bottom: "score1"
  bottom: "label_1"
  top: "char-1/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-2/top-1"
  type: "Accuracy"
  bottom: "score2"
  bottom: "label_2"
  top: "char-2/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-3/top-1"
  type: "Accuracy"
  bottom: "score3"
  bottom: "label_3"
  top: "char-3/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-4/top-1"
  type: "Accuracy"
  bottom: "score4"
  bottom: "label_4"
  top: "char-4/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-5/top-1"
  type: "Accuracy"
  bottom: "score5"
  bottom: "label_5"
  top: "char-5/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-6/top-1"
  type: "Accuracy"
  bottom: "score6"
  bottom: "label_6"
  top: "char-6/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "char-7/top-1"
  type: "Accuracy"
  bottom: "score7"
  bottom: "label_7"
  top: "char-7/top-1"
  include {
    phase: TEST
  }
}

layer {
  name: "color/top-1"
  type: "Accuracy"
  bottom: "score8"
  bottom: "label_8"
  top: "color/top-1"
  include {
    phase: TEST
  }
}

I1013 09:27:46.414327  1877 solver.cpp:424] Iteration 10000, Testing net (#0)
I1013 09:27:46.493001  1877 solver.cpp:523]     Test net output #0: center_loss_1 = 12.0089 (* 0.01 = 0.120089 loss)
I1013 09:27:46.493019  1877 solver.cpp:523]     Test net output #1: center_loss_2 = 5.24614 (* 0.01 = 0.0524614 loss)
I1013 09:27:46.493024  1877 solver.cpp:523]     Test net output #2: center_loss_3 = 11.0822 (* 0.01 = 0.110822 loss)
I1013 09:27:46.493029  1877 solver.cpp:523]     Test net output #3: center_loss_4 = 8.95363 (* 0.01 = 0.0895363 loss)
I1013 09:27:46.493034  1877 solver.cpp:523]     Test net output #4: center_loss_5 = 6.53369 (* 0.01 = 0.0653369 loss)
I1013 09:27:46.493038  1877 solver.cpp:523]     Test net output #5: center_loss_6 = 3.18075 (* 0.01 = 0.0318075 loss)
I1013 09:27:46.493043  1877 solver.cpp:523]     Test net output #6: center_loss_7 = 4.05542 (* 0.01 = 0.0405542 loss)
I1013 09:27:46.493047  1877 solver.cpp:523]     Test net output #7: char-1/top-1 = 0.046875
I1013 09:27:46.493052  1877 solver.cpp:523]     Test net output #8: char-2/top-1 = 0.046875
I1013 09:27:46.493055  1877 solver.cpp:523]     Test net output #9: char-3/top-1 = 0.09375
I1013 09:27:46.493059  1877 solver.cpp:523]     Test net output #10: char-4/top-1 = 0.140625
I1013 09:27:46.493062  1877 solver.cpp:523]     Test net output #11: char-5/top-1 = 0.125
I1013 09:27:46.493067  1877 solver.cpp:523]     Test net output #12: char-6/top-1 = 0.09375
I1013 09:27:46.493069  1877 solver.cpp:523]     Test net output #13: char-7/top-1 = 0.140625
I1013 09:27:46.493073  1877 solver.cpp:523]     Test net output #14: color/top-1 = 0
I1013 09:27:46.493078  1877 solver.cpp:523]     Test net output #15: loss1 = 3.43402 (* 1 = 3.43402 loss)
I1013 09:27:46.493083  1877 solver.cpp:523]     Test net output #16: loss10 = 1.7594e-05 (* 1 = 1.7594e-05 loss)
I1013 09:27:46.493088  1877 solver.cpp:523]     Test net output #17: loss11 = 3.06595e-06 (* 1 = 3.06595e-06 loss)
I1013 09:27:46.493094  1877 solver.cpp:523]     Test net output #18: loss12 = 8.17079e-05 (* 1 = 8.17079e-05 loss)
I1013 09:27:46.493101  1877 solver.cpp:523]     Test net output #19: loss13 = 6.52614e-06 (* 1 = 6.52614e-06 loss)
I1013 09:27:46.493106  1877 solver.cpp:523]     Test net output #20: loss14 = 6.5437e-05 (* 1 = 6.5437e-05 loss)
I1013 09:27:46.493111  1877 solver.cpp:523]     Test net output #21: loss15 = 0.000146175 (* 1 = 0.000146175 loss)
I1013 09:27:46.493115  1877 solver.cpp:523]     Test net output #22: loss16 = 0.000373983 (* 1 = 0.000373983 loss)
I1013 09:27:46.493120  1877 solver.cpp:523]     Test net output #23: loss2 = 4.4682 (* 1 = 4.4682 loss)
I1013 09:27:46.493124  1877 solver.cpp:523]     Test net output #24: loss3 = 3.39354 (* 1 = 3.39354 loss)
I1013 09:27:46.493129  1877 solver.cpp:523]     Test net output #25: loss4 = 2.52323 (* 1 = 2.52323 loss)
I1013 09:27:46.493134  1877 solver.cpp:523]     Test net output #26: loss5 = 2.58557 (* 1 = 2.58557 loss)
I1013 09:27:46.493139  1877 solver.cpp:523]     Test net output #27: loss6 = 2.35224 (* 1 = 2.35224 loss)
I1013 09:27:46.493142  1877 solver.cpp:523]     Test net output #28: loss7 = 2.35104 (* 1 = 2.35104 loss)
I1013 09:27:46.493147  1877 solver.cpp:523]     Test net output #29: loss8 = 8.24727 (* 1 = 8.24727 loss)
I1013 09:27:46.493151  1877 solver.cpp:523]     Test net output #30: loss9 = 0.000510821 (* 1 = 0.000510821 loss)

**Comment by wangxd-xlnx** [comment]
Hi @FurballClaire 

Yes, he is referring to this script. Has your issue been resolved? Then we will close this issue.

**Comment by FurballClaire** [comment]
ok
