### ISSUE TITLE
Custom board vitis-ai

### ISSUE THREAD

**Issue by mmterkc** [Xilinx/Vitis-AI#567]
Hi, everyone I integrate vitis-ai with vivado and petalinux 2021.1. I use /home/adt01/Vitis_AI/Vitis-AI/dsa/DPU-TRD/prj/Vivado/pre-build xsa file. I use metavitisai on github. I have 2021.1 version of metavitisai. But get  dpu_controller.cpp:44] Check failed: !the_factory_methods.empty()
How can I solve these error?

**Comment by andrew0917** [comment]
Hi @mmterkc，
     I find that you are integrating the DPU with vivado flow(2021.1) to **Zynq**.  As for Vivado flow, there is the reference for [ZCU102](https://github.com/Xilinx/Vitis-AI/tree/1.4.1/dsa/DPU-TRD/prj/Vivado), However, it is for Zynq MpSOC(aarch64) instead of Zynq, and we haven't supported Zynq yet.

**Comment by iivanov1996** [comment]
Hi,

I am also using the reference for ZCU102 to create a custom project for ZCU104.
 
The output I get from lsmod is:
![image](https://user-images.githubusercontent.com/97990124/162693667-1466e4d4-7f77-4a8f-8b85-a587e0915e36.png)


None of the commands for dpu check are providing the expected output. I am receiving the same error message:
![image](https://user-images.githubusercontent.com/97990124/162694570-e4a09798-99eb-46d7-82da-d4fad05fdc94.png)


any suggestions?

**Comment by andrew0917** [comment]
Hi @iivanov1996,
    As for  integrating DPU IP to  your custom petalinux project for ZCU104,there are two steps:
    STEP1:  Copy the recipes-modules directory(you can get it from the release zcu102 reference(vitis 2.0/2021.2) https://github.com/Xilinx/Vitis-AI/blob/master/dsa/DPU-TRD/prj/Vivado/dpu_petalinux_bsp/download_bsp.sh)  to your  <petalinux projct>/project-spec/meta-user/ ;
    STEP2: enable the dpu driver to your petalinux project, there are two ways to accomplish it, as the following description:
Way1:   add IMAGE_INSTALL_append = " dpu " to <petalinux projct>/project-spec/meta-user/conf/petalinuxbsp.conf;
Way2:   add CONFIG_dpu to <petalinux projct>/project-spec/meta-user/conf/user-rootfsconfig  and run petalinux-config -c rootfs command to enable it;
![image](https://user-images.githubusercontent.com/68576025/163121726-8e05c438-a30a-4b0e-b30a-150cdf6d8065.png)

**Comment by qianglin-xlnx** [comment]
Hi @iivanov1996 
Regarding the failure of VART package installation, the error shows the RPM package can't be installed on your system.
Could you please check the whether the packages are complete and whether the RPM related commands run normally, such as "rpm -qa"
You can also refer to: https://kb.vmware.com/s/article/68103
