### ISSUE TITLE
Pytorch residual connection layer failed to export xmodel

### ISSUE THREAD

**Issue by waldenou** [Xilinx/Vitis-AI#570]
Hi,

I am trying to compile a pytorch model that includes residual connection layer (previous layer is added onto the current layer). When doing forward pass, everything looks fine, and the model is able to be quantized. However, when exporting to xmodel, I see the following error:

`WARNING: Logging before InitGoogleLogging() is written to STDERR
F1022 08:11:19.983764   243 shape_inference.cpp:910] [UNILOG][Check Failed: std::get<0>(sbc_rlt)][/home/xbuild/conda-bld/xir_1606383669768/work/src/xir/op/shape_inference.cpp:910][XIR_INVALID_ARG_OCCUR][Invalid arg occurence!] xir::Op{name = Model__Model_44, type = add}'s input size are not matching. One is {1, 3, 1022, 16} and another is {1, 1, 1024, 16}.
*** Check failure stack trace: ***`

I have attached my model architecture and the quantizer output. I am currently using Vitis-AI 1.4. Any help is appreciated.
[model.zip](https://github.com/Xilinx/Vitis-AI/files/7398234/model.zip)

**Comment by Alexiazzf** [comment]
Hi @waldenou ,

I think your problem has fix now. You can use Vitis-AI 2.0 to check if there is still that problem.

**Comment by Alexiazzf** [comment]
Hi @waldenou,

Have you solved your problem? If you have solved this problem, please let me know. Thanks.

**Comment by niuxjxlnx** [comment]
Verified with Vitis-AI 2.0 and this problem has gone.
