### ISSUE TITLE
demo/VART/adas_detection/src/main.cc

### ISSUE THREAD

**Issue by zhangchenchen-novauto** [Xilinx/Vitis-AI#579]
<img width="932" alt="截屏2021-11-03 下午4 15 45" src="https://user-images.githubusercontent.com/84957934/140027736-174c701a-d559-4fa4-a4d9-bf6ecaeb04f3.png">

I can't understand why it is written like this here
If data[i] is less than 0 after quantization,   what  doing?

And I think data[i] will never be less than 0

**Comment by yongshengxu-xlnx** [comment]
This processing is for data[i]=128, because it is the type of int8_t, 128 will cross the boundary and become a negative number. This process is to assign all the numbers of 128 to 127.

**Comment by CallmeZhangChenchen** [comment]
OK!  I get it.
