### ISSUE TITLE
Vitis AI Library model for BCC (Bayesian Crowd Counting) output objects

### ISSUE THREAD

**Issue by Ali-Flt** [Xilinx/Vitis-AI#583]
In the Vitis AI Library v1.4 user guide page 74, it has been said that the output of the model is the number of people plus the density map.
![image](https://user-images.githubusercontent.com/60854595/140416412-0f2f4e4e-94d1-4c80-aa5a-ffec27ffca20.png)

But in page 325, it says that the output struct type only contains the following:
![image](https://user-images.githubusercontent.com/60854595/140416566-b0ebb2b1-d9af-4871-be64-f1963cea337b.png)

So where can you get the density map result from this model?

**Comment by lishixlnx** [comment]
Sorry for the boring, this document is obsolete.  
The image is not provided,  and the output should be only the count number.
