### ISSUE TITLE
DPU Integration With Vivado: [DNNDK_XRT] Cannot find device, index: 0

### ISSUE THREAD

**Issue by Hamptonjc** [Xilinx/Vitis-AI#586]
I followed chapter 5 in the DPU user guide (https://www.xilinx.com/support/documentation/ip_documentation/dpu/v3_3/pg338-dpu.pdf) to integrate the DPU into my block design.

I added the dpu node to the device tree and created the software components with PetaLinux.

However upon using dexplorer I get the error "[DNNDK_XRT] Cannot find device, index: 0"

When trying to run my VART application the dpu controller throws the same error.

`xbutil scan`:
![image](https://user-images.githubusercontent.com/41594631/141006527-04035f5a-5604-42df-8670-95123f82c111.png)

`cat /proc/interrupts`:
![image](https://user-images.githubusercontent.com/41594631/141006665-1531d886-815b-4086-b7af-f4d2bccf3210.png)
 
Any ideas?

**Comment by tianfang-fafafa** [comment]
@Hamptonjc   hi,  which flow(vitis flow or vivado flow) did you use? and could you please share steps for details?

**Comment by qianglin-xlnx** [comment]
Hi @Hamptonjc 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.

**Comment by Urbont** [comment]
hi, i think i have met the same problem, could u please share your solutions?

**Comment by tianfang-fafafa** [comment]
hi @Urbont, could you please try to add dpu into your block design with v2022.2 tool? the version of dpu match v2022.2 is v4.1. And share your steps to reporpduce issue if issue still exists
