### ISSUE TITLE
Maths functions

### ISSUE THREAD

**Issue by samyhocine** [Xilinx/Vitis-AI#587]
Hi,

On the Xilinx website it's written that there are Math, Linear Algebra and statistics functions included inside the Vitis-AI Library but all I can see related to that is the exponential function (accelerated using SIMD Neon assembly instructions). Of course there are plenty of functions related to Neural Network.

No maths functions (sin/cos...), linear algebra (dot product, cross product, normalisation...), machine learning (no KMeans, no Hierarchical Agglomerative Clustering), statistics...

How is it so ?

**Comment by ensiehaliagha** [comment]
Hello, 
I also have the same question. It would be great if they answer and clearly indicate how the acceleration can be done for Math functions.

**Comment by Hamptonjc** [comment]
There are other Vitis libraries besides Vitis-AI.

These might be what you are looking for:

https://www.xilinx.com/products/design-tools/vitis/vitis-libraries/vitis-solver.html

https://www.xilinx.com/products/design-tools/vitis/vitis-libraries/vitis-blas.html

**Comment by samyhocine** [comment]
Thanks for the feedback ;)

**Comment by ensiehaliagha** [comment]
Thanks a lot for providing the links.
