### ISSUE TITLE
Vitis AI pytorch quantization problem for yolov5 model

### ISSUE THREAD

**Issue by kct890721** [Xilinx/Vitis-AI#589]
Hi everyone,
I'm trying to accelerate a Pytorch YoloV5s model. Here you have the link to the model.
Can someone help to solve this problem,it bothered me for a month.
When quantizing, the following error is arise:
![15071374341599](https://user-images.githubusercontent.com/86824960/141440852-d980b002-362a-4c8e-b87b-14f5fba1916e.jpg)
![15071374324236](https://user-images.githubusercontent.com/86824960/141440914-0f6df5cc-682f-448c-a61a-b34a954e5ef8.jpg)
![1352251](https://user-images.githubusercontent.com/86824960/141440964-0fbe7e0c-e25f-48b7-8efc-95f849cc8077.jpg)

**Comment by kct890721** [comment]
here are my cod
[quantize(.py).txt](https://github.com/Xilinx/Vitis-AI/files/7526276/quantize.py.txt)
[common(.py).txt](https://github.com/Xilinx/Vitis-AI/files/7526277/common.py.txt)
[yolo(.py) .txt](https://github.com/Xilinx/Vitis-AI/files/7526278/yolo.py.txt)
e.

**Comment by carrotandjzy** [comment]
Can you provide  pytorch version in this case ?

**Comment by kct890721** [comment]
hey@ carrotandjzy my pytorch version is  1.10.0+cu102

**Comment by carrotandjzy** [comment]
In vitis-1.4.1, torch 1.7 is the highest version supported by vai_q_pytorch.

**Comment by niuxjxlnx** [comment]
Pytorch 1.7 version has been supported in Vitis-AI 1.4, and pytorch 1.8, 1.9 version have been supported in Vitis-AI 2.0.
Further more, solution to change pytorch versions among the supported version range is released, please refer to the related part about script replace_pytorch.sh in user guide.

**Comment by krishnaadithya** [comment]
@kct890721 @niuxjxlnx @carrotandjzy 

Do you guys have the instruction to quantise yolov5 trained model to deploy in kv260?

**Comment by masrourabdou** [comment]
have you the problem
