### ISSUE TITLE
Illegal variable name

### ISSUE THREAD

**Issue by jing-fi** [Xilinx/Vitis-AI#59]
Hi 
I am running Vitis-AI/alveo/examples/tensorflow/ examples
(https://github.com/Xilinx/Vitis-AI/tree/master/alveo/examples/tensorflow)

however in the step source setup.sh
source /home/jingy/Vitis-AI/alveo/overlaybins/setup.sh
shows error "Illegal variable name"

I am using ubuntu16.04, and Alveo U200 board.
How do i fix the issue?

**Comment by sumitn-xilinx** [comment]
Did you load the docker and activated the corresponding conda environement?

**Comment by jing-fi** [comment]
Hi ,

Do you mean this one?
https://github.com/Xilinx/Vitis-AI/blob/master/doc/install_docker/load_run_docker.md
cpu tools docker, gpu tools docker and runtime docker?

If yes, I haven’t load it since I am not sure the version.
May I know how do I check the cpu, gpu and runtime version?

Regards,
Yang Jing

**Comment by sumitn-xilinx** [comment]
try xilinx/vitis-ai:runtime-1.0.0-cpu

**Comment by jing-fi** [comment]
It is correct?

jingy@xapthor40:/home/jingy/Vitis-AI% ./docker_run.sh xilinx/vitis-ai:tools-1.0.0-cpu
Running as jingy
passwd: password expiry information changed.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

bash: export: `1': not a valid identifier
bash: export: `14:51:32': not a valid identifier
bash: export: `2019': not a valid identifier

==========================================
__      ___ _   _                   _____
\ \    / (_) | (_)            /\   |_   _|
\ \  / / _| |_ _ ___ ______ /  \    | |
  \ \/ / | | __| / __|______/ /\ \   | |
   \  /  | | |_| \__ \     / ____ \ _| |_
    \/   |_|\__|_|___/    /_/    \_\_____|

==========================================

Docker Image Version: 1.0.0
Build Date: Sun
VAI_ROOT=/opt/vitis_ai
For TensorFlow Workflows do:
  conda activate vitis-ai-tensorflow
For Caffe Workflows do:
  conda activate vitis-ai-caffe
jingy@xapthor40:/workspace$

**Comment by jing-fi** [comment]
Not sure how to fix this

jingy@xapthor40:/home/jingy/Vitis-AI%                                                         D
jingy@xapthor40:/home/jingy/Vitis-AI% sudo ./docker_run.sh xilinx/vitis-ai:runtime-1.0.0-cpu
[sudo] password for jingy:
WARNING: Error loading config file: /home/jingy/.docker/config.json: stat /home/jingy/.docker/config.json: permission denied
Running as root
useradd: user 'root' already exists
/etc/login.sh: line 12: /home/root/.bashrc: No such file or directory
/etc/login.sh: line 13: /home/root/.bashrc: No such file or directory

**Comment by hanxue** [comment]
Hi @jing-fi , could you please try with the latest v1.2 docker images?

The summarized steps are:
1. Download and install Docker (version 19.03.1 preferably)
2. Create the `docker` group and add yourself to it
3. Get a copy of this repo 

```
git clone --recurse-submodules https://github.com/Xilinx/Vitis-AI  
cd Vitis-AI
```

Or if you already have a copy, then update it

```
cd Vitis-AI
git pull origin master
```

4. Get the latest Vitis AI 1.2 CPU docker image `docker pull xilinx/vitis-ai:latest `
5. Run the docker image

```
./docker_run.sh xilinx/vitis-ai:latest
```

What is the result of using the v1.2 docker image?

**Comment by qianglin-xlnx** [comment]
Hi @jing-fi 
Since we haven't received your reply for a long time, I'm going to close this issue. If you still have any questions, please feel free to reopen it. Thank you very much.
