### ISSUE TITLE
Is it possible to use DPU with PL memory?

### ISSUE THREAD

**Issue by siliangZ** [Xilinx/Vitis-AI#591]
I am new to Vitis AI and VART. I am trying to understand if it is possible to run inference with DPU and PL memory. I searched in the examples. It seems like they all use CpuFlatTensorBuffer to store the input data.(I assume it is PS memory). So I am wondering if there is a API to support user to use DPU with PL memory. 
And I found that in the execute_async function, it has some copy functions which seems copy data from Host virtual space to physical space. I am wondering if I could just construct the input tensor buffer in the physical space and then I could save the time on copying data. And I found there is a class TensorBufferExtImpHostPhy. The location of it is HOST_PHY. Could I use that to avoid data transfer from host memory to device memory?
And I don't find much document talking about this. Please help me if you know. I would really appreciate it.

**Comment by wilderfield** [comment]
VART assumes that the input data to any model is coming from the CPU. Therefore there is always a data transfer from host memory to device memory (ddr). There is also the reverse transfer from device memory (ddr) to host memory at the end of an inference.

Can you please describe the scenario you are trying to support?

**Comment by deandrew119** [comment]
From the hardware design, the DPU can only access the PS side DDR though the AXI interface  . In ZU7EV or ZU5EV, only the VCU can add the DDR4 controller at PL side.

**Comment by siliangZ** [comment]
@wilderfield Thank you so much for your reply. The scenario is that the input data is generated into PL memory by ADC on PL. So I am trying to avoid coping data around. My assumption is that the device memory is PL DDR. So if we could just give DPU the memory buffer created by ADC, then we could save some time there. Since we don't need to do any other preprocessing on the input data.

**Comment by siliangZ** [comment]
@deandrew119 That is good to know. then I think my assumption will not hold any more. I thought DPU has access to PL DDR.

**Comment by tianfang-fafafa** [comment]
@siliangZ   hi,  which platform or board （cloud or edge） are you using ？

**Comment by SlevinZhang** [comment]
@tianfang-fafafa 
thank you for replying. I am using ultrazed-ev.

**Comment by qianglin-xlnx** [comment]
@SlevinZhang 
Can you get the physical address of PL DDR on ARM PS side? 
If yes, you can use "Zero Copy" mode of VART. For "Zero Copy" samples, refer to: https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Runtime/VART/vart/dpu-runner/samples/resnet50_zero_copy

**Comment by tianfang-fafafa** [comment]
hi @SlevinZhang ,  someone ever did that both CPU and DPU use PL ddr on other board, but performance of PL ddr is low.

**Comment by qianglin-xlnx** [comment]
Hi @siliangZ 
Since we haven't received your reply for a long time, I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
