### ISSUE TITLE
Is TensorBufferExtImpHostPhy a class we could use to create TensorBuffer on HOST_PHY?

### ISSUE THREAD

**Issue by siliangZ** [Xilinx/Vitis-AI#592]
I found that there is a copy_for_input function called if the input buffer is on HOST_VIRT. I would like to avoid doing that copy to speed the process. And I came across the class TensorBufferExtImpHostPhy. I am wondering if that is a valid class we could use to achieve the goal. And if it is, is there a example of using it?

**Comment by deandrew119** [comment]
You can refer to "Vitis-AI/tools/Vitis-AI-Library/facedetect/test/test_facedetect_zero_copy.cpp", this sample will show you the interfaces to implement the zero copy. Hope this can meet your requirement.

**Comment by yongshengxu-xlnx** [comment]
Hi, @siliangZ 
Can test_facedetect_zero_copy.cpp sample help you achieve your goals? This sample code has the interfaces to implement the zero copy.
Thanks for your feedback. And if there is no feedback, we will close the issue 1 week later.
