### ISSUE TITLE
Face Detect APIs missing in Chapter 8 (API References) of Vitis AI user guide (UG1354)

### ISSUE THREAD

**Issue by Ali-Flt** [Xilinx/Vitis-AI#594]
The Face Detect API references are missing from the ug1354 document.

**Comment by qianglin-xlnx** [comment]
Hi @Ali-Flt 
Thank you for your feedback. We will fix it in the next release.
Before we fix it, you can find the Face Detect API in https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Library/facedetect/include/vitis/ai/facedetect.hpp
