### ISSUE TITLE
Error response from daemon: No such image: xilinx/vitis-ai-gpu:1.4.1.978

### ISSUE THREAD

**Issue by JasonTryharder** [Xilinx/Vitis-AI#607]
I have following [this](https://github.com/Xilinx/Vitis-AI) to install vitisAI and trying to install gpu docker, 
below is mine configuration : 
Linux C001886040 5.11.0-41-generic#45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Nvidia RTX A3000,  NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5
Vitis unified platform 2021.1 
Docker version 20.10.11, build dea9396
cmake version 3.20.2

When run ./docker_build_gpu.sh 
it shows : 
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xrt : Depends: libboost-filesystem1.71.0 but it is not installable
       Depends: libboost-program-options1.71.0 but it is not installable
       Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.4 is to be installed
       Depends: libncurses6 (>= 6) but it is not installable
       Depends: libprotobuf17 but it is not installable
       Depends: libtinfo6 (>= 6) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/bash -c wget --progress=dot:mega -O xrt.deb ${XRT_URL}     && ls -lhd ./xrt.deb     && apt-get update -y     && apt-get install -y ./xrt.deb     && rm -fr /tmp/*' returned a non-zero code: 100
Error response from daemon: No such image: xilinx/vitis-ai-gpu:1.4.1.978
![Vitis-AI_docker_gpu_build_Error](https://user-images.githubusercontent.com/54369499/144725842-ddd8cf2e-7f12-4f82-bf82-15f7c5d6596b.png)

full error msg:
[Vitis-AI_docker_gpu_build_Error.txt](https://github.com/Xilinx/Vitis-AI/files/7654772/Vitis-AI_docker_gpu_build_Error.txt)

Thanks

**Comment by JasonTryharder** [comment]
I have found the same issue when creating cpu docker ./docker_build_cpu.sh
![Vitis-AI_docker_cpu_build_Error](https://user-images.githubusercontent.com/54369499/144726154-a1a5f936-0e71-44fd-9421-9eaaba212efc.png)
![Vitis-AI_docker_cpu_build_Error](https://user-images.githubusercontent.com/54369499/144726175-7cf6234b-fc50-4aa3-9390-7bf1fa67dc32.png)

full error msg: 
[Vitis-AI_docker_cpu_build_Error.txt](https://github.com/Xilinx/Vitis-AI/files/7654798/Vitis-AI_docker_cpu_build_Error.txt)

**Comment by schegde** [comment]
Hi,  I am also encountering similar issue, but different error message, when I try to build the `docker_build_gpu.sh` . I am on Ubuntu 18.04 host PC.
![image](https://user-images.githubusercontent.com/25887290/144925559-da04bf95-f4e9-4508-83a6-7126468da75b.png)

**Comment by nhphuong91** [comment]
@JasonTryharder vitis-ai hasn't supported Nvidia Ampere generation (yours is A3000). To be concrete, vitis-ai hasn't supported CUDA 11 + CUDA 10 don't support Nvidia Ampere gen
About building vitis-ai cpu, you can pull the pre-built docker image from here: https://hub.docker.com/r/xilinx/vitis-ai-cpu/tags
@schegde Try to switch to tag 'v1.4' or 'v1.4.1'. I'm usually avoid using master branch, it's inconsistent

**Comment by hanxue** [comment]
@JasonTryharder @schegde ,

Are you guys still having error message building the Vitis AI GPU docker image? 

Odd to see package conflict when installing XRT dependencies - boost, libc and so on. XRT uses the OS' default package version, and for Vitis AI GPU it is based on Ubuntu 18.04.

**Comment by siniGAL** [comment]
I have some problem:
```bash
make[2]: Leaving directory '/tmp/protobuf-3.4.0/src'
Makefile:1488: recipe for target 'all-recursive' failed  
make[1]: Leaving directory '/tmp/protobuf-3.4.0'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Makefile:1395: recipe for target 'all' failed
The command '/bin/bash -c cd /tmp; wget --progress=dot:mega https://codeload.github.com/google/protobuf/zip/v3.4.0     && unzip v3.4.0     && cd protobuf-3.4.0     && ./autogen.sh     && ./configure     && make -j     && make install     && ldconfig     && rm -fr /tmp/*' returned a non-zero code: 2  
Error response from daemon: No such image: xilinx/vitis-ai-gpu:2.0.0.1103  
Error response from daemon: No such image: xilinx/vitis-ai-gpu:2.0.0.1103
Error response from daemon: No such image: xilinx/vitis-ai-gpu:2.0.0.1103
```

**Comment by hanxue** [comment]
@siniGAL Please raise a separate Github Issue. These are different build errors. 

Are you building from the latest v2.0 release?

I see multiple lines of 

```
[0m[91mg++: internal compiler error: Killed (program cc1plus)
```

This may happen due to lack of resources on the docker build host. How much memory is allocated for docker build, and is there sufficient free disk space - recommended 100GB?

**Comment by siniGAL** [comment]
@hanxue thanks.
I create a new issue. I solved it.

**Comment by mykishan** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/51981523/173110384-9e9f23e5-1a6a-4860-98a1-59e0ebff404a.png">
Getting error while executing 

> ./docker_build_cpu.sh

returned a non-zero code: 137
Error response from daemon: No such image: xilinx/vitis-ai-cpu:2.0.0.1103
Error response from daemon: No such image: xilinx/vitis-ai-cpu:2.0.0.1103
Error response from daemon: No such image: xilinx/vitis-ai-cpu:2.0.0.1103
