### ISSUE TITLE
Versal DPU interrupt type?

### ISSUE THREAD

**Issue by ksstms** [Xilinx/Vitis-AI#608]
Hi!

I have noticed something in the XVDPU-TRD.
In the Vivado design the AXI interrupt controller's interrupt type is configured as `auto`, which results in it being set to `0xFFFFFFFF` (all edge-sensitive) after the DPU is added by the Vitis linker.

On the contrary, all interrupt lines are configured as level-sensitive in the PetaLinux device tree:
https://github.com/Xilinx/Vitis-AI/blob/5e500db21ceeff9830c5e57d4b81042cdb68e9ca/dsa/XVDPU-TRD/vck190_platform/petalinux/xilinx-vck190-base-trd/project-spec/meta-user/recipes-bsp/device-tree/files/vck190_mipiRxSingle_hdmiTx.dtsi#L45

I have also found that the DPU's interrupt pin's `SENSITIVITY` property is `EDGE_RISING` in Vivado, whereas [PG389 / page 14](https://www.xilinx.com/content/dam/xilinx/support/documentation/ip_documentation/dpucvdx8g/v1_0/pg389-dpucvdx8g.pdf#page=14) states that it should be an "Active-High interrupt"

I'm curious what would be the correct type for it, because we would like to build the DPU as well as other Vitis acceleration kernels on our platform, but the Vitis HLS kernels have level interrupt outputs.

**Comment by shycbi19830601** [comment]
EDGE_RISING is not correct，should be configured to be high level, VAI2.0 has solved it.
