### ISSUE TITLE
mobilenetv1_ssd download link is wrong

### ISSUE THREAD

**Issue by schabc** [Xilinx/Vitis-AI#611]
mobilenetv1_ssd download link is wrong
was linked to cf_resnet50_imagenet

**Comment by nhphuong91** [comment]
I found another model with similar issue:
`pt_personreid-res50_market1501_256_128_5.4G_1.4` was linked to `dk_yolov3_bdd_288_512_53.7G_1.4`

**Comment by wangxd-xlnx** [comment]
Hi @schabc @nhphuong91 

This issue has been identified as download server cache failure and has been resolved, you can try them again. Thanks for your feedback.

**Comment by nhphuong91** [comment]
Thanks, it has been resolved. You can close this issue now!
