### ISSUE TITLE
How can I get the temperature of VCK5000 using the SMBus/I2C interface

### ISSUE THREAD

**Issue by whyaysd** [Xilinx/Vitis-AI#614]
I found the SC document here: https://xilinx.github.io/Alveo-Cards/master/management-specification/oob-intro.html

And It conveys that we can get the temperature of my card using this interface.
However, I can not find the I2C address through i2cdetect command.

How can I using this Interface to get those information?

**Comment by hanxue** [comment]
Does this XRT command give you the information that you need?

```
sudo /opt/xilinx/xrt/bin/xbutil --legacy dump  -d 0000:d8:00.0
```

**Comment by SuZhan0322** [comment]
Hi @whyaysd ,
In VAI2.5, you can get the temperature of VCK5000 using XRT command:
/opt/xilinx/xrt/bin/xbutil examine --report thermal --device
thanks!

**Comment by SuZhan0322** [comment]
Hi @whyaysd ,
Any update about this issue? Thanks!

**Comment by SuZhan0322** [comment]
Hi @whyaysd ,
Please reopen this issue if you have any other questions. thanks!
