### ISSUE TITLE
Can I suspend VCK5000, which stop the power supply and stop the fan, when I am not using it

### ISSUE THREAD

**Issue by whyaysd** [Xilinx/Vitis-AI#615]
You know the VCK5000 is too noisy, I want to suspend it when I am not going to use it

**Comment by hanxue** [comment]
Hi @whyaysd ,

There is a similar thread at https://support.xilinx.com/s/question/0D52E00006khDFQSA2/vck5000-fan-noise-alternating?language=en_US 

Since this is a question on VCK5000, I would suggest starting a new thread at Xilinx Forums.
