### ISSUE TITLE
vaitrace power consumption (U50 board)

### ISSUE THREAD

**Issue by vittofa** [Xilinx/Vitis-AI#632]
Hello,
Is it possible with "vaitrace" to trace the board power consumption running my neural network? (I'm using U50 board)
If not, what's the best approach to do it?

Thanks.

**Comment by li900309** [comment]
hi @vittofa , the **xbutil query** command could be help, just setup XRT environment(source PATH_TO_XRT/setup.sh), then run **xbutil query** you can get the power and temp info from the report 
![图片](https://user-images.githubusercontent.com/7360000/149868879-b7453121-9644-4171-b12f-bb5d24f180eb.png)

**Comment by vittofa** [comment]
Thank you @li900309, I already use this command, I was wondering if could be possible to have a more accurate way to measure power consumption, but I guess I'll have to deal with it.

**Comment by vittofa** [comment]
For those interested in a complete prifiler output with power consmption for python's scripts you need to use "vaitrace" with "xrt.ini", you need to follow this instruction:
https://xilinx.github.io/XRT/master/html/xrt_ini.html
and set the desired parameters... 
https://docs.xilinx.com/r/en-US/ug1393-vitis-application-acceleration/xrt.ini-File
Thanks, bye.
