### ISSUE TITLE
how i deploy the xmodel on cpu？

### ISSUE THREAD

**Issue by white0dew** [Xilinx/Vitis-AI#636]
when i get a xmodel, there is a OP which should be running on CPU.
but I dont know how to deploy a OP on CPU, is there a example for us to follow?
Thanks!

**Comment by bryanloz-xilinx** [comment]
https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Runtime/VART/plugin-samples/samples/plugin-smfc-cpu

This might help

**Comment by white0dew** [comment]
> https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Runtime/VART/plugin-samples/samples/plugin-smfc-cpu
> 
> This might help

Thanks for your quickly reply, I mentioned that  Vitis Ai  2.0 is available ， so is there a new pdf for reading？

**Comment by qianglin-xlnx** [comment]
Hi @white0dew 
Yes. 
For Vitis AI 2.0 user guide, you can refer to : https://docs.xilinx.com/r/en-US/ug1414-vitis-ai 
For pdf version, refer to : http://www.xilinx.com/support/documentation/sw_manuals/vitis_ai/2_0/ug1414-vitis-ai.pdf

BTW, you can also refer to https://github.com/Xilinx/Vitis-AI/tree/master/demo/Custom_OP_Demo to deploy the OP on cpu.
