### ISSUE TITLE
The difference between "VART" and "Vitis AI Library"

### ISSUE THREAD

**Issue by CheungBH** [Xilinx/Vitis-AI#637]
Hi. I am a newcomer of Vitis-AI. I want to run some demo samples, but I found that there are similar samples in "VART" and "Vitis AI Library". I wonder what's the differences of them?

**Comment by bryanloz-xilinx** [comment]
VART == Vitis AI Run Time

The key difference is that Vitis AI Libraries is one extra layer on top of VART that provides utility functions for common ML models. It dives in to higher level application like object detection for example.

VART is more the mechanics of feeding data to the accelerator in the FPGA.
