### ISSUE TITLE
How to generate xclbin  for  "whole_app_acceleration"

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/Vitis-AI#64]
@wilderfield @sumitn-xilinx @kamranjk 
Regarding this 
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/apps/whole_app_acceleration

Already discussed the same(xplusml) issue here
https://github.com/Xilinx/Vitis-AI/issues/41

**Comment by mahinlma** [comment]
@sumitn-xilinx @wilderfield Please let me know, How to utilize libs provided 
https://github.com/Xilinx/Vitis-AI/tree/master/alveo/apps/whole_app_acceleration/libs

**Comment by sumitn-xilinx** [comment]
you first need the new xclbins. we will update this thread soon.

**Comment by mahinlma** [comment]
Okay, Thank you. @sumitn-xilinx , Please provide  xclbin for XRT version 2019.2

**Comment by nkpavan** [comment]
@mahinlma , you can download the xclbins using below links.
for Ubuntu:
https://www.xilinx.com/bin/public/openDownload?filename=vai-1.1-xplusml-bins-18.04.deb
for centOS:
https://www.xilinx.com/bin/public/openDownload?filename=vai-1.1-xplusml-bins-1.0-0.x86_64.rpm

**Comment by mahinlma** [comment]
Thank you @nkpavan
