### ISSUE TITLE
VAI 2.0: docker_run.sh contains incorrect path to PROMPT.txt

### ISSUE THREAD

**Issue by louiev-xlnx** [Xilinx/Vitis-AI#644]
WAS: ./setup/docker/docker/PROMPT.txt
IS: ./setup/docker/dockerfiles/PROMPT.txt

**Comment by qianglin-xlnx** [comment]
Hi @louiev-xlnx 
This issue is fixed. Please git pull the latest Vitis-AI and try it again. Thank you.
