### ISSUE TITLE
vck5000 power and vitis-ai quantify

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#645]
I've been using vck5000 and vitis-ai for a while and currently have two problems.
1. When using xbmgmt examine to obtain the power consumption of vck5000, the displayed power consumption is N/A.
2. Using vitis-ai to quantify the model (without compiling), the model size does not change.

**Comment by wanghy-xlnx** [comment]
Hi @jzymessi ,

Can you provide more detail? Such as
1. Which Vitis AI version are you using, such as Vitis AI 2.0?
2. What type of card are you using, VCK5000-ES1, or VCK5000-PROD?
3. According to which documentation, and what is the log output?

From the description, it seems that the version used is wrong and needs to be carefully checked or reconfigured. For example, Vitis AI 2.0 does not support VCK5000-ES1 and needs to be replaced with VCK5000-PROD. And, the development environment needs to be prepared according to the steps given in the following document,
https://github.com/Xilinx/Vitis-AI/tree/master/setup/vck5000
