### ISSUE TITLE
I used the tf2_erfnet_cityscapes_512_1024_54G_2.0 in AI-Model-Zoo , but when i evaluate the model, the mean IoU(%): 0.04

### ISSUE THREAD

**Issue by flaseConfidence** [Xilinx/Vitis-AI#647]

**Comment by wangxd-xlnx** [comment]
@flaseConfidence ,

Could you provide some more details for this issue? Such as your operation steps or screen shot.
I'm not sure, are you evaluating the float model or quantized model, or deployed xmodel on board?

In addition, I think you could check your data folder, whether the corresponding dataset is placed according to the model guide.

**Comment by qianglin-xlnx** [comment]
Hi @flaseConfidence 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
