### ISSUE TITLE
quantize in 3080ti problem

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#648]
When I use 3080ti to perform quantization in the doctor environment, the GPU shows that the memory is occupied,
but the program has not quantified. 
![image](https://user-images.githubusercontent.com/51226649/151118601-0e9e5e4e-6a4d-4d64-a70e-d50f1905273f.png)

![image](https://user-images.githubusercontent.com/51226649/151118762-59362cd5-96e2-43d5-8775-71e06261a51f.png)

However, in 2080ti, there is no problem in operation. What is the solution?

**Comment by qianglin-xlnx** [comment]
Hi @jzymessi 

Nvidia 30xx GPU not supported for Vitis AI Tensorflow 1.x GPU docker. 
You can use other GPU for quantizing TF1 model or use TF2 model

**Comment by jzymessi** [comment]
@qianglin-xlnx

**Comment by jzymessi** [comment]
@qianglin-xlnx 
thanks，will 30XX GPU be supported in the new version later?

**Comment by qianglin-xlnx** [comment]
HI  @jzymessi 

Because CUDA11 is not supported by TF1 itself, we do not intend to support TF1 with 30XX GPU.
