### ISSUE TITLE
Error while running - AI Kernel Scheduler

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/Vitis-AI#65]
@wilderfield  @sumitn-xilinx 

executed command
> ./aks.sh  -i py -m resnet50

Please let me know, how to fix this issue.
[INFO] Running
[INFO] Model: resnet50 with py

[INFO] Reading kernel_zoo/kernel_classify_preproc.json
[INFO] Reading kernel_zoo/kernel_dpuv1_norunner.json
[INFO] Reading kernel_zoo/kernel_image_read.json
[INFO] Reading kernel_zoo/kernel_caffe.json
[INFO] Reading kernel_zoo/kernel_add.json
[INFO] Reading kernel_zoo/kernel_yolo_post_proc.json
[ERROR] libdpuv1utils.so: cannot open shared object file: No such file or directory
[ERROR] Could not find the mandatory 'getKernel' function in libs/libYoloPostProc.so. Skipping this kernel.
[INFO] Reading kernel_zoo/kernel_detect_imreadpre.json
[INFO] Reading kernel_zoo/kernel_save_darknet_style.json

**Comment by sumitn-xilinx** [comment]
which docker are you using?

**Comment by mahinlma** [comment]
@sumitn-xilinx ,
docker from this https://hub.docker.com/r/xilinx/vitis-ai/tags

Please share the recent docker link

**Comment by mahinlma** [comment]
@sumitn-xilinx , Referred here https://github.com/Xilinx/Vitis-AI/blob/master/doc/install_docker/load_run_docker.md

**Comment by sumitn-xilinx** [comment]
please wait for the new docker to use AI Kernel Scheduler. Should be available in a day or so.

**Comment by mahinlma** [comment]
Thank you @sumitn-xilinx
