### ISSUE TITLE
Symmetric padding for PyTorch model

### ISSUE THREAD

**Issue by gau-nernst** [Xilinx/Vitis-AI#655]
Hello,

I want to use symmetric padding for my PyTorch model, since DPU can only use symmetric padding. Since there is no symmetric padding in PyTorch, there is no mapping between PyTorch modules and DPU instructions. Is there a way for me to insert DPU symmetric padding instruction in the xmodel after I convert PyTorch model to xmodel?

Thanks

**Comment by niuxjxlnx** [comment]
Hi, @gau-nernst:

DPU supports not only symmetric padding but also constant padding. You can try constant padding.

**Comment by gau-nernst** [comment]
No. In the end I did that part on CPU, since it was easier to write the code.

**Comment by masrourabdou** [comment]
I have a missunderstand you mean that you write plugin and pass through compilation but you must layer be quantized
