### ISSUE TITLE
About the docker image:vitis ai gpu!

### ISSUE THREAD

**Issue by white0dew** [Xilinx/Vitis-AI#658]
When i try to complie a VAI 2.0 Docker environment， I got many many many...problems , so could you please provide a **gpu-docker-image for convenient**， just like this: https://hub.docker.com/r/iivanov96/vitis-ai-gpu

i think this is easy for you, but will be very helpful to us!

Thanks a lot!

**Comment by qianglin-xlnx** [comment]
HI @white0dew 
Due to the GPU license issue, we can't provide a gpu-docker-image for public. Sorry about this.
Maybe you can ask the local Xilinx FAE for it.
