### ISSUE TITLE
Run inference on RTSP from VCK190

### ISSUE THREAD

**Issue by peterdors** [Xilinx/Vitis-AI#668]
I have an Amcrest branded IP camera that outputs video H264 codec. I would like to run inference (using the prebuilt boot image for the VCK 190) on the video feed of the camera through the cameras RTSP stream. 

Is there any guide for setting up the codecs to do this?

**Comment by xlnx-yuxiz** [comment]
@peterdors I suppose you are asking to use the Xilinx VCU IP to do the decoding, but unfortunately, VCK190 has no hard IP Video Codec, so you have to use the software way to do the decoding, that's based on the software stack you choose, either OpenCV or GStreamer, but as you know, it's slow.
