### ISSUE TITLE
fingerprint check failure on Ultra96V1

### ISSUE THREAD

**Issue by qhy991** [Xilinx/Vitis-AI#673]
When I run the example in Vitis-AI-tutorials, I met this Error:
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0209 12:11:33.135960  3394 dpu_runner_base_imp.cpp:689] CHECK fingerprint fail ! model_fingerprint 0x1000020f2014404 dpu_fingerprint 0x1000020f6014405
F0209 12:11:33.136103  3394 dpu_runner_base_imp.cpp:661] fingerprint check failure
 
I can't find the fingerprint of Ultra96V1. Please help me!

**Comment by qianglin-xlnx** [comment]
Hi @qhy991 
Has this issue been solved?

**Comment by qianglin-xlnx** [comment]
HI @qhy991 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
