### ISSUE TITLE
How to get Multiple Output from model?

### ISSUE THREAD

**Issue by rahulsingh701** [Xilinx/Vitis-AI#678]
Hi all, I have a Pytorch model which gives two outputs, a classification output and a segmentation output. I can see that during quantizing I can get the two outputs but when compiling the model, I am only getting my segmentation output and not the classification one. Can you please tell me how could I get both the outputs in Vitis AI python.

I am attaching the model defination file created by Vitis AI during quantization. You can see the return output_module 67 and 35 in the end of it.
[UNet.zip](https://github.com/Xilinx/Vitis-AI/files/8106725/UNet.zip)

**Comment by niuxjxlnx** [comment]
Hi, @rahulsingh701:

I find one of the output is after sigmoid OP, because sigmoid OP cannot run on DPU. It needs to exclude this OP in quantized part by partial quantization or packed it with custom OP.
Please refer to partial quantization or custom OP part on how to implement it.
