### ISSUE TITLE
How can I get OPS for compiled xmodels?

### ISSUE THREAD

**Issue by Richsheep** [Xilinx/Vitis-AI#681]
Is there anyway or any tool to find out OPS of xmodels? Or only could calculate FLOPS of float model.

I remember in DNNDK 3.1, GOPS will shown at model compile result. 

![image](https://user-images.githubusercontent.com/23067221/155058581-a4d13295-1df5-4820-9981-27b78b5543fc.png)

How can I get this param in Vitis-AI-1.3.2 for caffe/tensorflow compiled models？

thanks a lot.

**Comment by wanghong4compiler** [comment]
Hi @Richsheep,
if you want get more info about the compiled model, you could use "xir" tool. One method of its use is as follows:
xir dump_txt <xmodel> [<txt>]
        e.g. xir dump_txt a.xmodel a.txt
        when <txt> is missing, it dumps to standard output.
the txt file would provide a lot of details.
for code size, you can seach "mc_code", for parameter size, you can search "reg_id_to_size".
but unfortunately, the workload info is not available until Vitis-AI-2.0.

**Comment by Richsheep** [comment]
> Hi @Richsheep, if you want get more info about the compiled model, you could use "xir" tool. One method of its use is as follows: xir dump_txt [] e.g. xir dump_txt a.xmodel a.txt when is missing, it dumps to standard output. the txt file would provide a lot of details. for code size, you can seach "mc_code", for parameter size, you can search "reg_id_to_size". but unfortunately, the workload info is not available until Vitis-AI-2.0.

Hi @wanghong4compiler 
Thanks，but still confusing why workload is removed in vitis-ai，and why models in model-zoo have workload marked.

**Comment by wanghong4compiler** [comment]
Hi @Richsheep ,
sorry for the incorrect info, you can also get workload info.
sorry again.

**Comment by Richsheep** [comment]
> Hi @Richsheep , sorry for the incorrect info, you can also get workload info. sorry again.

Hi @wanghong4compiler 
How to get workload info?
Have to find any other tools?

**Comment by wanghong4compiler** [comment]
Hi @Richsheep ,
xir is a open source repo. you can get the source code from xilinx git.
this depend on unilog repo, which is also a open source repo, and also in xilinx git.
if you use the docker image, you can get xir directly without doing anything.

**Comment by Richsheep** [comment]
> Hi @Richsheep , xir is a open source repo. you can get the source code from xilinx git. this depend on unilog repo, which is also a open source repo, and also in xilinx git. if you use the docker image, you can get xir directly without doing anything.

Many thanks, I found workload info in xir dump_txt output, it seems in subg_root

![image](https://user-images.githubusercontent.com/23067221/155256145-93757ac5-4011-40ef-bab9-2ec5fdb38f7c.png)

Thanks again for your support!

**Comment by Serendi-pity1995** [comment]
> 

Hi, i also those info with the tool xir dump_txt . But i dont know which number represent Gops. What is the conversion relationship between them?  I used the tool xir to generate the info of the model "tf2_efficientnet-b0_imagenet_224_224_0.36G_2.0"  but the numbers here do not match it (0.36G)
![image](https://user-images.githubusercontent.com/68078643/156024396-8123c098-3d0c-4d24-8724-798d394db5b4.png)

thanks!

**Comment by ahnu-zhaorong** [comment]
My question is the same. How do I find the detailed documentation for OPS? The information of dump_txt provided is not stated in any way!
