### ISSUE TITLE
Reid Quantization Error by pytorch

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#684]
I used JDAI-CV/fast-reid(https://github.com/JDAI-CV/fast-reid) trained a  model(backbone  resnest ) , when I use  pytorch  quantize the model , The following error occurred :
![DEeLqXXQ4R](https://user-images.githubusercontent.com/51226649/155287560-ce0448d6-5b8c-45c6-aecf-9087f9695f13.png)
Does anyone know why?  Thanks.

**Comment by Alexiazzf** [comment]
Hi @jzymessi ,

It seems like there is something wrong with conv channels. Is there any error when you run float model? Can you upload  your torch model or show more details?

**Comment by qianglin-xlnx** [comment]
Hi @jzymessi 
Has the problem been solved?

**Comment by jzymessi** [comment]
> Hi @jzymessi Has the problem been solved?

Hi @qianglin-xlnx @Alexiazzf 
This problem has been solved,Thanks!
