### ISSUE TITLE
What exactly does the “Gops” in the Naming Rules in Vitis AI Model Zoo mean and how is it derived?

### ISSUE THREAD

**Issue by Serendi-pity1995** [Xilinx/Vitis-AI#687]

**Comment by Ru-Huang** [comment]
Hi，I've been doing some testing with your model recently. The whole tutorial is well done. But there is one place I don't understand, what exactly does the "Gops" mean and how you get this value ? 
![image](https://user-images.githubusercontent.com/68078643/155906142-158767ed-4d47-4640-961e-24a16c835604.png)

and can you explain  what is the difference between total trainable params and "Gops" here?
![image](https://user-images.githubusercontent.com/68078643/155906182-6ac4becf-4e24-4cdb-a427-4ef3f944a66b.png)

**Comment by Ru-Huang** [comment]
I'm just getting started with neural networks, and there are a lot of things I don't understand.  hope you can help me！

**Comment by wangxd-xlnx** [comment]
Hi @Serendi-pity1995 

It's actually a shorthand for G FLOPs. The FLOPs (Floating Point Operations) is used to measure the computational complexity of a model, and is often used as an indirect measure of the speed of a model.

So can sum up, it represents the amount of calculation. And ‘params’ is a completely different concept.

**Comment by Serendi-pity1995** [comment]
> 

Thanks for your reply, but how do I get the Gops of each model? I saw someone write that the xir tool can be used, is that right? Does the content in subg_root in the generated txt file represent Gops?

![image](https://user-images.githubusercontent.com/68078643/156171276-467a5731-5bcc-4fe9-955c-529879143db8.png)
I used the tool xir to generate the info of the model "tf2_efficientnet-b0_imagenet_224_224_0.36G_2.0" but the numbers here do not match it (0.36G).
I also tried to get infos of some other models.  In "tf_ssdinceptionv2_coco_300_300_9.62G_2.0" ,the number is 9,625,770,531
In "tf_mobilenetv2_1.0_imagenet_224_224_602M_2.0" ,the number is 608,725,705 . It looks like it fits right in.
It's just a coincidence, or I've got the wrong numbers.

**Comment by Serendi-pity1995** [comment]
> Hi @Serendi-pity1995
> 
> There‘re many open source tools to calculate flops. We recommend 'ptflops' or 'thop'. But please note that 1 MACs = 2 Flops.
> 
> Such as thop, please refer to https://github.com/Lyken17/pytorch-OpCounter.

Many thanks！
