### ISSUE TITLE
About Vitis AI support

### ISSUE THREAD

**Issue by yumianhuli2** [Xilinx/Vitis-AI#688]
Hello!
1. Does Vitis AI currently support FPGA ArtiX-7 Series?

2. Could you plz list all the FPGA series currently supported by Vitis AI?

3 Could QEMU-emulator simulate the whole process for AI ?
Thank you!

**Comment by sudharsan2000** [comment]
@andyluo7 @qianglin-xlnx any help would greatly help.
Is there any flow for using the images such as this one for [ZCU104](https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-zcu104-dpu-v2021.2-v2.0.0.img.gz) mentioned under this [page](https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc/VART).

**Comment by li900309** [comment]
Q3: as far as I know, DPU can not support QEMU emulator

**Comment by SteCla0** [comment]
Same question.
I don't understand why it is closed without reply/answer
