### ISSUE TITLE
 DPU model size doesn't match my yolov4 input

### ISSUE THREAD

**Issue by charles-str** [Xilinx/Vitis-AI#689]
I train yolov4-tiny with darknet, after quantize and compiled, I run it on ZCU104 , my input size is 608*608, why get 152*152 size
this is error

[ WARN:0] global /usr/src/debug/opencv/4.4.0-r0/git/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=-1, duration=1202
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0426 11:54:54.262604  1428 demo.hpp:744] DPU model size=152x152
I0426 11:54:54.300854  1428 demo.hpp:744] DPU model size=152x152
I0426 11:54:54.334166  1428 demo.hpp:744] DPU model size=152x152
I0426 11:54:54.366963  1428 demo.hpp:744] DPU model size=152x152
Segmentation fault

**Comment by charles-str** [comment]
> Hi @charles-str You can use xdputil tool to check the model input and output first, as shown below. ![image](https://user-images.githubusercontent.com/58016351/156316589-0fad9ec0-8628-41a0-b17c-0e2c9a0db169.png)

Thanks for your reply yesterday, I use xdputil tool to check the model input and output,  the input and output are wrong,
maybe it occured in the compiled process,  but it didn't report  any errors。

this is the model input and output:
![Screenshot from 2022-03-03 10-45-07](https://user-images.githubusercontent.com/35334263/156487379-901ad498-c9e7-442e-a6af-40708f3f3b34.png)


this is the  compiled information:
![Screenshot from 2022-03-03 10-44-30](https://user-images.githubusercontent.com/35334263/156487429-33966cfb-d7f7-4d33-a672-c6379fa577fd.png)
![Screenshot from 2022-03-03 10-46-41](https://user-images.githubusercontent.com/35334263/156487468-78732fc4-dd03-40f6-9adb-96dbc6448727.png)

**Comment by qianglin-xlnx** [comment]
Hi @charles-str 
Your model is based on TF1? If yes, you can specify the input tensor shape with an extra option
like --options '{"input_shape": "1,224,224,3"}'.

And one more thing, from the your comping log, you need to set the alpha value in leaky-relu from 0.1 to 0.101562. Thus, it will be assigned to DPU side.

**Comment by charles-str** [comment]
> Hi @charles-str Your model is based on TF1? If yes, you can specify the input tensor shape with an extra option like --options '{"input_shape": "1,224,224,3"}' when you compile the model.
> 
> And one more thing, from the your comping log, you need to set the alpha value in leaky-relu from 0.1 to 0.101562. Thus, it will be assigned to DPU side.

I train yolov4-tiny with caffe , input size is 608 * 608

**Comment by charles-str** [comment]
> Hi @charles-str Your model is based on TF1? If yes, you can specify the input tensor shape with an extra option like --options '{"input_shape": "1,224,224,3"}' when you compile the model.
> 
> And one more thing, from the your comping log, you need to set the alpha value in leaky-relu from 0.1 to 0.101562. Thus, it will be assigned to DPU side.
I train yolov4-tiny with darknet, then convert it to caffe

**Comment by charles-str** [comment]
Hi @qianglin-xlnx , I change  leaky-relu alpha value 0.101562, it has same comping log, it seems very strange,
and the input size still  is  not the first layer.
![Screenshot from 2022-03-03 14-50-16](https://user-images.githubusercontent.com/35334263/156512639-a5b08f92-a52e-4f4c-bd2f-4c50fc05ea74.png)

**Comment by wanghong4compiler** [comment]
Hi @charles-str ,
could you share the model file, so that I can reproduce this issue? thank you ~

**Comment by charles-str** [comment]
@qianglin-xlnx @wanghong4compiler  
I change the activation function from  leaky-relu to relu, the input size is correct finally, thanks for yours enthusiasm,
next I will test the performance.

**Comment by charles-str** [comment]
@qianglin-xlnx  @wanghong4compiler 

I met another question, after my yolov4-tiny compiled, although the input size is correct, it has many  graphs. But the demo of yolov4, it has only one graph.

![Screenshot from 2022-03-03 16-27-27](https://user-images.githubusercontent.com/35334263/156527097-8f84c1cd-2249-42c4-b19d-88b2d68642dd.png)
![Screenshot from 2022-03-03 16-30-26](https://user-images.githubusercontent.com/35334263/156527107-f1f55615-2ed0-49f6-9e77-619e2000e7c7.png)

**Comment by wanghong4compiler** [comment]
Hi @charles-str 
Is there any warning on your screen? or could you dump the svg of the model?

**Comment by charles-str** [comment]
> Hi @charles-str Is there any warning on your screen? or could you dump the svg of the model?

 this is the svg of the yolov4-tiny model.
![test](https://user-images.githubusercontent.com/35334263/156528656-5da7275a-f3f0-4b26-a7aa-23bc5be49390.svg)

**Comment by wanghong4compiler** [comment]
Hi @charles-str ,
If the strided_slice is shape-related or is the component of a coarse-grained operation, it would be removed. Otherwise, the strided_slice would be compiled into CPU implementations.
It seems like, in your model, it can't be removed, and assigned to CPU.

**Comment by charles-str** [comment]
> shape-related or is the component of a coarse-grained operation

thanks, what sholud I do?  need I retrain the yolov4-tiny model with replacing strided_slice ? so that it can be supported by dpu.
Do you have any other advise?

**Comment by charles-str** [comment]
> Hi @charles-str , If the strided_slice is shape-related or is the component of a coarse-grained operation, it would be removed. Otherwise, the strided_slice would be compiled into CPU implementations. It seems like, in your model, it can't be removed, and assigned to CPU.

thanks, what sholud I do? need I retrain the yolov4-tiny model with replacing strided_slice ? so that it can be supported by dpu.
Do you have any other advise?

**Comment by wanghong4compiler** [comment]
Hi @charles-str ，
the replacement may be a convenient way to resolve this issue.

**Comment by qianglin-xlnx** [comment]
Hi @charles-str 
It seems that we can close this issue. If you have further problems, please feel free to reopen it. Thank you.

**Comment by vandenplas9a** [comment]
I have exactly the same issue using running

https://github.com/Xilinx/Vitis-AI-Tutorials/blob/1.4/Design_Tutorials/07-yolov4-tutorial/readme.md

selection 3

How do I fixed it?



> Hi @charles-str Your model is based on TF1? If yes, you can specify the input tensor shape with an extra option like --options '{"input_shape": "1,224,224,3"}' when you compile the model.
> 
> And one more thing, from the your comping log, you need to set the alpha value in leaky-relu from 0.1 to 0.101562. Thus, it will be assigned to DPU side.
