### ISSUE TITLE
yolov3 effect  different after compiled

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#704]
I trained a Yolov3 model from https://github.com/ultralytics/yolov3/。This is the effect before compiled，
<img width="1269" alt="微信图片_20220309193422" src="https://user-images.githubusercontent.com/39182088/157434591-b55db547-c8cb-46c1-8499-3cf36aa8d5fb.png">
after compiled model， the effect is
<img width="1336" alt="666" src="https://user-images.githubusercontent.com/39182088/157434862-d422e88b-39a5-47ea-aac5-dfc72ff20056.png">。
<img width="784" alt="res" src="https://user-images.githubusercontent.com/39182088/157435043-50cc29e4-6eac-46c3-bae8-e86ace2637dc.png">
Does anyone know what is the reason or how to troubleshoot?

**Comment by zz002** [comment]
@worldback Which model library are you using to run the model 。

**Comment by worldback** [comment]
@zz002  1.3

<img width="1040" alt="微信图片_20220310154143" src="https://user-images.githubusercontent.com/39182088/157612595-01556ba2-2d8c-4610-9e6b-d19ecca3ac3d.png">

and The model compilation environment is

![图片](https://user-images.githubusercontent.com/39182088/157612658-e89705c8-f799-458c-96ba-eb52a4b632ef.png)

**Comment by zz002** [comment]
@worldback 我 I didn't find the yolo.cpp you reported wrong in the 1.3.2 codebase. I can only tell you about the way to solve this kind of problem.
1.The quantitative model will output a golden, run the dpu subgraph part of the model separately, pass in golden, compare the output,
2.（1.） Check that there is no problem, step by step check the pre- and post-processing of the model to see what is not as expected

**Comment by qianglin-xlnx** [comment]
Hi @worldback 
Is this issue solved?

**Comment by qianglin-xlnx** [comment]
Hi @worldback 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
