### ISSUE TITLE
opencv  cv::VideoCapture error

### ISSUE THREAD

**Issue by charles-str** [Xilinx/Vitis-AI#705]
I run demo test_video_yolov4, I use the official video, the demo can be runned,
but I use my own video, cv::VideoCapture can't read, this is thh error.
![Uploading Screenshot from 2022-03-10 16-34-43.png…]()

**Comment by qianglin-xlnx** [comment]
Hi @charles-str 
I can't see the screenshot you shared. Could you please post your log again?
which platform? official system image? usb camera?

**Comment by charles-str** [comment]
thanks I solved it, I made video by using ffmpeg, maybe ffmpeg can not supported, then I made video by using opencv, now it is solved.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 10, 2022 18:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Xilinx/Vitis-AI] opencv  cv::VideoCapture error (Issue #705)




 
Hi @charles-str
 I can't see the screenshot you shared. Could you please post your log again?
 which platform? official system image? usb camera?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
