### ISSUE TITLE
Can not QAT(quantization aware training) on multiple GPUs

### ISSUE THREAD

**Issue by Ngoc-Nguyen-NIS** [Xilinx/Vitis-AI#706]
Hello Xilinx @all,
I am getting the following issue while doing QAT on multiple GPUs:
![image](https://user-images.githubusercontent.com/43519055/157845969-fd3a0046-cc00-4838-8f66-c5c2cc86ee49.png)
Does anyone know how to solve this problem? Thank you very much!

**Comment by yuwang-xlnx** [comment]
Hi @Ngoc-Nguyen-NIS ,


Can you please share your code snippet of doing QAT ?
It seems that this error occurs before the training starts and is not related to multiple GPUs.
