### ISSUE TITLE
opencv::resize  costs so much time

### ISSUE THREAD

**Issue by charles-str** [Xilinx/Vitis-AI#710]
I  use function  opencv::resize, resize image from 1920 to 608 , but it costs nearly 30 ms.
Is there any way to  reduce time?  Can it run on dpu? 
thanks

**Comment by guohaot-Xlnx** [comment]
Hi，Charles-str
Resize of large images is a real overhead. Unfortunately, we currently have no other way to optimize resize on the development board.
Regards

**Comment by qianglin-xlnx** [comment]
Hi @charles-str 
It can't run on dpu.
You can consider to use H/W acceleration to do resize.  For more details, you can refer to : https://github.com/Xilinx/Vitis-AI/tree/master/Whole-App-Acceleration
