### ISSUE TITLE
nndct_kernels.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#711]
After installing torch (conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=10.2 -c pytorch) in the conda virtual environment, I ran python setup.py install in the vai_q_Pytorch/Pytorch_binding directory, Then run python -c "import pytorch_nndct", and the following error is reported:
![图片](https://user-images.githubusercontent.com/39182088/158372361-efa489a5-905d-4d84-a59f-58b8141e6516.png)

**Comment by niuxjxlnx** [comment]
Hi, @worldback:

Per the warning message, your gcc compiler is not compatible with the torch version you installed, so as to vai_q_pytorch is not compiled successfully. 
What is your OS version and gcc version?

**Comment by worldback** [comment]
@niuxjxlnx  gcc : 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
centos:   CentOS Linux release 7.9.2009 (Core)

This is the output of cat /etc/version:
Linux version 3.10.0-1160.24.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Thu Apr 8 19:51:47 UTC 2021

**Comment by niuxjxlnx** [comment]
@worldback:

From the warning message reported by torch/utils/cpp_extension.py, your gcc is too old for pytorch. Some choices you can try:
1) install gcc in you conda environment. Gcc version >=5.4 works for pytorch 1.9 as I know. The re-compiler vai_q_pytorch.
2) Recomipile pytorch from source code and re-compile vai_q_pytorch
3) Start a Ubuntu(version > 16) docker and works in it.
