### ISSUE TITLE
int 16 quantization 

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#712]
Quantization model in xilinx docker, the same code, int8 quantization is normal, but Int16 execution error, just add bitwidth=16 in pytorch_nndct.apis.torch_quantizer, and the following error is reported:
![图片](https://user-images.githubusercontent.com/39182088/158373499-bd357e03-2e42-411a-8a66-912be860a543.png)
Does it not support Int16 quantization?

**Comment by niuxjxlnx** [comment]
Int16 quantization is not supported officially for CNN models.

**Comment by worldback** [comment]
@niuxjxlnx thanks
