### ISSUE TITLE
Zynq 7020/7030 support

### ISSUE THREAD

**Issue by rbcarlos** [Xilinx/Vitis-AI#715]
Hello, 

are there any resources available, which show how to integrate DPU on the ZYNQ 7020/7030 devices and how to train a custom model to target these?

**Comment by qianglin-xlnx** [comment]
hi @rbcarlos 
So far as I know, Vitis-AI officially does not support ZYNQ devices.

**Comment by rbcarlos** [comment]
Hi @qianglin-xlnx, 
Not even the zc706, I can see that there is the Vitis embedded base platform available for that device. Is that not suitable for use with Vitis-AI?

**Comment by qianglin-xlnx** [comment]
Hi @rbcarlos 
Sorry. We do not test Vitis-AI on ZC706.
