### ISSUE TITLE
Error response from daemon: No such image: xilinx/vitis-ai-gpu:2.0.0.1103

### ISSUE THREAD

**Issue by siniGAL** [Xilinx/Vitis-AI#716]
I have some problem:
```bash
make[2]: Leaving directory '/tmp/protobuf-3.4.0/src'
Makefile:1488: recipe for target 'all-recursive' failed  
make[1]: Leaving directory '/tmp/protobuf-3.4.0'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Makefile:1395: recipe for target 'all' failed
The command '/bin/bash -c cd /tmp; wget --progress=dot:mega https://codeload.github.com/google/protobuf/zip/v3.4.0     && unzip v3.4.0     && cd protobuf-3.4.0     && ./autogen.sh     && ./configure     && make -j     && make install     && ldconfig     && rm -fr /tmp/*' returned a non-zero code: 2  
Error response from daemon: No such image: xilinx/vitis-ai-gpu:2.0.0.1103 
```
[report.txt](https://github.com/Xilinx/Vitis-AI/files/8282948/report.txt)

In the log:
```bash
g++: internal compiler error: Killed (program cc1plus)
```
**dmesg** command:
```bash
[ 2505.556239] Out of memory: Kill process 12750 (cc1plus) score 8 or sacrifice child
[ 2505.556242] Killed process 12750 (cc1plus), UID 0, total-vm:191864kB, anon-rss:139056kB, file-rss:4kB, shmem-rss:0kB
```
My machine had 16GB RAM. After I added another 16 GB of RAM, it solved my problem.

_Originally posted by @siniGAL in https://github.com/Xilinx/Vitis-AI/issues/607#issuecomment-1070518836_

**Comment by Werterror** [comment]
I highly doubt it was RAM issu
![Screenshot from 2022-08-09 09-38-41](https://user-images.githubusercontent.com/75620421/183592425-e1b28f3d-0855-4ccb-ba0b-32b7cfefdfae.png)
e

**Comment by YuetongFang** [comment]
replace the "`make -j`" with "`make -j$(nproc)`", can solve the problem.

**Comment by janifer112x** [comment]
Hi @YuetongFang,
Thanks for your information, we will update the DockerFile accordingly.
