### ISSUE TITLE
About the hard sigmoid in cpu

### ISSUE THREAD

**Issue by white0dew** [Xilinx/Vitis-AI#720]
The moileNetV3 has op names hard-sigmoid，and the op is only supported in VCK190
but my hardware is kv260。
now i want to know if i deploy the hardsigmoid in cpu， the inference latency will increace how much？？ms？

**Comment by zz002** [comment]
Tested a hard-sigmoid-fix that we support, and the calculation takes 498ms for a data size of 123904

**Comment by Ace-cream** [comment]
> 

Hello, could you please send your test code to me so that I can test my data? Thanks a lot!

**Comment by Ace-cream** [comment]
> Tested a hard-sigmoid-fix that we support, and the calculation takes 498ms for a data size of 123904

Hello, could you please send your test code to me so that I can test my data? Thanks a lot!

**Comment by zz002** [comment]
https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Library/cpu_task/ops/hard-sigmoid-fix/hard-sigmoid-fix.cpp#L48
The function in the link above is the main code you can use to test your data
