### ISSUE TITLE
Missing the 'video_input.webm' file in vitis_ai_library_r2.0.x_video.tar.gz tarball

### ISSUE THREAD

**Issue by lucasbrasilino** [Xilinx/Vitis-AI#722]
Hello,
I'm starting to explore Vitis AI so doing the basic examples. Following directions in the [Running AI Library Examples](https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Library#running-vitis-ai-library-examples) I've noticed the `video_input.webm` file, used in the second example, is not in the `vitis_ai_library_r2.0.x_video.tar.gz` tarball.

Is the video file available somewhere ? Ideal scenario would be updating the tarball.

Thanks.

**Comment by qianglin-xlnx** [comment]
Hi @lucasbrasilino 
Due to the license issue, there is no 'video_input.webm' file in vitis_ai_library_r2.0.x_video.tar.gz package. Users need to prepare 'video_input.webm' file by themselves. 
Simply, you can also directly use the USB camera as input.
