### ISSUE TITLE
the problem of YOLOv5 compilation 

### ISSUE THREAD

**Issue by XiongDa0001** [Xilinx/Vitis-AI#724]
When I use vai_c_tensorflow I encounter the following error：
![image](https://user-images.githubusercontent.com/71107056/159654264-c5e6495c-acbf-4484-b29f-5248db5cffa3.png)
The docker environment is Vitis-AI 2.0
vai_q_tensorflow can be executed successfully
I wonder how this problem should be solved?

**Comment by zhenzhen-Xilinx** [comment]
Can you share your float model and quantized model so we can analyze the problem further. Thank you.

**Comment by XiongDa0001** [comment]
> Thank you for your reply, my float model, frozen model and quantized model are all in my google drive.
https://drive.google.com/drive/folders/1PisOoT3rBbX2XAJVwosGW0akKk87oLrx?usp=sharing

**Comment by zhenzhen-Xilinx** [comment]
Hi @XiongDa0001， Based on the model you provided, I reproduced the problem below. The solution is that the shape of the input can be less than 1.

![Capture](https://user-images.githubusercontent.com/101087234/160080495-8352ce66-b926-4b23-bf67-a9ed1a64c4b4.PNG)


Because the problem I reproduced is not the same as what you asked. Can you offered the float and quantized model again. Thanks.

**Comment by XiongDa0001** [comment]
> Hi @XiongDa0001， Based on the model you provided, I reproduced the problem below. The solution is that the shape of the input can be less than 1.
> 
> ![Capture](https://user-images.githubusercontent.com/101087234/160080495-8352ce66-b926-4b23-bf67-a9ed1a64c4b4.PNG)
> 
> Because the problem I reproduced is not the same as what you asked. Can you offered the float and quantized model again. Thanks.

My float and quantized model in google dive.
https://drive.google.com/drive/folders/1PisOoT3rBbX2XAJVwosGW0akKk87oLrx?usp=sharing

**Comment by XiongDa0001** [comment]
> Hi @XiongDa0001， Based on the model you provided, I reproduced the problem below. The solution is that the shape of the input can be less than 1.
> 
> ![Capture](https://user-images.githubusercontent.com/101087234/160080495-8352ce66-b926-4b23-bf67-a9ed1a64c4b4.PNG)
> 
> Because the problem I reproduced is not the same as what you asked. Can you offered the float and quantized model again. Thanks.

The problem you have encounterd was not define the command{--options '{"input_shape": "1,416,416,3"}'}
![image](https://user-images.githubusercontent.com/71107056/160115244-58fdbaf1-ba1b-4d4a-8d7a-970716050346.png)

**Comment by zhenzhen-Xilinx** [comment]
hi @XiongDa0001 ,Sorry for late reply. The model contains tf.strided_slice. Now we only supports the case where the tf.strided_slices parameter ellipsis_mask = 0. However in this model the parameter ellipsis_mask = 1. tf.strided_slice belongs to the preprocessing part of the model. Could you removes the preprocessing
?
<img width="450" alt="2" src="https://user-images.githubusercontent.com/101087234/161371708-e2be104e-1298-40e4-b165-77d8fa5799cf.PNG">

**Comment by XiongDa0001** [comment]
> hi @XiongDa0001 ,Sorry for late reply. The model contains tf.strided_slice. Now we only supports the case where the tf.strided_slices parameter ellipsis_mask = 0. However in this model the parameter ellipsis_mask = 1. tf.strided_slice belongs to the preprocessing part of the model. Could you removes the preprocessing ? <img alt="2" width="450" src="https://user-images.githubusercontent.com/101087234/161371708-e2be104e-1298-40e4-b165-77d8fa5799cf.PNG">

Thank you very much, I'll remove this it.

**Comment by zhenzhen-Xilinx** [comment]
hi @XiongDa0001 , If you still have any questions, please feel free to reopen it. Thank you very much.
