### ISSUE TITLE
Whether the quantified compiled model in Vitis AI V1.4 can be used in Vitis AI V1.3

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#741]
Whether the quantified and compiled model in Vitis AI V1.4 can be used in Vitis AI V1.3 ?

**Comment by xihuazhanghui** [comment]
The V1.3  you mentioned is the V1.3.0 or V1.3.1, V1.3.2 ...?

**Comment by worldback** [comment]
@xihuazhanghui V1.3.2
