### ISSUE TITLE
Using DPU-TRD Vivado for zcu104 to reconfigure the hardware design 

### ISSUE THREAD

**Issue by Afef00** [Xilinx/Vitis-AI#746]
I am working on DPU-PYNQ (PYNQ version 2.6) on ZCU104 board.

I wanted to use vivado flow to reconfigure the hardware design as I wanted to add some other IPs. However only ZCU102 is provided in the DPU-TRD for vivado flow. Is there  any tutorials on DPU with ZCU104 using vivado. 

Also as I am working on DPU-PYNQ which version of DPU and vivado should I use?

I am using vivado 2019.2.

Best regards

**Comment by davidxudong** [comment]
@Afef00 
Hi
Yes, only ZCU102 TRD is provided, if you want to use ZCU104, please refer to ZCU102 TRD.
Thanks
