### ISSUE TITLE
typo in page https://github.com/Xilinx/Vitis-AI/tree/master/dsa/DPU-TRD

### ISSUE THREAD

**Issue by giovanniguasti** [Xilinx/Vitis-AI#747]
**Connolution** Architecture

**Comment by qianglin-xlnx** [comment]
Hi @giovanniguasti 
Thanks for your feedback. We will fix it.

**Comment by qianglin-xlnx** [comment]
Hi @giovanniguasti 
Fixed and updated. Thank you.
