### ISSUE TITLE
Compiling model in v1.3.2 environment prompts not enough bank space

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#751]
![图片](https://user-images.githubusercontent.com/39182088/162377286-c245d25d-539f-4b46-b8e6-402673dad87d.png)

**Comment by wanghong4compiler** [comment]
Hi @worldback ,
it seems like the compilation is complete, just the process is rough and encountered problems.

**Comment by worldback** [comment]
@wanghong4compiler Is there any solution please?

**Comment by wanghong4compiler** [comment]
Hi @worldback ，
I think there is nothing need to do, the compilation is finished, you already get the compiled model.
