### ISSUE TITLE
Stale link for "Setting Up the Evaluation Board"

### ISSUE THREAD

**Issue by louiev-xlnx** [Xilinx/Vitis-AI#754]
On https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc/VART, the link to "[Setting Up the Evaluation Board](https://www.xilinx.com/html_docs/vitis_ai/2_0/installation.html#ariaid-title8)" is stale.

**Comment by qianglin-xlnx** [comment]
Hi @louiev-xlnx 
Thank you for your feedback. We will fix it.
Before we fix it, you can use the following correct link. Thank you.
https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Setting-Up-the-Evaluation-Board

**Comment by qianglin-xlnx** [comment]
Hi @louiev-xlnx 
Fixed and updated. Thank you.
