### ISSUE TITLE
How to disable HPC hardware cache-coherency in Vitis flow?

### ISSUE THREAD

**Issue by jx991220** [Xilinx/Vitis-AI#767]
In my experiments, I found that the latency of the HPC interface was much higher than that of HP interface. So i want to disable HPC hardware cache-coherency.
In the readme file there is a sentence:
“When HPC0 or HPC1 port is used to connect DPU, we advise platform disable HPC hardware cache-coherency, which could reduce DPU latency on HPC port. label the HPC ports with the type S_AXI_HP, instead of S_AXI_HPC in xsa.tcl file in your platform.“
But i cannot exactly find the .tcl file. Can anyone help me? How to diable it?

**Comment by jiaz-xlnx** [comment]
Hi @jx991220 
if you generate the platform form the following link
[https://github.com/Xilinx/Vitis_Embedded_Platform_Source/blob/2021.2/Xilinx_Official_Platforms/xilinx_zcu102_base/hw/xsa_scripts/pfm_decls.tcl](url)
Please check the line 20. modify the sentence like below and try generate the platform again.
set_property PFM.AXI_PORT {M_AXI_HPM1_FPD {memport "M_AXI_GP"} S_AXI_HPC0_FPD {memport "S_AXI_HP" sptag "HPC0" memory "ps_e HPC0_DDR_LOW"}  S_AXI_HPC1_FPD {memport "S_AXI_HP" sptag "HPC1" memory "ps_e HPC1_DDR_LOW"}  S_AXI_HP0_FPD {memport "S_AXI_HP" sptag "HP0" memory "ps_e HP0_DDR_LOW"}  S_AXI_HP1_FPD {memport "S_AXI_HP" sptag "HP1" memory "ps_e HP1_DDR_LOW"}  S_AXI_HP2_FPD {memport "S_AXI_HP" sptag "HP2" memory "ps_e HP2_DDR_LOW"}} [get_bd_cells /ps_e]

**Comment by qianglin-xlnx** [comment]
Hi @jx991220 
Has this issue been solved?

**Comment by qianglin-xlnx** [comment]
Hi @jx991220 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
