### ISSUE TITLE
csh or bash shell?

### ISSUE THREAD

**Issue by giovanniguasti** [Xilinx/Vitis-AI#771]
https://github.com/Xilinx/Vitis-AI/tree/master/dsa/XVDPU-TRD/README.md

in the same .md instruction page we first require the usage of **csh**, then to set the terminal to **bash** shell

**Comment by xlinyg** [comment]
Hi, @giovanniguasti 
Scripts for compiling DPU's AIE are designed as "*.csh", so **csh** is required.
But just need installing **csh** on your server, it will be called automatically.
You just need to run the XVDPU-TRD in the bash shell.

**Comment by qianglin-xlnx** [comment]
Hi @giovanniguasti 
Did @xlinyg 's answer address your question? or do you have other questions?
https://github.com/Xilinx/Vitis-AI/issues/771#issuecomment-1118103562

**Comment by giovanniguasti** [comment]
hi @qianglin-xlnx  and @xlinyg, 
thanks for the answer, the question is answered
