### ISSUE TITLE
Weird Subgraph for Flatten Layer

### ISSUE THREAD

**Issue by HenningCode** [Xilinx/Vitis-AI#774]
Hello,

I am trying to run some small Models on the DPU and I wanted to look at the Subgraphs, but the Flatten Layers seems to look a bit weird. 

This is the Model I am using: 
```
def create_cnn_small(input_shape,output_shape):
    x = x_in = Input(input_shape, name='input_1_m')
    x = Conv2D(16,(3,3),(2,2),name='conv2d_1_m')(x)
    x = Activation("relu", name='act_1_m')(x)
    x = Conv2D(32,(3,3),(2,2),name='conv2d_2_m')(x)
    x = Activation("relu", name='act_2_m')(x)
    x = Flatten(name='flatten_1_m')(x)
    x = Dense(output_shape,name='dense_1_m')(x)
    x = Activation("softmax", name='act_3_m')(x) 
    
    model = Model(inputs=[x_in], outputs=[x])

    return model
```

This is the Subgraph with `xdputil` 
![test](https://user-images.githubusercontent.com/57907680/165341709-b9a82bd2-ff10-45ac-b820-81d429db1229.png)

and this with Netron: 
![cnn_small_netron](https://user-images.githubusercontent.com/57907680/165341871-45691dc2-9ee2-40a5-8c30-4b3f9a821c5e.png)
 
This Model works, but I do want to understand why the Subgraph in Netron adds another Conv2d Layer and is reshaping twice? It seems like Dense Layers are converted to Conv2d Layers. Why is that?

Greetings

**Comment by wanghong4compiler** [comment]
Hi @HenningCode ,
Dense layers would be converted to Matmul layers, Matmul layers would be converted to Conv2d layers because it's a conv like operation.
The first one is added when transfer Matmul to Conv2d in order to fit hardware, and the second one is added to recover the dimension of the tensor for softmax.
The added two reshape operators do not drop performance, because they don't generate instructions actually.

**Comment by qianglin-xlnx** [comment]
Hi @HenningCode 
Is this issue solved?

**Comment by qianglin-xlnx** [comment]
Hi @HenningCode 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
