### ISSUE TITLE
Vitis-AI quantizer

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#776]
If we are running our own model with data set of our own do we have to write pre-processing script input_fn on our own? Is the pre-processing script same for all the frameworks like pytorch ,caffee and tensorflow? Do we  resize all the inputs to 224x224x3 before giving to pre-processing script or it is done by pre-processing script itself

**Comment by AfifaIshtiaq** [comment]
I wrote the preprossing script and I had the following error while quantizing 
![image](https://user-images.githubusercontent.com/68226162/166916001-aedd9b60-e4c3-4096-ba27-df646379d3b1.png)

**Comment by xieyi4650** [comment]
Hi @AfifaIshtiaq 
1. pre-processing is the same as float model pre-processing when running inference.
2. can you upload full error log?

**Comment by renjiangyong** [comment]
Hi @AfifaIshtiaq , Does issue resolved?  the issue is existed for a long time , if you still have problem, you can reopen it .
