### ISSUE TITLE
docker_build_gpu fails because of NVIDA pub key

### ISSUE THREAD

**Issue by ydajwz123** [Xilinx/Vitis-AI#782]
I just share method to continue build for someone encountering this problem.
Some command could be added to GPU Dockerfile. Such as 
```
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
```

**Comment by jzymessi** [comment]
I added the above command to the vitis-ai-gpu.Dockerfile file according to your method, and the following problem occurred. How to solve it, thank you.
![image](https://user-images.githubusercontent.com/51226649/167376649-d51c9f53-a9e0-4d8b-841b-a61d6d2bd40a.png)

**Comment by ydajwz123** [comment]
> I added the above command to the vitis-ai-gpu.Dockerfile file according to your method, and the following problem occurred. How to solve it, thank you. ![image](https://user-images.githubusercontent.com/51226649/167376649-d51c9f53-a9e0-4d8b-841b-a61d6d2bd40a.png)
Do you build GPU docker successfully? I did some changes such as following lines.
```shell
  29 RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
  30     && sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list \
  31     && sed -i s/security.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list \
```
However, it still doesn't work. You may find new issue in #739 .

**Comment by janifer112x** [comment]
Hi @ydajwz123,
as we have release Vitis AI 2.5 this June, Could you please try with newer version?

**Comment by janifer112x** [comment]
closed it with fix in master branch
