### ISSUE TITLE
deploy model takes dicts input

### ISSUE THREAD

**Issue by chulongc** [Xilinx/Vitis-AI#784]
my model take 5 tensors as input. is there any example / tutorial showing how to handle this case?

**Comment by zz002** [comment]
hi @chulongc 
[Here ](https://github.com/Xilinx/Vitis-AI/blob/master/tools/Vitis-AI-Library/RGBDsegmentation/src/RGBDsegmentation_imp.cpp#L111)is an example of multiple inputs. We need to set the data for each input tensor, you can use the tensor name as a key to determine which tensor is currently set.
