### ISSUE TITLE
quantization fast fine tuning

### ISSUE THREAD

**Issue by worldback** [Xilinx/Vitis-AI#787]
![图片](https://user-images.githubusercontent.com/39182088/167134022-80549f9c-480f-4717-98f6-be0bc9c9c4dc.png)
Whether loss_fn is required in the quantizer.fast_finetune function ？

Evaluate which forward function to use in fast_finetune if, for some reason, I changed the code so that the training forward function was different from the DPU forward function.

![图片](https://user-images.githubusercontent.com/39182088/167136854-90e6df1e-ecd8-465a-881f-586e3dca272e.png)
As shown, I commented out this code in Yolov3。

**Comment by niuxjxlnx** [comment]
@worldback :

Fast finetune does not need loss_fn. 
Here the tuple (quant_model, ft_loader, loss_fn) is just the arguments of function "evaluate". And quantizer will not catch the data of  loss_fn and identify it.
