### ISSUE TITLE
Failed to quantify two models simultaneously

### ISSUE THREAD

**Issue by JackzhangLOVEcode** [Xilinx/Vitis-AI#793]
I want to train two models for encoder and decoder, so I did an experiment that trained two models and quantified them simultaneously, here is my code:
train(success)
<img width="458" alt="train" src="https://user-images.githubusercontent.com/35070703/167388286-901207e9-b5d0-42bb-80ef-f462848b4719.PNG">
quantize(failed)
<img width="448" alt="quantize" src="https://user-images.githubusercontent.com/35070703/167388393-7f16d2c1-3b31-4eb1-b2f2-a0ac08302458.PNG">
error code:
<img width="535" alt="error" src="https://user-images.githubusercontent.com/35070703/167389415-7e1469f4-c620-4485-a857-83c40bc6ffce.PNG">
the question is why first xmodel is CNN2 rather than CNN1? and why can't quantify two models simultaneously?

**Comment by zl200881** [comment]
Two or more models can not be quantized simultaneously. You can do the quantization one by one.
