### ISSUE TITLE
Where to find the list of ONNX layers supported by Vitis-AI?

### ISSUE THREAD

**Issue by cmarabotto** [Xilinx/Vitis-AI#794]
Hi, 

Can you tell me where I can find the updated list of ONNX layers supported by Vitis-AI?

Thank you very much.

**Comment by SuZhan0322** [comment]
You can refer to https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Supported-Operators-and-DPU-Limitations

**Comment by SuZhan0322** [comment]
Hi @cmarabotto ,
Is there any update to this issue?

**Comment by SuZhan0322** [comment]
Hi @cmarabotto ,
Please reopen the issue if you still have other questions. thanks!
