### ISSUE TITLE
Compiler Crashes during openCV build WSL2

### ISSUE THREAD

**Issue by caleb-depotanalytics** [Xilinx/Vitis-AI#795]
While running docker_build_gpu.sh, I got a compilation error.

During the step:
------
executor failed running [/bin/bash -c export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"     && cd /tmp; wget --progress=dot:mega https://github.com/opencv/opencv/archive/3.4.3.tar.gz     && tar -xvf 3.4.3.tar.gz     && cd opencv-3.4.3     && mkdir build     && cd build     && cmake -DBUILD_SHARED_LIBS=ON ..     && make -j     && make install     && ldconfig     && export PATH="${VAI_ROOT}/conda/bin:${VAI_ROOT}/utility:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"     && rm -fr /tmp/*]: exit code: 2

I got the following error:

#15 121.7 [ 86%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_moments.cpp.o
#15 121.7 [ 86%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_pc.cpp.o
#15 121.7 [ 86%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_thresh.cpp.o
#15 121.7 [ 87%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_main.cpp.o
#15 121.8 [ 87%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_watershed.cpp.o
#15 121.8 [ 87%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_smooth_bitexact.cpp.o
#15 121.8 [ 87%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_templmatch.cpp.o
#15 121.8 [ 87%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_resize_bitexact.cpp.o
#15 121.9 [ 87%] Linking CXX executable ../../bin/opencv_test_highgui
#15 122.9 [ 87%] Built target opencv_perf_imgcodecs
#15 129.2 [ 87%] Linking CXX executable ../../bin/opencv_test_flann
#15 131.0 [ 87%] Built target opencv_test_highgui
#15 136.7 [ 87%] Built target opencv_test_flann
#15 169.8 c++: internal compiler error: Killed (program cc1plus)
#15 169.8 Please submit a full bug report,
#15 169.8 with preprocessed source if appropriate.
#15 169.8 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#15 171.2 make[2]: *** [modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/dls.cpp.o] Error 4
#15 171.2 modules/calib3d/CMakeFiles/opencv_calib3d.dir/build.make:171: recipe for target 'modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/dls.cpp.o' failed
#15 171.7 CMakeFiles/Makefile2:5594: recipe for target 'modules/calib3d/CMakeFiles/opencv_calib3d.dir/all' failed
#15 171.7 make[1]: *** [modules/calib3d/CMakeFiles/opencv_calib3d.dir/all] Error 2
#15 171.8 make[1]: *** Waiting for unfinished jobs....
#15 186.9 [ 87%] Built target opencv_dnn

I believe that this was caused by an unhandled thread conflict because the error was at a different line when I built it again:

#15 120.8 [ 87%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin128.fp16.cpp.o
#15 120.8 [ 87%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin256.avx2.cpp.o
#15 120.8 [ 88%] Building CXX object modules/core/CMakeFiles/opencv_test_core.dir/test/test_intrin128.avx.cpp.o
#15 122.1 [ 88%] Built target opencv_perf_imgcodecs
#15 122.8 [ 88%] Linking CXX executable ../../bin/opencv_test_highgui
#15 134.6 [ 88%] Built target opencv_test_highgui
#15 137.4 [ 88%] Linking CXX executable ../../bin/opencv_test_flann
#15 150.8 [ 88%] Built target opencv_test_flann
#15 187.9 c++: internal compiler error: Killed (program cc1plus)
#15 187.9 Please submit a full bug report,
#15 187.9 with preprocessed source if appropriate.
#15 187.9 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#15 188.7 make[2]: *** [modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/dls.cpp.o] Error 4
#15 188.7 modules/calib3d/CMakeFiles/opencv_calib3d.dir/build.make:171: recipe for target 'modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/dls.cpp.o' failed
#15 189.7 CMakeFiles/Makefile2:5594: recipe for target 'modules/calib3d/CMakeFiles/opencv_calib3d.dir/all' failed
#15 189.7 make[1]: *** [modules/calib3d/CMakeFiles/opencv_calib3d.dir/all] Error 2
#15 189.9 make[1]: *** Waiting for unfinished jobs....

I then changed the command to "make -j12" because I have 16 virtual cores. The build then proceeded correctly. Maybe this is something to submit to gcc, but it also may mean that the compiler in the docker image needs to be updated to fix some bug.

I am running the build on a Dell XPS 17 9710 with a processor 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s).

**Comment by janifer112x** [comment]
Hi @caleb-depotanalytics,
Thanks for your detailed information. This build error is due to resource limitation just as your error message. we will look into a better way to address it
