### ISSUE TITLE
Does Vitis-AI support element-wise product between 2 tensors in Pytorch?

### ISSUE THREAD

**Issue by chuong98** [Xilinx/Vitis-AI#796]
Let say, if I have two tensors A,B of dimension [B,C,H,W]. Can I get the product C = A*B, where C[i,j] = A[i,j]*B[i,j] ?
The document does not describe it clearly, and this is a basic operator.

**Comment by wanghong4compiler** [comment]
Hi @chuong98 ，
Which hardware platform are you using?

**Comment by chuong98** [comment]
Hi @wanghong4compiler ,
I am testing 3 devices, Ultra 96, ZCU104 and U250 board. Thank you.

**Comment by wanghong4compiler** [comment]
Hi @chuong98 ,
ZCU 104 supports element-wise product.
