### ISSUE TITLE
Vitis AI library API3

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#798]
how to check if the model has multiple subgraphs?

**Comment by foolmarks** [comment]
The compiler output will tell you how many subgraphs there are.

**Comment by AfifaIshtiaq** [comment]
As reference to my previous submitted issue I'm still not able to quantize the model thereby I guess I can't compile the model

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
Vitis AI library API3 is graph_runner API. You can use this API to deploy any model that compiled successfully by Xilinx Xcompiler, whether it has only one dpu subgraph or multiple subgraph.
