### ISSUE TITLE
Resize Operation

### ISSUE THREAD

**Issue by PedroPDelgado** [Xilinx/Vitis-AI#802]
Hello.

 

I am currently trying to deploy the SqueezeSegV3-21 model to the ZCU104. In the network which is implemented using Pytorch, the following operation

 

`F.interpolate(input_tensor, scale_factor=(1, 0.5), mode='bilinear', align_corners=False)`

 

is mapped to a resize operation to be executed on the CPU. This happens after performing quantized calibration and compiling the model.

 

 

 
![resize](https://user-images.githubusercontent.com/47891513/168810121-e29a25eb-ee2d-4876-b8fe-af3561f0e3f7.jpg)

 

Then, I send the compiled xmodel to the ZCU104 and try to create a graph runner.

 

```
import os
import xir
import vitis_ai_library


def get_runner(xmodel_path):   
    filepath = os.path.dirname(os.path.realpath(__file__))
    xmodel_path = os.path.join(filepath, xmodel_path)
    graph = xir.Graph.deserialize(xmodel_path)
    runner = vitis_ai_library.GraphRunner.create_graph_runner(graph)
    return runner

 
if __name__ == '__main__':
    runner = get_runner('../SSGV321_zcu104.xmodel')

```
When I try to run this script, I get the following error:

```

WARNING: Logging before InitGoogleLogging() is written to STDERR

W0519 08:33:14.755436 20822 tool_function.cpp:188] [UNILOG][WARNING] The operator named Segmentator__Segmentator_Backbone_backbone__SACBlock_enc1__SACBlock_residual_0__8268, type: my_im2col, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)

F0519 08:33:15.794091 20822 op_imp.cpp:106] Check failed: handle != NULL cannot open library! lib=libvart_op_imp_resize.so;error=libvart_op_imp_resize.so: cannot open shared object file: No such file or directory;op=xir::Op{name = Segmentator__Segmentator_Backbone_backbone__input_16, type = resize}

*** Check failure stack trace: ***

Aborted

```

 

When I look into /usr/lib on the ZCU104, the file libvart_op_imp_resize.so is indeed missing.

 

The user guide v2.0 ([Compiling the model > Compiling with an XIR-based Toolchain > Operators Supported by PyTorch](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Operators-Supported-by-PyTorch)) states that interpolate should be mapped to the resize operation so I was surprised not to see it near the other operations in /usr/lib.

 

Am I missing something?

 

 

The image on the ZCU104 is the default image for Vitis-AI 2.0 for the ZCU104 board:

 

- Url: https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-zcu104-dpu-v2021.2-v2.0.0.img.gz

- Filename: xilinx-zcu104-dpu-v2021.2-v2.0.0.img.gz

- Date: May 17, 2022

**Comment by AMDmoore** [comment]
Hi, PedroPDelgado
Resize op may be supported in graph runner in later release.
Please try libvart_op_imp_upsample-fix.so instead.
Do as below:
cd /usr/lib
cp libvart_op_imp_upsample-fix.so libvart_op_imp_resize.so

Thanks
Regards

**Comment by PedroPDelgado** [comment]
Hello.

First of all, thank you for the fast answer.

I did as you said and unfortunately, I am presented with the following error:
```
root@xilinx-zcu104-2021_2:~/SSGV321/app# python3 main.py

/home/root/SSGV321/app/../compiled_model/SSGV321_zcu104.xmodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0525 15:42:12.823194 12269 tool_function.cpp:188] [UNILOG][WARNING] The operator named Segmentator__Segmentator_Backbone_backbone__SACBlock_enc1__SACBlock_residual_0__8268, type: my_im2col, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
F0525 15:42:14.777385 12269 upsample-fix.cpp:52] Check failed: output_w_ % input_w_ == 0 (1024 vs. 0) only support upsample by integer.
*** Check failure stack trace: ***
Aborted

```

Next, I tried some other libraries in /usr/lib. When I tried doing either:
```
cp libvart_op_imp_reshape.so libvart_op_imp_resize.so
```

or

```
 cp libvart_op_imp_reshape-fix.so libvart_op_imp_resize.so
```

The resize error disappears but the process gets a SIGKILL.

```
root@xilinx-zcu104-2021_2:~/SSGV321/app# python3 main.py


/home/root/SSGV321/app/../compiled_model/SSGV321_zcu104.xmodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0525 15:55:09.682384 12349 tool_function.cpp:188] [UNILOG][WARNING] The operator named Segmentator__Segmentator_Backbone_backbone__SACBlock_enc1__SACBlock_residual_0__8268, type: my_im2col, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
Killed
```

When checking kernel logs, I find that SIGKILL is due to "out-of-memory".

```
root@xilinx-zcu104-2021_2:~/SSGV321/app# dmesg -T| grep -E -i -B100 'killed process'

[Fri May 25 15:55:12 2018] [  12349]     0 12349   485938   285871  3899392        0             0 python3
[Fri May 25 15:55:12 2018] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=python3,pid=12349,uid=0
[Fri May 25 15:55:12 2018] Out of memory: Killed process 12349 (python3) total-vm:1943752kB, anon-rss:1142200kB, file-rss:1284kB, shmem-rss:0kB, UID:0 pgtables:3808kB oom_score_adj:0
```

From here, I also tried replacing the `F.interpolate` function with a `nn.Conv2d`. This also led to an 'out-of-memory' SIGKILL.
Since having a convolution results in having more subgraphs on the DPU,  I would prefer to follow this path.

The size of the SSGV321 xmodel I am trying to create a graph runner from is 20MB. As a last experience, I tried the same script with the model yolov3_voc_tf.xmodel from the Vitis-Ai/model-zoo on the zcu104. This model has 61MB and yet it loads with no problem.

Finally, It should be worthy to note that the SSGV321 model I am trying to deploy uses a custom operation that unfortunately occurs 7 times. It is the F.unfold (= im2col) operation from pytorch which was implemented and validated on the ZCU104 using golden results as explained in the user guide ([Deploying and Running the Model > Custom Op Workflow > Pytorch Custom Op Model Example > Compiling the model](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Custom-OP-Registration?tocId=Qgp2CjXE4Jygs5RGVGSKaw)).

**Comment by AMDmoore** [comment]
Hi PedroPDelgado,

Thanks for your response.
The reason why I suggest you to try upsample is that upsample op has the similar attributes and algorithm to resize, but the others don't.
Your error "check failed" results from the parameters' check for upsample op, that means it can't be reused as resize/downsample in release2.0.
So, a new custom op "resize" needs to be developed for your model.
To develop a new custom op, you can refer to https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Custom-OP-Registration?tocId=vNwJMFTssuJQ~WWsO4gV3A
For the algorithm, you can refer to upsample-fix(https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Library/cpu_task/ops/upsample-fix) and remove some checks like CHECK_EQ(output_w_ % input_w_, 0) and CHECK_EQ(N_w_ % 2, 0).
Please pay attention, you don't need to fix the data to int8_t for your CPU subgraph, so please use float type in your codes instead, for example: vart::simple_tensor_buffer_t<float> input, float N_w_.

Thanks
Regards

**Comment by PedroPDelgado** [comment]
Thank you. I think this issue can be closed since your suggestion is to develop a custom operation.
