### ISSUE TITLE
Segmentation fault during quantization with GPU

### ISSUE THREAD

**Issue by DeepTrial** [Xilinx/Vitis-AI#803]
I have a resenet50 implemented by pytorch. When I quantize the model with device cuda, it fails with segmentation fault. However when switching to device cpu, it works. What should i do if i have to quantize with gpu?

![image](https://user-images.githubusercontent.com/36470029/168969864-024561d9-67cc-4881-a040-7c9390d52679.png)

**Comment by DeepTrial** [comment]
Additional Information: Vitis-AI 2.0 with visit-ai-pytorch

**Comment by zl200881** [comment]
Would you please disclose more running information, such as the warnings, errors, as well as command shells?

**Comment by zl200881** [comment]
More information about your working environment?
Such as Ubuntu or windows, gpu or cpu, docker or conda env, graphics card?

**Comment by niuxjxlnx** [comment]
@DeepTrial :

Please confirm GPU can be accessed and its driver works well. 
You can type "nvidia-smi" to check the log.  
A pytorch function "torch.cuda.device_count()" also can check GPU works or not.

**Comment by niuxjxlnx** [comment]
Close since no response for a long time.
