### ISSUE TITLE
Versioned releases of the SDK

### ISSUE THREAD

**Issue by finn-ball** [Xilinx/Vitis-AI#81]
At the moment, you just point to here:
https://www.xilinx.com/bin/public/openDownload?filename=sdk.sh

It would be very useful to have a versioned archive of this sdk.

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
Thank you for your valuable advice.

**Comment by finn-ball** [comment]
Did this get closed because it was resolved?

**Comment by qianglin-xlnx** [comment]
We will add the version number of sdk.sh in the next release. Thank you for your advice again.
