### ISSUE TITLE
VCK190 DPU limitation: Depth-wise convolution

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#813]
While compiling my model I found out that
**depthwise-conv2d** is supported by **DPU** if **dilation** 1,1 **Kernel** 3,3 pad 1,1,1,1 stride 1,1
But  **depthwise-conv2d** is mapped to **CPU** if  **dilation** 3,2 **Kernel** 3,3 pad 0,0,0,0 stride 1,1

I'm confused by the dcoumentation where here they say **depthwise-conv2d** is not supported by DPU https://docs.xilinx.com/r/1.3-English/ug1414-vitis-ai/Supported-OPs-and-DPU-Limitations but from the compiled results I can see some get maped

Also in here they say **depthwise-conv2d** can be  supported by DPU https://docs.xilinx.com/r/1.3-English/ug1414-vitis-ai/Operators-Supported-by-TensorFlow 

Here is the svg graph
![deep_rx_compile](https://user-images.githubusercontent.com/68226162/169838828-bce6a5bc-b217-4247-befe-c0f178cb3fc8.svg)

**Comment by wanghong4compiler** [comment]
Hi @AfifaIshtiaq ，
for now, we only support depthwise conv with dilation_h == dilation_w.

**Comment by AfifaIshtiaq** [comment]
> Hi @AfifaIshtiaq ， for now, we only support depthwise conv with dilation_h == dilation_w.

Thanks, @wanghong4compiler I resolved this issue Can you also let me know the reason behind CPU mapping of the output convolution layer in the upper graph?

![image](https://user-images.githubusercontent.com/68226162/171015395-ab063bf0-78da-4668-b39c-4e61ccbf423c.png)

**Comment by wanghong4compiler** [comment]
Hi @AfifaIshtiaq ,
DPU's data result are all XINT8, the last fix2fload op would transfer the fixed XINT8 result float back, this will keep the whole model equivalent.
