### ISSUE TITLE
Out of memory when deploying model on ZCU104

### ISSUE THREAD

**Issue by PedroPDelgado** [Xilinx/Vitis-AI#814]
Hello.

For some context, I am currently trying to deploy a model (SqueezeSegV3-21) to the ZCU104. My model has 20MB of size. It also contains a custom operation that I developed, `im2col`, that replaces `torch.nn.functional.unfold`. This operation is working well as I have tested it on the ZCU104 using "golden results" as explained in the user guide ([Deploying and Running the Model > Custom Op Workflow > Pytorch Custom Op Model Example > Compiling the model](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Custom-OP-Registration?tocId=Qgp2CjXE4Jygs5RGVGSKaw)). It occurs 7 times in the model.

My problem, however, is when I try to run the following very simple python file which creates a graph runner using my model.

```
import os
import xir
import vitis_ai_library


def get_runner(xmodel_path):   
    filepath = os.path.dirname(os.path.realpath(__file__))
    xmodel_path = os.path.join(filepath, xmodel_path)
    print(xmodel_path)
    graph = xir.Graph.deserialize(xmodel_path)
    runner = vitis_ai_library.GraphRunner.create_graph_runner(graph)
    return runner

 
if __name__ == '__main__':
    runner = get_runner('../SSGV321_zcu104.xmodel')
    print(runner)
```

When I run it, I get the following error:

```
root@xilinx-zcu104-2021_2:~/SSGV321/app# python3 main.py


/home/root/SSGV321/app/../compiled_model/SSGV321_zcu104.xmodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0525 15:55:09.682384 12349 tool_function.cpp:188] [UNILOG][WARNING] The operator named Segmentator__Segmentator_Backbone_backbone__SACBlock_enc1__SACBlock_residual_0__8268, type: my_im2col, is not defined in XIR. XIR creates the definition of this operator automatically. You should specify the shape and the data_type of the output tensor of this operation by set_attr("shape", std::vector<int>) and set_attr("data_type", std::string)
Killed
```

By checking kernel logs, I find that the SIGKILL is due to "out-of-memory".

```
root@xilinx-zcu104-2021_2:~/SSGV321/app# dmesg -T | grep -E -i -B100 'killed process'

(...)
[Fri May 25 15:55:12 2018] [  12349]     0 12349   485938   285871  3899392        0             0 python3
[Fri May 25 15:55:12 2018] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=python3,pid=12349,uid=0
[Fri May 25 15:55:12 2018] Out of memory: Killed process 12349 (python3) total-vm:1943752kB, anon-rss:1142200kB, file-rss:1284kB, shmem-rss:0kB, UID:0 pgtables:3808kB oom_score_adj:0
```

Since I thought that it could have to do with the size of the model, I tried to run the exact same python file with a different model of a bigger size than mine. This model I tried was yolov3_voc_tf.xmodel from the Vitis-Ai/model-zoo which has 61MB. With this yolo model, my simple python file ran without any errors, even though the model size is 3 times bigger.

```
root@xilinx-zcu104-2021_2:~/SSGV321/app# python3 main.py

/home/root/SSGV321/app/yolov3_voc_tf.xmodel
vart::Runner@0xaaaabe2eb2e0
```

What do you think could be the problem?

**Comment by qianglin-xlnx** [comment]
Hi @PedroPDelgado 
You can use xdputil tool to check the details of your model, such as the following command.

xdputil xmodel yolov3_voc_tf.xmodel -l

Or could you share your xmodel?

**Comment by tuanmonkeyy** [comment]
> Increasing the CMA does solve the issue. I tried it on the vck190 board, not the ZCU104. However, 2048MB CMA was not enough and I had to increase it to 4096MB.

Hello , how to increase the CMA on ZCU104? I have the same situation as you
