### ISSUE TITLE
GCP error when buld GPU docker

### ISSUE THREAD

**Issue by Zhijiexu-nuro** [Xilinx/Vitis-AI#816]
Hi,
when I run ./docker_build_gpu.sh, I meet the GCP error.
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
and how to solve it
Thanks,

**Comment by zhzhqian** [comment]
same issue, have no idea what to do

**Comment by janifer112x** [comment]
Hi @zhzhqian，
this issue has been addressed in the latest commit of mater branch, please have a try and let us know if you still have any problem. I will close this issue for now. feel free to reopen it  if you have any concern.
