### ISSUE TITLE
Conv2d output layer DPU limitation: VCK190

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#821]
In the model attached here
[deep_rx_dummy_dilation_rate.zip](https://github.com/Xilinx/Vitis-AI/files/8803813/deep_rx_dummy_dilation_rate.zip)
I can quantize and compile and I get the following output
![image](https://user-images.githubusercontent.com/68226162/171139540-17adc62b-e4f1-4538-8a88-e1e84780edfa.png)

The compiler shows 5 subgraphs and 1  DPU graph although I see that all the model is converted to two graphs i.e., DPU and the output convolution layer to CPU. Here is the SVG graph. why the last node is mapped to the CPU? a
![deeprx_dilation](https://user-images.githubusercontent.com/68226162/171140189-c9e24a83-8025-437a-9a65-eb9d0730c36f.svg)

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
The output of DPU subgraph is int8. So xcompiler will add a fix2float op in the last node. It's in CPU subgraph and it's expected.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/58016351/171800722-f2915894-a55a-4eb4-b93a-b024d525c70f.png">

**Comment by AfifaIshtiaq** [comment]
> Hi @AfifaIshtiaq The output of DPU subgraph is int8. So xcompiler will add a fix2float op in the last node. It's in CPU subgraph and it's expected. <img alt="image" width="474" src="https://user-images.githubusercontent.com/58016351/171800722-f2915894-a55a-4eb4-b93a-b024d525c70f.png">

Yes you're right so Is it fine to calculate the throughput using the output of DPU graph in the application instead of CPU ? or is there any way to avoid this CPU graph

**Comment by wanghong4compiler** [comment]
Hi @AfifaIshtiaq ,
I'm sorry to say the CPU subgraph can not be removed.
The data would be convert from float to INT8 because DPU only supports INT8, but in order to make the output data type of the model is consistent, there should be a CPU subgraph to recover the data type.

**Comment by AfifaIshtiaq** [comment]
> Hi @AfifaIshtiaq ,
> I'm sorry to say the CPU subgraph can not be removed.
> The data would be convert from float to INT8 because DPU only supports INT8, but in order to make the output data type of the model is consistent, there should be a CPU subgraph to recover the data type.

So it means it is fine if I set my prediction buffer to dpu graph output instead of cpu output and ignore this output cpu layer?

**Comment by wanghong4compiler** [comment]
Hi @AfifaIshtiaq ,
the remove operation is not recommended, but if that's that you need, you could give it a try.
