### ISSUE TITLE
Xdputil: Test failed

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#823]
Can you please tell me why the test failed and what can be reasons behind

root@xilinx-vck190-2021_2:~/models# xdputil benchmark deeprx_compiledilation.xmodel  -i -1 1
XAIEFAL: INFO: Resource group Avail is created.
XAIEFAL: INFO: Resource group Static is created.
XAIEFAL: INFO: Resource group Generic is created.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0531 03:26:06.921924  1163 test_dpu_runner_mt.cpp:475] shuffle results for batch...
I0531 03:26:06.922271  1163 performance_test.hpp:73] 0% ...
I0531 03:26:12.922384  1163 performance_test.hpp:76] 10% ...
I0531 03:26:18.922524  1163 performance_test.hpp:76] 20% ...
I0531 03:26:24.922662  1163 performance_test.hpp:76] 30% ...
I0531 03:26:30.922797  1163 performance_test.hpp:76] 40% ...
I0531 03:26:36.922935  1163 performance_test.hpp:76] 50% ...
I0531 03:26:42.923074  1163 performance_test.hpp:76] 60% ...
I0531 03:26:48.923213  1163 performance_test.hpp:76] 70% ...
I0531 03:26:54.923350  1163 performance_test.hpp:76] 80% ...
I0531 03:27:00.923487  1163 performance_test.hpp:76] 90% ...
I0531 03:27:06.923640  1163 performance_test.hpp:76] 100% ...
I0531 03:27:06.923703  1163 performance_test.hpp:79] stop and waiting for all threads terminated....
I0531 03:27:06.927350  1163 performance_test.hpp:85] thread-0 processes 63135 frames
I0531 03:27:06.927377  1163 performance_test.hpp:93] it takes 3656 us for shutdown
I0531 03:27:06.927393  1163 performance_test.hpp:94] FPS= 1052.16 number_of_frames= 63135 time= 60.0051 seconds.
I0531 03:27:06.927428  1163 performance_test.hpp:96] BYEBYE
Test Failed!!!

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
Could you share the xmodel: deeprx_compiledilation.xmodel so that we can further analyze the problem？ Thank you.

**Comment by AfifaIshtiaq** [comment]
> 

[deeprx_compiledilation.zip](https://github.com/Xilinx/Vitis-AI/files/8831970/deeprx_compiledilation.zip)
This is the model attached above

**Comment by AfifaIshtiaq** [comment]
Hi, do you have the solution to this issue?

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
The model you shared is based on DPUCVDX8G_ISA2_C64B5. 
Could you please also share us the quantized model? So that we can compile the model with different arch. Thank you.

**Comment by AfifaIshtiaq** [comment]
> Hi @AfifaIshtiaq The model you shared is based on DPUCVDX8G_ISA2_C64B5. Could you please also share us the quantized model? So that we can compile the model with different arch. Thank you.
Yes Please find the attached file
[quantized_model_dilation_rate.zip](https://github.com/Xilinx/Vitis-AI/files/8860407/quantized_model_dilation_rate.zip)

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
Currently, I don't have the vck190 board with VAI2.0. I test the model on vck190 with VAI2.5 and the test result shows passed, as shown below.
![image](https://user-images.githubusercontent.com/58016351/173005526-f61e0dbf-b2fb-4faa-9feb-ee28408a31bb.png)

**Comment by AfifaIshtiaq** [comment]
> Hi @AfifaIshtiaq Currently, I don't have the vck190 board with VAI2.0. I test the model on vck190 with VAI2.5 and the test result shows passed, as shown below. ![image](https://user-images.githubusercontent.com/58016351/173005526-f61e0dbf-b2fb-4faa-9feb-ee28408a31bb.png)

Thanks, Can you figure out what can be the issue ? Can it is related to V2.0 version. Where can I find VAI2.5

**Comment by qianglin-xlnx** [comment]
hi @AfifaIshtiaq 
VAI2.5 has been released.
Could you please test it again in VAI2.5? Thank you.

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
