### ISSUE TITLE
Pytorch quantize error: cannot import name 'Graph'

### ISSUE THREAD

**Issue by CharlesChen1024** [Xilinx/Vitis-AI#828]
Hi,
When I run "from pytorch_nndct.apis import torch_quantizer, dump_xmodel", I got one warning message.
Warning message:
[VAIQ_WARN]: Can't find xir package in your environment.

Then I quantize the model, I got one error message.
Error message:
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-optimizer_pytorch/lib/python3.6/site-packages/nndct_shared/compile/xgraph.py", line 20, in <module>
    from xir import Graph
ImportError: cannot import name 'Graph'

How to solve this problem?
Thanks

**Comment by niuxjxlnx** [comment]
Hi, @CharlesChen1024:

Which version of VAI are you using?

**Comment by niuxjxlnx** [comment]
Hi, @CharlesChen1024 :

I notice you are using optimizer conda env:
/opt/vitis_ai/conda/envs/**vitis-ai-optimizer_pytorch**.

Please do quantization in conda env **vitis-ai-pytorch**.

**Comment by CharlesChen1024** [comment]
Hi, @niuxjxlnx : 
Thanks for your reply. I successfully run the same code in conda env vitis-ai-pytorch.
