### ISSUE TITLE
Release a portable toolchain with no install

### ISSUE THREAD

**Issue by finn-ball** [Xilinx/Vitis-AI#83]
At the moment, you must install the toolchain and source an environment variable which sets up some filepaths which are predermined from the original system you installed the `sdk` into.

It would be useful to release a tarball of the sysroot which doesn't require an install and instead leaves it to the user to determine how they interact with the SDK. For example, they could decide to `chroot` into the sysroot. 

It may also be useful to be able to copy the cross compilers to other directories on other systems. They seem hardcoded from when you install them and must remain in the same directory structure as the install.

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
Thank you for your advice. It's related to sysroot which is shipped in SDK form. It is a standard form that yocto provides.
