### ISSUE TITLE
Keyboard and mouse input ZCU102

### ISSUE THREAD

**Issue by Werterror** [Xilinx/Vitis-AI#835]
Hi all,

According to Vitis-AI UG, after flashing the OS Image to the SD Card I should be able to plugin mouse and keyboard and use Linux. However when I connect either mouse or keyboard board doesnt read any inputs. Monitor connected via DP works fine. Iam using usb-b to usb adapter.

**Comment by qianglin-xlnx** [comment]
Hi @Werterror 
You can check the jumpers around USB connecter. Make sure they are set up correctly. You can refer to the following.
Also, you can check the USB connecter and USB converter. 

<img width="892" alt="image" src="https://user-images.githubusercontent.com/58016351/173039911-36ae1007-d4f7-4343-acf8-25e3c4a27f1e.png">

**Comment by Werterror** [comment]
Hi @qianglin-xlnx 
Good guess, I was missing J7 Jumper - USB ULPI Device or Host select.
Thank you for help.
