### ISSUE TITLE
No image while running Vitis-ai resnet50 example on Ultrascale+ ZCU102, SSH

### ISSUE THREAD

**Issue by Werterror** [Xilinx/Vitis-AI#836]
Hi All,

I went through UG on Vitis-AI:

https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Vitis-AI-Examples

and everything worked fine but I received no image and warning: "Gtk-WARNING **: 21:04:27.766: cannot open display:"

I am using PuTTy SSH with X11 forwarding. I already tried export DISPLAY=:0.0, but there was no succes.

**Comment by qianglin-xlnx** [comment]
@Werterror 
It's probably a setup issue of ssh tool or host system.
Maybe you can try MobaXterm tool.

**Comment by tianfang-fafafa** [comment]
hi @Werterror , how to reproduce your problem? Could you please share your step?

**Comment by tianfang-fafafa** [comment]
hi @Werterror , I have never used step1-step5.  I directly burn SD Card image via Etcher. Then run resnet50 successfully:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/80665242/173315578-838e35cd-45bf-4a96-84ef-0422a6564e79.png">

**Comment by Werterror** [comment]
@tianfang-fafafa  probably those steps are unnecessary, I was following instruction from https://github.com/Xilinx/Vitis-AI Readme file and as I can see you are running in to same issue as I was recently "Gtk-WARNING **: 21:04:27.766: cannot open display:" which was caused in my case by not using MobaXterm (lack of X Windows Server).
After opening SSH session in MobaXterm instead of PuTTy, error that you provided screenshot of change to:
![image](https://user-images.githubusercontent.com/75620421/173317948-d3a76ccb-51b7-493f-9494-ff6ead7410dc.png)

**Comment by tianfang-fafafa** [comment]
hi @Werterror , please try to logon by running "ssh root@<board IP>  -XY":
