### ISSUE TITLE
Choose what to install with the `sdk.sh`

### ISSUE THREAD

**Issue by finn-ball** [Xilinx/Vitis-AI#84]
At the moment it installs sysroots for both `aarch64` and `x86_64`. It may be useful to allow the user to choose to only install what they need. For example, just installing the cross compiler.

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
It's related to sysroot which is shipped in SDK form. It is a standard form that yocto provides.

**Comment by finn-ball** [comment]
Did this get closed because it was resolved?

**Comment by qianglin-xlnx** [comment]
It's a standard form that yocto provides. Both the files under aarch64 and x86_64 are used for crossing compiling. So It's not possible to choose what to install with the 'sdk.sh'. 
Thank you for your advice again.

**Comment by finn-ball** [comment]
That's unusual. When I cross compile, I generally just need a cross compiler, along with the libraries in the `aarch64` folder. Is this not the case for Xilinx?

**Comment by qianglin-xlnx** [comment]
The cross compiler tools, such as aarch64-xilinx-linux-g++ and aarch64-xilinx-linux-gcc, are under 
./x86_64-petalinux-linux/usr/bin/aarch64-xilinx-linux/
They can be run on X86 host.  They are not under aarch64 which makes you confused I guess.
![image](https://user-images.githubusercontent.com/58016351/83117835-28838000-a100-11ea-9839-9a49de686c92.png)
