### ISSUE TITLE
The release file of  VAI 2.5 is still for VAI 2.0

### ISSUE THREAD

**Issue by hill19850213** [Xilinx/Vitis-AI#853]
I unzipped VAI 2.5 file and found the contents were still for vai 2.0. Is the file incorrect?

**Comment by dsp-avt** [comment]
@hill19850213 - you're talking about the Vitis-AI/docker/dockerfiles/VERSION.txt file correct?

The file has 2.0.0.1103, but I think it should actually be 2.5.0.1260

**Comment by hill19850213** [comment]
Here is screenshot for unzipped file of Vitis-AI-2.5.zip
![Screenshot 2022-06-16 074324 PNG](https://user-images.githubusercontent.com/40138266/173960351-8b6c02f3-2e8f-4d64-a2de-387ee0169049.jpg)
This contents are same as [Vitis-AI-2.0](https://github.com/Xilinx/Vitis-AI/tree/996459fb96cb077ed2f7e789d515893b1cccbc95). Actually, the contents are should be same as  [Vitis-AI-2.5](https://github.com/Xilinx/Vitis-AI)

**Comment by qianglin-xlnx** [comment]
Hi @hill19850213 
Sorry about the late reply. It's fixed. Could you please try it again, thank you.
