### ISSUE TITLE
Remove infinite `gphoto2` symbolic link loop

### ISSUE THREAD

**Issue by finn-ball** [Xilinx/Vitis-AI#86]
If you run:

```
ls -la /opt/petalinux/2019.2/sysroots/aarch64-xilinx-linux/usr/include/gphoto2/
```
You'll see there is an infinite symbolic loop for `gphoto2`:
```
gphoto2 -> .
```

Can you remove this?

**Comment by finn-ball** [comment]
Hi, was this resolved?

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
It's introduced by OpenCV and there is no need to remove it. I guess it has it's own special use, such as compatible different version.
