### ISSUE TITLE
VCK190 DPU TRD 2022.1 - Wrong SRC_URI?

### ISSUE THREAD

**Issue by ksstms** [Xilinx/Vitis-AI#861]
When building the new (2022.1) DPUCVDX8G example, I get the following PetaLinux messages. Of course the build fails afterwards, as it can't access these URLs. Are these your internal repos?

```
WARNING: vart-2.5-r0 do_fetch: Failed to fetch URL git://gitenterprise.xilinx.com/aisw/vart;protocol=https;branch=dev, attempting MIRRORS if available
WARNING: vitis-ai-library-2.5-r0 do_fetch: Failed to fetch URL git://gitenterprise.xilinx.com/aisw/Vitis-AI-Library;protocol=https;branch=dev, attempting MIRRORS if available
WARNING: unilog-2.5-r0 do_fetch: Failed to fetch URL git://gitenterprise.xilinx.com/aisw/unilog;protocol=https;branch=dev, attempting MIRRORS if available
WARNING: target-factory-2.5-r0 do_fetch: Failed to fetch URL git://gitenterprise.xilinx.com/aisw/target_factory;protocol=https;branch=dev, attempting MIRRORS if available
WARNING: xir-2.5-r0 do_fetch: Failed to fetch URL git://gitenterprise.xilinx.com/aisw/xir;protocol=https;branch=dev, attempting MIRRORS if available
```

Another quick question: are the TRDs available somewhere with version control? Up until this version, they were here in this repo, but now it's just a tar.gz download. That makes it so much more complicated to see if there was an update.

**Comment by ksstms** [comment]
Apparently this got fixed, there's a new tar.gz available.
My second question still stands though.

**Comment by qianglin-xlnx** [comment]
Hi @ksstms 
Thank you for your feedback.
So far as I know, version control of TRD will be introduced in the next release.
