### ISSUE TITLE
A model verification tool ?

### ISSUE THREAD

**Issue by mehdi-nait** [Xilinx/Vitis-AI#866]
It would be really useful if there's a verification tool for custom models, to show unsupported operations and layers that could potentially crash the quantization process. I've been using a custom pytorch YoloV4 model with VAI, I spent a lot of time debugging the quantization with error messages that were little to no help.

**Comment by qianglin-xlnx** [comment]
Hi @mehdi-nait 
Thank you for your advice.  
@andyluo7

**Comment by qianglin-xlnx** [comment]
HI @mehdi-nait 
In VAI2.5 Model Inspector is introduced. It can inspects a float model and shows partition results
<img width="664" alt="image" src="https://user-images.githubusercontent.com/58016351/175066842-516c1a5d-d72f-40f8-8bba-86068fea1331.png">

For tensorflow2 model, you can refer to: https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Inspecting-the-Float-Model
For Pytorch model, you can refer to: https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Inspect-Float-Model-Before-Quantization
