### ISSUE TITLE
Error about large model quantization

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#867]
When I quantified a 32GB model, I encountered the following error message
![image](https://user-images.githubusercontent.com/51226649/174509732-978b189b-d0c9-4972-939a-f266ffad41d0.png)
Is the model too big for the maximum limit?

**Comment by niuxjxlnx** [comment]
@jzymessi ：

As the message shows, protobuf, which is dependency of XIR, does not support graph larger than 2GB. 
You can split the graph to some smaller sub-graphs by partial quantization OP(quantStub/dequantStub pairs).

**Comment by jzymessi** [comment]
@niuxjxlnx :
Thanks for your reply, by the way,If xmodel size is larger than VCK5000 ddr capacity，xmodel can be splited into multiple xmodel at compile time?
Thanks.

**Comment by wanghong4compiler** [comment]
Hi @jzymessi ,
If the required DDR size is larger than hardware's, compiler would report fail and abort, it can't split the model into multiple parts.
