### ISSUE TITLE
Vitis-ai cpu docker error

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#872]
I followed the steps in Readme to pull the Dockers and encountered the following problems :
1. I  use cmd  `docker pull xilinx/vitis-ai-cpu:latest`  pull docker, when i enter docker found this version is 1.4.1.978
2. I use cmd `././docker_build_cpu.sh` met the error 
![image](https://user-images.githubusercontent.com/51226649/174706099-142ff4ae-7dcf-46ff-930c-70712acc36bd.png)

**Comment by hanxue** [comment]
Hi @jzymessi 

Looking at the vitis-ai-cpu Docker tags at https://hub.docker.com/r/xilinx/vitis-ai-cpu/tags,  `docker pull xilinx/vitis-ai-cpu:latest` will get you the latest 2.5.0.1260 Vitis AI v2.5 Docker. You might want to try `docker rmi xilinx/vitis-ai-cpu:latest` to delete the existing Docker image and pull again, 

Indeed `docker_build_cpu.sh` uses the outdated file https://github.com/Xilinx/Vitis-AI/blob/master/docker/dockerfiles/VERSION.txt

They will be updated later today.

**Comment by hanxue** [comment]
The docker version file has been updated to 2.5.0.1260. Please can you give it a try after `git pull` your local local Vitis AI repo?

**Comment by qianglin-xlnx** [comment]
Hi @jzymessi 
Is this issue solved?

**Comment by jzymessi** [comment]
@qianglin-xlnx 
   Tanks,this issue is solved.
