### ISSUE TITLE
VART readme.md: please better split EDGE and CLOUD flow.

### ISSUE THREAD

**Issue by gguasti** [Xilinx/Vitis-AI#88]
many Customers run by mistake some commands that are dedicated to U50 server. I think we should avoid it by creating a complete and continuous flow for ZCU102/ZCU104 and one for U50. Now the two flows are interleaved.
It is just a matter of reorganizing the order of the operations.
Another big improvement could be always to specify where each command should be run (on the server or on the target board?) and if working inside the docker environment is needed or not, or when the conda environment should be activated.

**Comment by qianglin-xlnx** [comment]
Hi @gguasti 
Thank you for your valuable suggestion. Now the readme.md of VART and Vitis-AI-Library have been updated according your suggestion.
