### ISSUE TITLE
Error with replace_pytorch.sh with Docker 2.5 version

### ISSUE THREAD

**Issue by chuong98** [Xilinx/Vitis-AI#888]
![image](https://user-images.githubusercontent.com/15174756/175513200-0d04bc96-98ee-4227-981f-9eb1104c817d.png)
Hello, I can create new Docker Vitis 2.5 version, but then there is still error when replacing pytorch. Please fix

**Comment by chuong98** [comment]
I manage to fix this error by replacing the link in the `replace_pytorch.sh`
`wget -O conda-channel.tar.gz --progress=dot:mega https://www.xilinx.com/bin/public/openDownload?filename=conda-channel_2.5.0.1260-01.tar.gz`

**Comment by niuxjxlnx** [comment]
@chuong98:

Thanks for your finding. We will update the script in vitis-ai github first.

**Comment by niuxjxlnx** [comment]
The script is updated at this link: 
https://github.com/Xilinx/Vitis-AI/blob/master/docker/dockerfiles/replace_pytorch.sh
