### ISSUE TITLE
[Invalid DPU target] Error when compile xmodel with Vitis 2.5 version for ZCU104, 

### ISSUE THREAD

**Issue by chuong98** [Xilinx/Vitis-AI#890]
Hello, I can compile a pytorch model into int.xmodel, however, in the last step, when compile from int.xmodel to `xmodel` with `vai_c_xir`, it throws error that the device is not supported.
![image](https://user-images.githubusercontent.com/15174756/175772677-df3c1026-7619-440e-8976-99f0a644fb93.png)

Here is the fingerprint of ZCU104
```

//use xdputil query  
{
    "fingerprint":"0x1000020f6014407"
}
```

**Comment by JackzhangLOVEcode** [comment]
compile with VAI2.0

**Comment by chuong98** [comment]
I am using Docker, so I expect the default libs should work. 

Do you mean to build another Docker version 2.0 to compile the model ?

**Comment by JackzhangLOVEcode** [comment]
> I am using Docker, so I expect the default libs should work.
> 
> Do you mean to build another Docker version 2.0 to compile the model ?
I got same error when compiled models for ZCU102 by vitis2.5, but when checkout to vitis2.0 by ./docker_run.sh xilinx/vitis-ai-cpu:2.0.0.1103, it work fine, you can try it

**Comment by chuong98** [comment]
Do i need to upgrade the firmw

**Comment by wanghong4compiler** [comment]
Hi @chuong98 ,
yes, if you switch to Vitis 2.5, all components needs to be consistent.

**Comment by wanghong4compiler** [comment]
Hi @chuong98 ,
sorry, my bad, please try "0x0101000016010407" again, sorry again.

**Comment by chuong98** [comment]
Thanks, it works
