### ISSUE TITLE
Example designs reference in PG338 for DPUCZDX8G IP is missing

### ISSUE THREAD

**Issue by haoxi1999** [Xilinx/Vitis-AI#893]
Hi,
I have noticed the following example designs referred by PG338 are no longer available since the release of Vitis AI 2.5.

https://www.xilinx.com/bin/public/openDownload?filename=DPUCZDX8G.tar.gz
https://www.xilinx.com/bin/public/openDownload?filename=DPUCZDX8G.tar.gz

Cheers

**Comment by qianglin-xlnx** [comment]
Hi @haoxi1999 
I can download the DPUCZDX8G.tar.gz package and the structure of it is the same as before. Could you please point out what is missing in VAI2.5 comparing to VAI2.0 or VAI1.4. Thank you.

**Comment by haoxi1999** [comment]
I noticed the PG338 is updated few days ago. I think the reference link was updated and is now working! Thanks.
