### ISSUE TITLE
Re-analyse in pytorch iterative pruner before pruning?

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/Vitis-AI#895]
Before iterative pruning, we should analyse the model and generate a .sens file in .vai folder. Do I need to re-analyse my model before next pruning and generate another .sens file? Or I only need to analyse once, and the .sens file is useful to all sparsities like 0.3, 0.5, 0.7.

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,

You only need to do the model analysis once.
