### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by ajith-xilinx** [Xilinx/Vitis-AI#902]
After "git clone" information on main landing page, mention about host setup & card setup. 

```
cd ./setup/vck5000 
sudo ./install.sh
```

Without this step, the mentioned process will throw error in later steps.

**Comment by SuZhan0322** [comment]
This step has been pointed out in https://github.com/Xilinx/Vitis-AI/tree/master/setup/vck5000#setup-versal-accelerator-card.  If I noticed the wrong location, please help to point it out, thanks.

**Comment by SuZhan0322** [comment]
Hi @ajith-xilinx , 
Is there any comment update to this issue? thanks

**Comment by ajith-xilinx** [comment]
The Main Landing Page : https://github.com/Xilinx/Vitis-AI 

In this page, there is no mention about pre-requisites ( XRT Installation & DSA flash etc. ) 

The Installation process according to Main landing page, start from **git clone** & **docker pull**. 
Without installing XRT, this **docker run** will fail. 

So, it has to fist point to : 
```
cd ./setup/<device>   # cd ./setup/vck5000
sudo ./install.sh
```

And then, **git clone** -> **docker pull** -> **docker run**

**Comment by SuZhan0322** [comment]
Hi @ajith-xilinx ,
Thanks for your great suggestion, we will clarify this step in the next release.
