### ISSUE TITLE
[UNILOG][FATAL][XCOM_UNEXPECTED_VALUE]

### ISSUE THREAD

**Issue by CharlesChen1024** [Xilinx/Vitis-AI#906]
Hi, 
When I compile the .xmodel, I got an error message.
![image](https://user-images.githubusercontent.com/89010229/177479882-f1ab8b0e-2cb6-49d5-9dfe-38c94be11c63.png)
How to solve it?

**Comment by wanghong4compiler** [comment]
Hi @CharlesChen1024 ,
could you help share the model file so that I can reproduce this issue locally?

**Comment by CharlesChen1024** [comment]
Hi, @wanghong4compiler 
LiCENt_int.model is here, thank you for reply
[LiCENt_int.zip](https://github.com/Xilinx/Vitis-AI/files/9052235/LiCENt_int.zip)
.
