### ISSUE TITLE
Running unsupported subgraphs on CPU ?

### ISSUE THREAD

**Issue by mehdi-nait** [Xilinx/Vitis-AI#907]
Is there a way to run subgraphs that cannot be run on DPU on CPU cores ? I'm using a relatively big model (see picture).

Thanks!

![default](https://user-images.githubusercontent.com/45018669/177513256-871e6dfc-fc8e-4ae1-b568-dd317ce2de05.svg)

**Comment by Mookel** [comment]
Hi, @mehdi-nait, In vai2.5, we proposed a new feature called WeGO. It's a Vitis-AI in-framework inference solution, which works as frameworks' plugin to integrate Vitis-AI toolchain into diverse frameworks, including TensorFlow 1.x, TensorFlow 2.x and PyTorch. WeGO can enable graph partitioning and heterogeneous execution automatically: for operators supported by Xilinx DPUs(Deep Learning Units), WeGO will dispatch them to Vitis-AI native runtime on DPU execution, while for operators not supported by Vitis-AI, WeGO will dispatch them to native frameworks on CPU execution. 

You can refer to WeGO examples  https://github.com/Xilinx/Vitis-AI/tree/master/examples/WeGO for more details.
Thanks very much.
