### ISSUE TITLE
quant_mode in pt_personreid-res50_market1501_256_128_5.3G_2.5?

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/Vitis-AI#912]
In Vitis-AI2.0, we first used mode='calib' to export quant config and then used mode='test' to dump xmodel. But in Vitis-AI2.5, the released quantizing code is quite far away from that in 2.0, the quantizing modes are 'train', 'deploy' and  'test' respectively. So what's the order of exporting xmodel? 

The released script is used to test quantizing mode:
![image](https://user-images.githubusercontent.com/42413198/178199403-a5d3737d-c25e-4008-b8d0-34c73076cb30.png)
Should I change mode to 'train' first and then change mode to 'deploy' to get xmodel if I want to acquire a quantizing model?

Looking forward to hearing from you.

**Comment by wenjingk-xilinx** [comment]
Hi @LorenzoSun-V ,
This reid model in V2.5 is quantized by QAT(Quantized-aware-training). The whole QAT code is not released. The released script is about test.

**Comment by LorenzoSun-V** [comment]
Thanks @wenjingk-xilinx！
Do you have any plan about releasing the script of using QAT? If so, would you please 
disclose when will the script be released?

**Comment by wenjingk-xilinx** [comment]
Hi @LorenzoSun-V , we will release the qat scripts later.

**Comment by LorenzoSun-V** [comment]
Hi @wenjingk-xilinx, I just found the QAT scripts have been released. I'll try the lastest API. Thanks!

**Comment by LorenzoSun-V** [comment]
Hi @wenjingk-xilinx, I just took a glance of the released QAT code. Here are some qusetions about workflow confusing me:
1. Can the whole flow be summarized as:
    (1) train the float model, the model.py has not been modified by QAT rules as follows:
![image](https://user-images.githubusercontent.com/42413198/185572874-105b64b5-899e-473a-8a46-b57aa35e5fa9.png)
![image](https://user-images.githubusercontent.com/42413198/185572890-9fa8d91e-e44f-4b2c-98d4-ee341952edc0.png)
         However, the model.py can be like:
![image](https://user-images.githubusercontent.com/42413198/185573239-d8e6449c-f790-47a4-8740-60345828ef9e.png)

    (2) prune the float model and generate a slim model (optional).

    (3) quantize the (slim) model, and modify the model.py by QAT rules as follows:
![image](https://user-images.githubusercontent.com/42413198/185573896-afe35432-f3ce-4010-a53a-daaa3646cdb3.png)

**Comment by LorenzoSun-V** [comment]
Since the Add, Cat, ReLU, QuantStub and DeQuantStub have no weights in the ckpt of trained float model, so the model modified by model.py used in QAT is able to load the ckpt correctly. Can I understand in this way？
Because in the released [YOLOX ](https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/pt_yolox_TT100K_640_640_73G_2.5/model.yaml) project, the float model also contains the ops such as Add, Cat, ReLU, QuantStub and DeQuantStub and then I met some issues on pruning.  For more details, you can refer #966 .

**Comment by DehuaTang** [comment]
You shoud 
**(1) prune the float model and generate a slim model (optional).**
(2) the model.py has not been modified by QAT rules as follows
(3) quantize the (slim) model, and modify the model.py by QAT rules as follows

**Comment by DehuaTang** [comment]
**Pruning**  and **QAT** are fully decoupled. They can't be done together. 
Canceling any operation about QAT, then doing pruning. 
When you have finished pruning, then **(3) quantize the (slim) model, and modify the model.py by QAT rules as follows**

If you have any confusion, please contact me.

**Comment by LorenzoSun-V** [comment]
Thanks for your patient reply. 

Since backbone of my ReID model is ResNet50 and the ReID dataset is Market1501, it's much easier and faster to get the results. I'll work on ReID project to trial the whole workflow first.

I'll contact you if I meet confusing bugs.

**Comment by LorenzoSun-V** [comment]
Hi @DehuaTang, I've tried to use new pruning&quantizing APIs to deploy my model and got the xmodel successfully. 
But there is loss of metrics on VCK5000 compared to on GPU.
I use one_step pruning and QAT to get the xmodel. Here is my workflow.

My original ReID float model's metrics on Market1501 are:
![image](https://user-images.githubusercontent.com/42413198/186320178-6af7f452-f0c4-4cf6-b459-c397bc3c3124.png)

After searching subnets with sparsity=0.5 by one_step_pruner,  I retrained the best subnet and its metrics are:
![image](https://user-images.githubusercontent.com/42413198/186322588-73e44cc0-8aab-47d5-b0b8-081b22cfb3a3.png)
Even higher than my original pth.

Then I use QAT to deploy the slim model(modify and insert a lot of operators in model.py) and got metrics on GPU:
![image](https://user-images.githubusercontent.com/42413198/186322919-22c1917d-51ca-4460-9d74-ac782c367e2d.png)

However, I got lower metrics after I run generated xmodel to extract features of query and gallery images:
![image](https://user-images.githubusercontent.com/42413198/186323258-c6a4fbdb-d50e-4710-8e3b-bedbaa7d9304.png)

The details of prototxt are:
![image](https://user-images.githubusercontent.com/42413198/186323486-31434705-0eb1-4b39-aeff-65e262142279.png)
 The reid_param is due to this [reply](https://github.com/Xilinx/Vitis-AI/issues/696#issuecomment-1072093870).

Do you have any ideas about the loss of metrics?

**Comment by DehuaTang** [comment]
I think it's the difference in the implementation of pre - post processing between python and c++ code that causes this problem.
You can check it ！

**Comment by LorenzoSun-V** [comment]
Hi, @DehuaTang .

I've used the offical released reid xmodel and slim model with sparsity=0.5. I compiled the xmodel and extracted the last bn params into the prototxt. And I test it by my c++ code and use python code to evaluate the metrics, got:
![image](https://user-images.githubusercontent.com/42413198/186367531-cad2ef75-c2c8-42f7-b725-0488ee6a2a1e.png)
Which are the same as released README:
![image](https://user-images.githubusercontent.com/42413198/186367688-ccc51497-a656-44c5-8e5f-f722d929eba9.png)

This means my pre-post processing code should be correct. Here is my QAT code:
![image](https://user-images.githubusercontent.com/42413198/186368467-93379611-5d62-43ad-8f9f-387275d73005.png)

Does this can export correct xmodel?

**Comment by DehuaTang** [comment]
deployable_model = qat_processor.deployable_model(config.QAT_OUTPUT_DIR, used_for_xmodel=True)
        tmp_input = torch.randn([1, 3, 128, 256], dtype=torch.float32)
        tmp_output = deployable_model(tmp_input)
        qat_processor.export_xmodel(config.QAT_OUTPUT_DIR, deploy_check=True)

Try this !

**Comment by LorenzoSun-V** [comment]
> ```
>     deployable_model = qat_processor.deployable_model(config.QAT_OUTPUT_DIR, used_for_xmodel=True)
>     tmp_input = torch.randn([1, 3, 128, 256], dtype=torch.float32)
>     tmp_output = deployable_model(tmp_input)
>     qat_processor.export_xmodel(config.QAT_OUTPUT_DIR, deploy_check=True)
> ```
> 
> Try this !

Maybe 
`tmp_input = torch.randn([1, 3, 128, 256], dtype=torch.float32)`
shoule be
`tmp_input = torch.randn([1, 3, 256, 128], dtype=torch.float32)` ?

**Comment by DehuaTang** [comment]
Here is just an example, actually depends on your needs

**Comment by LorenzoSun-V** [comment]
Thanks, I'll try this. :full_moon_with_face:

**Comment by LorenzoSun-V** [comment]
I'm here again. :sweat_smile:

I've tried the code above, and it didn't work. But an idea just occurred into my mind: the bn_params in the prototxt are used to load the sole bn layer params during post processing, but I've trained the model by QAT which means the params of that sole bn layer have been changed.  So I extract the sole bn params in deployable.pth(export by QAT) and replace it into prototxt, got:
![image](https://user-images.githubusercontent.com/42413198/186565326-271ac32c-3445-483a-a4dc-079314376b25.png)

The metrics are better than before, but still has a little loss compared to those on GPU. I'll try to debug it sometimes, but now it seems to be OK. Thanks @DehuaTang .

**Comment by DehuaTang** [comment]
I think this error is acceptable. 
python and c++ versions of the preprocessing interpolation method may have errors.

**Comment by LorenzoSun-V** [comment]
OK, thanks.

**Comment by IkrameBeggar** [comment]
> Hi, @DehuaTang .
> 
> I've used the offical released reid xmodel and slim model with sparsity=0.5. I compiled the xmodel and extracted the last bn params into the prototxt. And I test it by my c++ code and use python code to evaluate the metrics, got: ![image](https://user-images.githubusercontent.com/42413198/186367531-cad2ef75-c2c8-42f7-b725-0488ee6a2a1e.png) Which are the same as released README: ![image](https://user-images.githubusercontent.com/42413198/186367688-ccc51497-a656-44c5-8e5f-f722d929eba9.png)
> 
> This means my pre-post processing code should be correct. Here is my QAT code: ![image](https://user-images.githubusercontent.com/42413198/186368467-93379611-5d62-43ad-8f9f-387275d73005.png)
> 
> Does this can export correct xmodel?

Hello, can you please share with me the QAT script that you have used. I am having an error with qat_processor. Here is the error I am having 
![Screenshot from 2023-10-15 15-23-57](https://github.com/Xilinx/Vitis-AI/assets/63944119/3fac87ec-5648-4739-bc76-3f2fc3208a90)

**Comment by LorenzoSun-V** [comment]
Hi, @IkrameBeggar 
I just commit the repo, you can refer this [script](https://github.com/LorenzoSun-V/lorenzo-reid-baseline/blob/main/applications/xilinx/quantize.py). But it's based on a former version of VitisAI. Hope it's helpful.

**Comment by IkrameBeggar** [comment]
> Hi, @IkrameBeggar I just commit the repo, you can refer this [script](https://github.com/LorenzoSun-V/lorenzo-reid-baseline/blob/main/applications/xilinx/quantize.py). But it's based on a former version of VitisAI. Hope it's helpful.

Thank you very much. I really appreciate it
