### ISSUE TITLE
How do I use my model

### ISSUE THREAD

**Issue by easilee** [Xilinx/Vitis-AI#913]
I have my own trained model and want to complete do inference on ZCU102

**Comment by qianglin-xlnx** [comment]
Hi @easilee 
You can refer to https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Quick-Start to deploy your model on ZCU102.

**Comment by easilee** [comment]
![QQ图片20220711181514](https://user-images.githubusercontent.com/108641692/178242820-58a90e42-01b1-4274-8a38-f11599cafe8a.png)

**Comment by easilee** [comment]
![UQ 0Z05YW0TPET)~)SDLY27](https://user-images.githubusercontent.com/108641692/178242924-c0103420-69f5-495a-a29d-6f888ef483d8.png)

**Comment by easilee** [comment]
it shows nan

**Comment by easilee** [comment]
![image](https://user-images.githubusercontent.com/108641692/178243107-9ba0b945-5abb-415a-8be9-fff486dabc8c.png)
this is xmodel input

**Comment by tracksnow** [comment]
From your above comments, this has nothing to do with xmodel, it's only the basic python program knowledge. Please remove the xmodel & vatis-ai part, only leave the basic python logic to debug your issue.  Thanks.

**Comment by lishixlnx** [comment]
From your above comments, this has nothing to do with xmodel, it's only the basic python program knowledge. Please remove the xmodel & vatis-ai part, only leave the basic python logic to debug your issue. Thanks.

**Comment by easilee** [comment]
> 从您上面的评论来看，这与xmodel无关，只是基本的python程序知识。请删除 xmodel & vatis-ai 部分，只留下基本的 python 逻辑来调试您的问题。谢谢。

https://github.com/Xilinx/Vitis-AI-Tutorials/tree/1.4/Feature_Tutorials/tf2_quant_fine_tune/files/application

I use this

**Comment by lishixlnx** [comment]
that is different. the sample is "dtype=np.int8" while you use float32.
please follow the guide carefully. thanks.

**Comment by qianglin-xlnx** [comment]
Hi @easilee 
Is this issue solved?

**Comment by qianglin-xlnx** [comment]
Hi @easilee 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
