### ISSUE TITLE
Vitis AI 2.0 compile issue 

### ISSUE THREAD

**Issue by gkdl0335** [Xilinx/Vitis-AI#922]
An error occurred while compiling a tf2 quantization model (h5) using Vitis ai 2.0 

I successed Vitis ai tutorial using tf2 

but I failed with my custom model 

![image](https://user-images.githubusercontent.com/91661984/178990026-7c2dbaf3-ed2a-45f6-86a4-65e347651b0b.png)

plz help me 

Thank you for Vitis ai manager

**Comment by zhenzhen-AMD** [comment]
Hi @gkdl0335 ，

Can floating point and quantized models and code be provided? We need these files to analyze the problem.
Thanks.

Regards

**Comment by renjiangyong** [comment]
The Issue existed for a long time with no response, I will close it , U can reopen it @gkdl0335 when you need.
