### ISSUE TITLE
Pytorch FADNet rebuild xmodel can't execute kv260 1.4 PetaLinux dpu_task fadnet

### ISSUE THREAD

**Issue by zhihaoTW** [Xilinx/Vitis-AI#924]
Hi
I trying to re-build the FADNet model, so I download Vitis AI 1.4 pt_fadnet_sceneflow_576_960_359G_1.4.zip,
then compile inside the quantization folder the FADNet_0_int, FADNet_1_int, and FADNet_2_int to xmodel, but it can't run kv260 Petalinux 1.4 it showed the following error:
![Screenshot from 2022-07-16 22-53-46](https://user-images.githubusercontent.com/103472384/179387341-309dc69e-41af-4c0c-804e-5b654b78b780.png)
I compare the Vitis AI MODEL ZOO 1.4 three FADNet xmodel, occur the FADNet_0 structure problem, it re-build xmodel is different output_tensor, my xmodel output_tensor is 1, the MODEL ZOO is 3.
my xmodel:
![Screenshot from 2022-07-16 22-44-08](https://user-images.githubusercontent.com/103472384/179387351-c861076a-b41d-4985-bc39-879b24d49ace.png)
![premodel-FADNet0](https://user-images.githubusercontent.com/103472384/179387354-7bb73e0a-3953-49c9-8745-cf11bafe7ddf.png)
MODEL-ZOO:
![Screenshot from 2022-07-16 22-57-39](https://user-images.githubusercontent.com/103472384/179387367-778b1d78-042d-444c-b699-bc75a23e75f1.png)
![modelzoo-FADNet0](https://user-images.githubusercontent.com/103472384/179387375-3a38f786-0331-4943-bab1-b7274988be52.png)
How can I increase output_tensor? 
like the Vitis ai zoo xmodel structure result.

using compile.sh file ->
source compile.sh kv260 ../quantization/FADNet_0_int.xmodel FADNet_0_pt ./kv260/FADNet_0
<img width="630" alt="compile" src="https://user-images.githubusercontent.com/103472384/179387386-b0a73500-1a3e-4c55-83e1-53f303c8d010.png">
![fadnet-result](https://user-images.githubusercontent.com/103472384/179387436-67f1239c-33f9-4b86-9356-41b52bdb283a.png)

**Comment by max271828** [comment]
Hi,
I found your command line need change when on board terminal. 
./demo_fadnet demo_fadnet_left.jpg demo_fadnet_right.jpg
The 1.4 version demo_fadnet need to execute like this.

**Comment by zhihaoTW** [comment]
> Hi, I found your command line need change when on board terminal. ./demo_fadnet demo_fadnet_left.jpg demo_fadnet_right.jpg The 1.4 version demo_fadnet need to execute like this.

Thanks for your advice.
I follow README:
![execute-fadnet](https://user-images.githubusercontent.com/103472384/179440528-ea307c40-d6a3-42fb-8c6c-43a018cf58df.png)
and then I have replace FADNet_0 to MODELZOO xmodel, it can work .
![execute-re-fadnet](https://user-images.githubusercontent.com/103472384/179440760-7a88f3b9-8133-44db-b4f9-873bc4475ced.png)
