### ISSUE TITLE
MPSoC Vitis-AI Deployment on Docker

### ISSUE THREAD

**Issue by aimilefth** [Xilinx/Vitis-AI#928]
Currently, when it comes to MPSoC deployment (ZCU104,ZCU102), the code containing the VART API is being run natively in the MPSoC. My question is whether it is possible to runa Vitis AI example through a docker on the MPSoC. Has anyone achieved such feat or are there any guidelines on how to create such docker?

**Comment by qianglin-xlnx** [comment]
Hi @aimilefth 
Could you tell me why do you want to run docker on the MPSOC? 
MPSOC is a target board with limited resources such as CPU operation and memory. So we do not try to run the docker on it.

**Comment by aimilefth** [comment]
I would like to integrate the MPSoC into a cluster controlled by Kubernetes, which would control Docker images. Therefore I want to be able to run a given .xmodel through a Docker. Note I don't want to use the development capabilities, just to be able to run an example using VART

**Comment by xihuazhanghui** [comment]
Currently the released docker only for X86 system, not for arm64 MPSoC. The prefer remote way to use the  board is the 'Board farm' method.  First connect  the Zcu102 or zcu104 board with cluster server by UART and set to JTAG mode. Second flash  board images on remote board, then run test on board.
