### ISSUE TITLE
free(): invalid pointer during xmodel export

### ISSUE THREAD

**Issue by Hamptonjc** [Xilinx/Vitis-AI#930]
I am using a built from source version of XIR, however when I attempt to export my model (pytorch) to .xmodel after QAT, I get 

"
[VAIQ_NOTE]: =>Converting to xmodel ...
free(): invalid pointer
Aborted (core dumped)
"

A similar issue:

> Hi, @wanghao16020510036:
> 
> Please try the following steps:
> 
> 1. create a new clean conda env and activate it
> 2. install pytorch 1.6 and pytorch_nndct following the instructions in https://github.com/Xilinx/Vitis-AI/tree/master/tools/Vitis-AI-Quantizer/vai_q_pytorch#install-from-source-code.
> 3. get XIR package at https://www.xilinx.com/bin/public/openDownload?filename=conda-channel_1.4.914-01.tar.gz:
> 
> ```
>    cd /tmp
>    wget -O conda-channel.tar.gz https://www.xilinx.com/bin/public/openDownload?filename=conda-channel_1.4.914-01.tar.gz
>    tar zxf conda-channel.tar.gz 
> ```
> 
> 1. install XIR into your conda environment with:
>    conda install xir -c file:///tmp/conda-channel

Hi I ues this way install xir in my own, but when export xmodel, this bug appears.

[VAIQ_NOTE]: =>Converting to xmodel
free(): invalid pointer

_Originally posted by @SpursLipu in https://github.com/Xilinx/Vitis-AI/issues/495#issuecomment-921762792_

**Comment by niuxjxlnx** [comment]
@Hamptonjc :

It looks like some mismatch happens. Can you show the code version of vai_q_pytorch and XIR?

**Comment by niuxjxlnx** [comment]
Close it since no response for a long time.
