### ISSUE TITLE
Incorrect Gitenterprise URL in Vitis AI Library Bitbake Recipe - v2.0

### ISSUE THREAD

**Issue by quentonh** [Xilinx/Vitis-AI#932]
The file:  https://github.com/Xilinx/Vitis-AI/blob/v2.0/tools/Vitis-AI-Recipes/recipes-vitis-ai/vitis-ai-library/vitis-ai-library_2.0.bb

Contains an internal gitenterprise link and needs to be updated with the public link.

Thanks!
--Quenton

**Comment by qianglin-xlnx** [comment]
Hi @quentonh 
We have fixed it in the 2.0 branch not in the v2.0 tag.
https://github.com/Xilinx/Vitis-AI/blob/2.0/tools/Vitis-AI-Recipes/recipes-vitis-ai/vitis-ai-library/vitis-ai-library_2.0.bb
