### ISSUE TITLE
Why accuracy increased after quantization ?

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/Vitis-AI#94]
In (https://github.com/Xilinx/Vitis-AI/tree/master/Tool-Example#vitis-ai-tool-example) the following results given.

FP32 evaluation : (https://github.com/Xilinx/Vitis-AI/tree/master/Tool-Example#float-model-evaluation)

INT8 evaluation : (https://github.com/Xilinx/Vitis-AI/tree/master/Tool-Example#quantized-model-evaluation)

Accuracy increased from 0.7 to 0.79

and why model size not get reduced after qunatization ?

**Comment by durgabhavaniv** [comment]
I didn't get reply till now....

**Comment by sumitn-xilinx** [comment]
@qianglin-xlnx  - Can you please repond to this query?

**Comment by qianglin-xlnx** [comment]
@sumitn-xilinx Sure. In fact, I have submitted this issue to the person in charge of it and still waiting for a clear answer.
@durgabhavaniv From my point view, float point model is usually not optimally trained in this case. You can retrain your float point model for better accuracy , at lease 0.79 in this example.  Tool-Example just show users how to use the tools in Vitis AI.

**Comment by qianglin-xlnx** [comment]
@durgabhavaniv 
The accuracy increase slightly because of the calib data is only a small portion of whole imagenet dataset. The accuracy varies a little after calibration and test. 

The  quantized model doesn't change in size because we didn't modify the data directly but only save quantize info in it, which will be used by compiler then.

**Comment by qianglin-xlnx** [comment]
hi @durgabhavaniv 
Since I haven't received your reply for a long time, I will close this issue. If you still have any questions, you can reopen this issue. Thank you.
