### ISSUE TITLE
QAT used more GPU memory than normal training.

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/Vitis-AI#941]
I'm using QAT to train my yolox_m model. But the occupied GPU memory was floating when training, and after a few iterations in the fitst epoch, I met CUDA OOM Error(I set the same batch size in both the cases).

Will using the model from QatProcessor(float_model, dummy_input).trainable_model() to train occupy more CUDA memory than using simple float model?

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,

QAT takes more GPU memory than training float model as there are addtional quantization operations.

**Comment by LorenzoSun-V** [comment]
Thanks.
