### ISSUE TITLE
DPU_TRD create xclbin fail error: No valid platform was found that matches

### ISSUE THREAD

**Issue by dreamella** [Xilinx/Vitis-AI#948]
make KERNEL=DPU DEVICE=template
v++ -t hw --platform  --save-temps --config /data/storageElla/zu19eg_dpu_ssd_axiM_0725/zu19eg_ssd_dpu_dpu_trd/DPU-TRD/prj/Vitis/config_file/prj_config --xp param:compiler.userPostSysLinkOverlayTcl=/data/storageElla/zu19eg_dpu_ssd_axiM_0725/zu19eg_ssd_dpu_dpu_trd/DPU-TRD/prj/Vitis/syslink/strip_interconnects.tcl  -l --temp_dir binary_container_1 --log_dir binary_container_1/logs --remote_ip_cache binary_container_1/ip_cache -o "binary_container_1/dpu.xclbin" binary_container_1/dpu.xo
WARNING: [v++ 60-1600] The option 'xp' was used directly on the command line, where its usage is deprecated. To ensure input line works for supported operating systems or shells, v++ supports specification for some options in a configuration file. As an alternative, please use options 'advanced.*', 'vivado.*' in a configuration file. Use one or more configuration files along with section headers to define key-value pairs for the advanced properties or parameters. Specify a configuration file using '--config'.
INFO: [v++ 84-14] Sample config file already exists. To regenerate, remove file 'sample_link.ini'.
Option Map File Used: '/data/tool/xilinx/v2020.2/Vitis/2020.2/data/vitis/vpp/optMap.xml'

****** v++ v2020.2 (64-bit)
  **** SW Build (by xbuild) on 2020-11-18-05:13:29
    ** Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.

ERROR: [v++ 60-1258] No valid platform was found that matches '--save-temps'. Please make sure that the platform is specified correctly, and the platform has the right version number. The platform repo paths are:
        /data/tool/xilinx/v2020.2/Vitis/2020.2/platforms
The valid platforms found from the above repo paths are:

ERROR: [v++ 60-587] Failed to add a platform: specified platform --save-temps is not found or is not valid
INFO: [v++ 60-1662] Stopping dispatch session having empty uuid.
INFO: [v++ 60-1653] Closing dispatch client.
Makefile:70: recipe for target 'binary_container_1/dpu.xclbin' failed
make: *** [binary_container_1/dpu.xclbin] Error 1

**Comment by jiaz-xlnx** [comment]
Hi @dreamella do you set the SDX_PLATFORM environment? this error means this environment setting doesn't set correctly.
you can use echo $SDX_PLATFORM to check it?
