### ISSUE TITLE
hal_host_trace.csv missing when profile the model

### ISSUE THREAD

**Issue by AdrFebles** [Xilinx/Vitis-AI#952]
Hi!
When I use vaitrace  to profile the model. I got the following files:

`python3 -m vaitrace_py ./app.py 2 /usr/share/vitis_ai_library/models/PATH DEL XMODEL/`

summary.csv, profile_summary.csv, vart_trace.csv, xrt.run_summary and vitis_ai_profile.csv but I don't got the hal_host_trace.csv, so the Timiline Trace in Vitis Analyzer shows only this:
![imagen](https://user-images.githubusercontent.com/103190068/182879174-b71a79a7-60f0-4adf-9daa-2bbf4ed47152.png)

Does anyone have any idea what might be going wrong?
Thanks!

**Comment by qianglin-xlnx** [comment]
Hi @AdrFebles 
Thank you for your feedback. We have filed a Jira internal. If there are any updates, I will let you know. Thank you.

**Comment by AdrFebles** [comment]
> Hi @AdrFebles Thank you for your feedback. We have filed a Jira internal. If there are any updates, I will let you know. Thank you.

Ok @qianglin-xlnx, thank you

**Comment by li900309** [comment]
hi @AdrFebles  as far as I know, hal_host_trace.csv seems to be obsolete by xrt after 21.1, What information do you need from this

**Comment by AdrFebles** [comment]
> hi @AdrFebles as far as I know, hal_host_trace.csv seems to be obsolete by xrt after 21.1, What information do you need from this

Ok @li900309, I didn't have this information. With the rest of .csv files I managed to analyze the DPU Performance, but the CPU usage is not shown.
Thanks for replying
