### ISSUE TITLE
failed to create XRM context

### ISSUE THREAD

**Issue by jzymessi** [Xilinx/Vitis-AI#953]
I run the vck5000 model in docker 2.5, unspecified error encountered
![image](https://user-images.githubusercontent.com/51226649/182981587-90a3f95e-e23e-40e5-869a-c549bc33c6a7.png)
it works in docker 2.0
how to solve it?

**Comment by SuZhan0322** [comment]
Hi @jzymessi , I believe you have found the cause of the issue, you need to install the correct version of xrm on the host before running the model in docker container.

**Comment by jzymessi** [comment]
Hi @SuZhan0322 :
     Thanks, I already slove this issue.
