### ISSUE TITLE
Hello! problems during installing VART

### ISSUE THREAD

**Issue by HankIC** [Xilinx/Vitis-AI#955]
Hello! I'm installing VART v1.1. I want to set up the host for edge. I follow the readme file to the final step: bash -x build.sh. I meet this problem:
build.sh: line 27: aarch64-xilinx-linux-g++: command not found
How can I fix this problem? Thank you!
![IMG_20220806_000638](https://user-images.githubusercontent.com/110684722/183117381-90f8c1dc-a3c5-4aee-a45d-41b449b41b98.jpg)

**Comment by HankIC** [comment]
![IMG_20220806_000638](https://user-images.githubusercontent.com/110684722/183117166-0e1469f0-2664-4a22-ac82-bbbb8fd2b802.jpg)

**Comment by lishixlnx** [comment]
as the readme mentions:
 If you encounter any path errors in running examples, check to see if you follow the steps above to set the host.
 
 Please follow the steps carefully.
did you run the steps 
# ./host_cross_compiler_setup.sh
mentioned in below page ?
https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc#step1-setup-cross-compiler

**Comment by HankIC** [comment]
> as the readme mentions: If you encounter any path errors in running examples, check to see if you follow the steps above to set the host.
> 
> Please follow the steps carefully. did you run the steps
> 
> # ./host_cross_compiler_setup.sh
> mentioned in below page ? https://github.com/Xilinx/Vitis-AI/tree/master/setup/mpsoc#step1-setup-cross-compiler

Thank you friend! I reboot the computer, rerun the "unset LD_LIBRARY_PATH; source ~/petalinux_sdk/environment-setup-aarch64-xilinx-linux" command, and rerun "bash -x [build.sh](https://build.sh/)" again according to the “https://github.com/Xilinx/Vitis-AI/tree/1.1/VART”. It works!
