### ISSUE TITLE
WARNING when compiling quantized pytorch model with vai_c_xir: MaxPool2d or AvgPool2d has been allocated to CPU.

### ISSUE THREAD

**Issue by wgshun** [Xilinx/Vitis-AI#965]
Hello,

I quantized a pytorch model and got an .xmodel. During compilation, I get the following warning:

```
[UNILOG][WARNING] xir::Op{name = Resnet__Resnet_Sequential_body__bottleneck_IR_1__MaxPool2d_shortcut_layer__9252, type = pool-fix} has been allocated to CPU.
[UNILOG][WARNING] xir::Op{name = Resnet__Resnet_Sequential_body__bottleneck_IR_2__AvgPool2d_shortcut_layer__9320, type = pool-fix} has been allocated to CPU.
```

Has anyone had the same error or knows what might be causing this error message?

I use Vitis-AI Docker vitis-ai-cpu:1.3.411.

Hope you can help me.
Thank you!

<img width="758" alt="1660191605506" src="https://user-images.githubusercontent.com/28470705/184064228-d69b5225-1c5e-4bcb-9b45-08b6a28b04f3.png">

**Comment by wanghong4compiler** [comment]
Hi @wgshun ,
which hardware target did you choose?

**Comment by wgshun** [comment]
@wanghong4compiler 
Hi,
`[UNILOG][INFO] Target architecture: DPUCZDX8G_CUSTOMIZED`

**Comment by sh39o** [comment]
Hi @wgshun ,
You can upgrade to vitis-ai >= 1.4, or you can remove the pool manually from your code.
(The pool with kernel size 1 and padding 0 doesn't modify the data, so you can delete the pool safely).
