### ISSUE TITLE
Incorrect hyperlink in https://github.com/Xilinx/Vitis-AI/blob/master/examples/README.md

### ISSUE THREAD

**Issue by jimw567** [Xilinx/Vitis-AI#967]
The hyperlinks for VART and Vitis-AI-Library in https://github.com/Xilinx/Vitis-AI/blob/master/examples/README.md are incorrect.

**Comment by qianglin-xlnx** [comment]
Hi @jimw567 
Thank you for your feedback. We will fix it.

**Comment by qianglin-xlnx** [comment]
Fixed. Please try it again. Thank you.
