### ISSUE TITLE
Incorrect link to Modelzoo in https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Library/README.md

### ISSUE THREAD

**Issue by jimw567** [Xilinx/Vitis-AI#968]
The link to Modelzoo in https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Library/README.md is incorrect.

**Comment by qianglin-xlnx** [comment]
Hi @jimw567 
Thank you for your feedback. We will fix it.

**Comment by qianglin-xlnx** [comment]
Fixed. Please try it again. Thank you.
