### ISSUE TITLE
QAT of YOLOX

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/Vitis-AI#969]
In released [yolox](https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/pt_yolox_TT100K_640_640_73G_2.5/model.yaml), QAT has been used.

I have generated a convert_qat.pth and want to export convert_qat.pth to xmodel.

However, the "qat_convert.sh" script has two undefined cmd params(marked in the red box of the following picture) and really confuses me:
![image](https://user-images.githubusercontent.com/42413198/184570151-3acf5f2f-1b65-4d61-870b-0a6632bdf761.png)

I delete the params in my script and the program hit me to do calib before export xmodel like PTQ：
![image](https://user-images.githubusercontent.com/42413198/184570440-7611b8e9-6ad8-4e1d-8e04-ba11637151a9.png)

So, how to skip calib step and export xmodel by my convert_qat.pth directly?

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,

- --nndct_equalization
- --nndct_param_corr

These two cmd parameters are defined in vai_q_pytorch. When you call "import pytorch_nndct", they are introduced into the current command.
Very confusing indeed, I suggest forgetting about this and using the new API.
Please refer to this: https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Quantizer/vai_q_pytorch/example/resnet18_qat.py#L631

**Comment by LorenzoSun-V** [comment]
Thanks @yuwang-xlnx ! It's really helpful. I'll try the new API later.

**Comment by LorenzoSun-V** [comment]
Hi @yuwang-xlnx ,
I've tried the new API and encounter some issues.
I use the following code to export xmodel:
![image](https://user-images.githubusercontent.com/42413198/184851128-e80c1578-6d77-4a61-9759-641604e6bed2.png)

However, when I use the deployable_model to infer COCO val set, I got:
![image](https://user-images.githubusercontent.com/42413198/184851358-b469ec40-45ca-46a7-8d25-15f037928f54.png)

I also use exported xmodel to infer COCO val set on VCK5000 and got predicted bboxes and classes, but I got lower results than those on GPU(To evaluate the xmodel, I use VCK5000 to obtain the result json file and use pycocotools to calculate APs):
![image](https://user-images.githubusercontent.com/42413198/184852163-cb03a14d-c189-49eb-aa6d-f540a969e6fb.png)

So, is it normal to have a 4% loss of AP:IoU=0.50:0.95?

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,

Is the AP of deployable model consistent with that tested during training? If it is the same, then it is likely that the preprocessing on VCK5000 is different from that on GPU.

**Comment by LorenzoSun-V** [comment]
Thanks @yuwang-xlnx . I modify the conf_threshold in prototxt from 0.25(used in demo inference on GPU) to 0.01(used in AP calculation on GPU) and the APs on VCK5000 are equal to those on GPU.
![image](https://user-images.githubusercontent.com/42413198/185017071-097401b3-6fee-48d1-9c41-76257b0ba775.png)

The same results on VCK5000:
![image](https://user-images.githubusercontent.com/42413198/185017923-2e4d1012-d148-4601-bde6-d63cc7733c60.png)

**Comment by LorenzoSun-V** [comment]
Hi @yuwang-xlnx,

I'm working on deploying the pruning YOLOX model. Since the pruning methods and QAT are fully decoupled(refer this [reply](https://github.com/Xilinx/Vitis-AI/issues/912#issuecomment-1221736723)), I retrained another YOLOX model which only including torch original operations.

However, when I use the retrained original pth to QAT, I encountered the shape error in this stem operation. 

The following picture shows the difference between original and QAT stem operations.
![image](https://user-images.githubusercontent.com/42413198/186622980-a12a5288-fc84-4c96-95a7-8660bc3e0329.png)

The QAT stem operation just includes a conv layer but not splitting channels and concrating. Why don't the QAT stem operation be the same to the original one? Is it because the DPU does not support this kind of operation(split channels)?

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,
Sorry I didn't understand what you meant. How did you get the pruned slim model?

**Comment by LorenzoSun-V** [comment]
Sorry, I may not have expressed clearly.

In previous QA, I trained the float model based on modified model.py(following QAT rules, details are in this [reply](https://github.com/Xilinx/Vitis-AI/issues/912#issuecomment-1220378330)) and one operation named 'stem' of this modified model.py is class 'FocusDeploy':
![image](https://user-images.githubusercontent.com/42413198/186655945-53a48033-438c-4629-89a4-72fe5c8dca5a.png)

However, an error occurred when I prune the model. This [reply](https://github.com/Xilinx/Vitis-AI/issues/912#issuecomment-1221736723) said "Pruning and QAT are fully decoupled." So I retrained YOLOX model based on an original model.py(without QAT operations like pytorch_nndct.nn.modules.functional.Cat/Add, including the 'FocusDeploy'), the class 'FocusDeploy' in original model.py is class 'Focus':
![image](https://user-images.githubusercontent.com/42413198/186657496-695567ea-c0de-4a25-a2bc-60fe9f62bac9.png)

When I used this new retrained model to QAT, I encountered the shape error. This error is due to the difference between 'FocusDeploy' and 'Focus' obviously.
Assumed a input tensor with shape of [16,3,640,640], the original 'Focus' splits the tensor to 4 tensors with shape of [16, 3, 320, 320] and then concatenates the 4 tensors to a single tensor with shape of [16,12,320,320]. The the [16,12,320,320] tensor is as the input of the conv layer. But the 'FocusDeploy' takes the tensor with shape of [16,3,640,640] as a input directly. 

So my question "Why don't the QAT stem operation be the same to the original one? Is it because the DPU does not support this kind of operation(split channels)?" may translate to "Why is the FocusDeploy in QAT not the same as the Foucs in original model?"

**Comment by yuwang-xlnx** [comment]
Hi @LorenzoSun-V,

The stem operation should be the same with the original one. 
When you do QAT, what you need to do is to wrap the function operation to a `torch.nn.Module` object.
The rewriting process  does not change the model's forward and the new network is fully equivalent to the original network.

**Comment by LorenzoSun-V** [comment]
OK, but I'm not sure that slice operation is supported by Vitis-AI and VCK5000.
The code in the green box of the following picture shows slice opertation.
![image](https://user-images.githubusercontent.com/42413198/186809468-5cc4accd-6711-4ef5-b79c-e013d268022f.png)

**Comment by LorenzoSun-V** [comment]
I've used a toy model only containing the stem operation to export xmodel successfully.
The xmodel is:
![image](https://user-images.githubusercontent.com/42413198/186846717-92ffb6bc-9756-460f-8daa-ba89a490c337.png)

I think it's ok to deploy the original model. Thanks.

**Comment by aiqiangbrave** [comment]
hi, sorry，please ask the following path questions:

Does the first path refer to the .pth file generated by the quant_PTQ.sh script?

What about the second and third paths??
Thank you~~~
Thank you~~~
![image](https://user-images.githubusercontent.com/93561249/202643609-67c1b208-2d30-4fc4-9c95-443bd1d063be.png)

**Comment by aiqiangbrave** [comment]
> Hi @LorenzoSun-V,
> 
> The stem operation should be the same with the original one. When you do QAT, what you need to do is to wrap the function operation to a `torch.nn.Module` object. The rewriting process does not change the model's forward and the new network is fully equivalent to the original network.
> 
> The class `Focus` and `FocusDeploy` are obviously not the same, so make sure they are still equivalent after wrapping the `torch.cat`.
[Could you help me analyze the size of the model? ](https://github.com/Xilinx/Vitis-AI/issues/969#issuecomment-1214846043)I remember that the xmodel model after yolov4 compression is about 7M, but the model after yolox compression is only twice shrunk (about 90M), is this normal? Thank you so much

**Comment by aiqiangbrave** [comment]
> Hi @LorenzoSun-V,
> 
> The stem operation should be the same with the original one. When you do QAT, what you need to do is to wrap the function operation to a `torch.nn.Module` object. The rewriting process does not change the model's forward and the new network is fully equivalent to the original network.
> 
> The class `Focus` and `FocusDeploy` are obviously not the same, so make sure they are still equivalent after wrapping the `torch.cat`.

### **[Could you help me analyze the size of the model? I remember that the xmodel model after yolov4 compression is about 7M, but the model after yolox compression is only twice shrunk (about 90M), is this normal? Thank you so much**

**Comment by LorenzoSun-V** [comment]
@aiqiangbrave , it's normal. I also got a YOLOX xmodel of 90M.

**Comment by aiqiangbrave** [comment]
Thank you very much，Good morning~~~（China time）
> @aiqiangbrave , it's normal. I also got a YOLOX xmodel of 90M.
I used the officially quantified xmodel file to compile, but the error was displayed. Have you ever encountered it? Thank you

![image](https://user-images.githubusercontent.com/93561249/202945215-5f7ce1e8-7f19-4a29-932e-1050657d5f8c.png)

**Comment by LorenzoSun-V** [comment]
No, I didn't encounter this error before.
I used `vai_c_xir -x your_xmodel_file.xmodel -a /your/arch_vck_file.json -o /your_output_dir -n your_output_xmodel_name` to complie in docker container.

**Comment by aiqiangbrave** [comment]
> No, I didn't encounter this error before. I used `vai_c_xir -x your_xmodel_file.xmodel -a /your/arch_vck_file.json -o /your_output_dir -n your_output_xmodel_name` to complie in docker container.

yes,yes,yes,I also use this format.
Can I ask you two path questions? Maybe I got the weight path wrong. Thank you very much~~~
![image](https://user-images.githubusercontent.com/93561249/202953246-2104fd18-e7d1-44a4-8ef4-872ef8b2a73c.png)
What exactly do these two weights refer to?

**Comment by LorenzoSun-V** [comment]
I didn't use the official script to generate xmodel.
Maybe you can refer this [answer](https://github.com/Xilinx/Vitis-AI/issues/912#issuecomment-1225366862).

**Comment by aiqiangbrave** [comment]
> 

Ok ,thank you

**Comment by aiqiangbrave** [comment]
> 

hi,Can you refer to your quantified script? (If convenient)

**Comment by aiqiangbrave** [comment]
> I didn't use the official script to generate xmodel. Maybe you can refer this [answer](https://github.com/Xilinx/Vitis-AI/issues/912#issuecomment-1225366862).

hi,Can I  refer to your quantified script? (If convenient)

**Comment by LorenzoSun-V** [comment]
Actually, I just used `python tools/train/py -f {your qat config file} -d 4 -b 32` to train the model. And then use `convert_qat.py` to convert `model.pth` to `depolyable.pth` which used for generating xmodel.

In class ExpDeployQat, the function get_model() is like:
```
    def get_model(self):
        from yolox.models.yolox_deploy import YOLOX
        from yolox.models.yolo_pafpn_deploy import YOLOPAFPN
        from yolox.models.yolo_head_deploy import YOLOXHead

        def init_yolo(M):
            for m in M.modules():
                if isinstance(m, nn.BatchNorm2d):
                    m.eps = 1e-3
                    m.momentum = 0.03

        if getattr(self, "model", None) is None:
            in_channels = [256, 512, 1024]
            backbone = YOLOPAFPN(self.depth, self.width, in_channels=in_channels, act=self.act)
            head = YOLOXHead(self.num_classes, self.width, in_channels=in_channels, act=self.act)
            self.model = YOLOX(backbone, head)

        self.model.apply(init_yolo)
        self.model.head.initialize_biases(1e-2)

        if self.is_qat:
            if self.float_ckpt:
                ckpt = torch.load(self.float_ckpt)
                print('Loading float model weight for QAT from {}'.format(self.float_ckpt))
                self.model.load_state_dict(ckpt["model"])
            dummy_input = torch.randn([1, 3, self.input_size[0], self.input_size[1]], dtype=torch.float32).cuda()
            logger.info(f"dummy_input size: {self.input_size[0]} x {self.input_size[1]}")
            self.qat_processor = QatProcessor(self.model, dummy_input, bitwidth=8, mix_bit=False)
            self.model = self.qat_processor.trainable_model()

        return self.model
```

In addition, function convert_qat is like:
```
    def convert_qat(self, qat_model, ckpt_path, cvt_dir):
        if not os.path.exists(cvt_dir):
            os.makedirs(cvt_dir)
        print("loading checkpoint from {}".format(ckpt_path))
        ckpt = torch.load(ckpt_path) 
        qat_model.load_state_dict(ckpt["model"])
        deployable_net = self.qat_processor.to_deployable(qat_model, output_dir=cvt_dir)
        print("Save converted QAT results in {}".format(cvt_dir))
        return deployable_net
```

Hope it helps you.

**Comment by Shreyas-NR** [comment]
Hi @LorenzoSun-V 
I'm also working on YOLOX with the custom dataset. 
I trained the float model and quantized it.
Now I want to use the QAT scripts, could you help me with the steps to follow?

Also, Do you have a reference script for the application code to run on the board? I'm confused about how to post-process the 3 outputs of the cat() from the quantized model.

**Comment by LorenzoSun-V** [comment]
Hi @Shreyas-NR 

About QAT(take COCO as an example):
First of all, I used 
```
export CUDA_VISIBLE_DEVICES=1,2,3,4
GPU_NUM=4
BATCH_SIZE=32
CFG=exps/example/custom/yolox_m_coco_qat.py
python tools/train.py -f ${CFG} -d ${GPU_NUM} -b ${BATCH_SIZE}
```
to train QAT model.

Then, I used
```
import argparse
import sys
import torch
sys.path.append('.')
from yolox.exp import get_exp
from yolox.evaluators import COCOEvaluator
from yolox.data import COCODataset, ValTransform


def make_parser():
    parser = argparse.ArgumentParser("YOLOX Eval")
    parser.add_argument("-expn", "--experiment-name", type=str, default=None)
    parser.add_argument("-n", "--name", type=str, default=None, help="model name")
    parser.add_argument("-b", "--batch-size", type=int, default=128, help="batch size")
    parser.add_argument(
        "-f",
        "--exp_file",
        default=None,
        type=str,
        help="pls input your expriment description file",
    )
    parser.add_argument("-c", "--ckpt", default=None, type=str, help="ckpt for eval")
    parser.add_argument("--cvt_dir", default=None, type=str, help="directory for the converted results")
    return parser


def main(args):
    exp = get_exp(args.exp_file, args.name)
    if not args.experiment_name:
        args.experiment_name = exp.exp_name
    model = exp.get_model()
    evaluator = exp.get_evaluator(args.batch_size, False, False, False, quantized=True)
    deployable_model = exp.convert_qat(model, args.ckpt, args.cvt_dir)
    print(deployable_model)
    *_, summary = evaluator.evaluate(deployable_model, model, False, False, None, None, exp.test_size, False)
    print("\n" + summary)

    deployable_model = exp.qat_processor.deployable_model(args.cvt_dir, used_for_xmodel=True)
    valdataset = COCODataset(
        data_dir=exp.data_dir,
        json_file=exp.val_ann,
        name="val2017",
        img_size=exp.test_size,
        preproc=ValTransform(legacy=False),
    )
    val_subset = torch.utils.data.Subset(valdataset, list(range(1)))
    subset_loader = torch.utils.data.DataLoader(val_subset, batch_size=1, shuffle=False, num_workers=4, pin_memory=True)
    for imgs, _, _, _ in subset_loader:
        deployable_model(imgs)
    exp.qat_processor.export_xmodel(args.cvt_dir)

if __name__ == "__main__":
    args = make_parser().parse_args()
    main(args)

```
to generate and infer `deployable.pth` on COCO.

Eventually, I used
```
import argparse
import random
import warnings
from loguru import logger
import sys
import os
import torch
import torch.backends.cudnn as cudnn
sys.path.append('.')
from yolox.core import Trainer, launch
from yolox.exp import get_exp
from yolox.utils import configure_nccl, configure_omp, get_num_devices, setup_logger, get_local_rank
from yolox.data import COCODataset, ValTransform


def make_parser():
    parser = argparse.ArgumentParser("YOLOX train parser")
    parser.add_argument("-expn", "--experiment-name", type=str, default=None)
    parser.add_argument("-n", "--name", type=str, default=None, help="model name")

    # distributed
    parser.add_argument(
        "--dist-backend", default="nccl", type=str, help="distributed backend"
    )
    parser.add_argument(
        "--dist-url",
        default=None,
        type=str,
        help="url used to set up distributed training",
    )
    parser.add_argument("-b", "--batch-size", type=int, default=64, help="batch size")
    parser.add_argument(
        "-d", "--devices", default=None, type=int, help="device for training"
    )
    parser.add_argument("-m", "--mode", type=str, choices=['train', 'deploy', 'test'], help="deploy mode, train for QAT train | deploy for exporting xmodel")
    parser.add_argument(
        "-f",
        "--exp_file",
        default=None,
        type=str,
        help="plz input your experiment description file",
    )
    parser.add_argument(
        "--resume", default=False, action="store_true", help="resume training"
    )
    parser.add_argument("-c", "--ckpt", default=None, type=str, help="checkpoint file")
    parser.add_argument("--conf", default=None, type=float, help="test conf")
    parser.add_argument("--nms", default=None, type=float, help="test nms threshold")
    parser.add_argument("--tsize", default=None, type=int, help="test img size")
    parser.add_argument(
        "-e",
        "--start_epoch",
        default=None,
        type=int,
        help="resume training start epoch",
    )
    parser.add_argument(
        "--num_machines", default=1, type=int, help="num of node for training"
    )
    parser.add_argument(
        "--machine_rank", default=0, type=int, help="node rank for multi-node training"
    )
    parser.add_argument(
        "--fp16",
        dest="fp16",
        default=False,
        action="store_true",
        help="Adopting mix precision training.",
    )
    parser.add_argument(
        "--cache",
        dest="cache",
        default=False,
        action="store_true",
        help="Caching imgs to RAM for fast training.",
    )
    parser.add_argument(
        "-o",
        "--occupy",
        dest="occupy",
        default=False,
        action="store_true",
        help="occupy GPU memory first for training.",
    )
    parser.add_argument(
        "opts",
        help="Modify config options using the command-line",
        default=None,
        nargs=argparse.REMAINDER,
    )
    return parser


@logger.catch
def main(exp, args):
    if exp.seed is not None:
        random.seed(exp.seed)
        torch.manual_seed(exp.seed)
        cudnn.deterministic = True
        warnings.warn(
            "You have chosen to seed training. This will turn on the CUDNN deterministic setting, "
            "which can slow down your training considerably! You may see unexpected behavior "
            "when restarting from checkpoints."
        )

    # set environment variables for distributed training
    configure_nccl()
    configure_omp()
    cudnn.benchmark = True

    if args.conf is not None:
        exp.test_conf = args.conf
    if args.nms is not None:
        exp.nmsthre = args.nms
    if args.tsize is not None:
        exp.test_size = (args.tsize, args.tsize)

    if args.mode == "train":
        trainer = Trainer(exp, args)
        trainer.train()
        
        deployable_model = trainer.exp.qat_processor.to_deployable(trainer.exp.model, os.path.join(trainer.file_name, 'qat'))
        evaluator = trainer.exp.get_evaluator(args.batch_size, False, False, False, quantized=True)
        *_, summary = evaluator.evaluate(deployable_model.to(torch.device('cuda')), trainer.exp.model, False, False, None, None, exp.test_size, False)
        logger.info("\n" + "deployable_model metric: \n" + summary)
    elif args.mode == "deploy":
        exp.get_model()
        deployable_model = exp.qat_processor.deployable_model(os.path.join(exp.output_dir, args.experiment_name, 'qat'), used_for_xmodel=True)
        valdataset = COCODataset(
        data_dir=exp.data_dir,
        json_file=exp.val_ann,
        name="val2017",
        img_size=exp.test_size,
        preproc=ValTransform(legacy=False),
        )
        val_subset = torch.utils.data.Subset(valdataset, list(range(1)))
        subset_loader = torch.utils.data.DataLoader(val_subset, batch_size=1, shuffle=False, num_workers=4, pin_memory=True)
        for imgs, _, _, _ in subset_loader:
            deployable_model(imgs)
        exp.qat_processor.export_xmodel(os.path.join(exp.output_dir, args.experiment_name, 'qat'))
    elif args.mode == "test":
        rank = get_local_rank()
        setup_logger(
        os.path.join(exp.output_dir, args.experiment_name),
        distributed_rank=rank,
        filename="qat_test_log.txt",
        mode="a",
        )
        exp.get_model()
        deployable_model = exp.qat_processor.deployable_model(os.path.join(exp.output_dir, args.experiment_name, 'qat'), used_for_xmodel=False)
        evaluator = exp.get_evaluator(args.batch_size, False, False, False, quantized=True)
        *_, summary = evaluator.evaluate(deployable_model.to(torch.device('cuda')), exp.model, False, False, None, None, exp.test_size, False)
        logger.info("\n" + "deployable_model metric: \n" + summary)
    else:
        raise ValueError('mode must be one of ["train", "deploy", "test"]')


if __name__ == "__main__":
    args = make_parser().parse_args()
    exp = get_exp(args.exp_file, args.name)
    exp.merge(args.opts)

    if not args.experiment_name:
        args.experiment_name = exp.exp_name

    num_gpu = get_num_devices() if args.devices is None else args.devices
    assert num_gpu <= get_num_devices()

    dist_url = "auto" if args.dist_url is None else args.dist_url
    launch(
        main,
        num_gpu,
        args.num_machines,
        args.machine_rank,
        backend=args.dist_backend,
        dist_url=dist_url,
        args=(exp, args),
    )
```
 convert `deployable.pth`  to `YOLOX_int.xmodel`.

The config file `exps/example/custom/yolox_m_coco_qat.py` mentioned above defines `YOLOX model` following QAT rules( Information about Xilinx QAT rules is [here](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/vai_q_pytorch-QAT) ). 

In a word, QAT steps are:
1. rewrite model.py following QAT model rules
2. retrain QAT model 
3. generate `deployable.pth`
4. convert `deployable.pth` to `xmode`

About post-porcess:
If you wanna depoly yolox xmodel on the borad(infer a jpeg image on the board), you are supposed to refer [this code](https://github.com/Xilinx/Vitis-AI/blob/master/examples/Vitis-AI-Library/samples/yolovx/test_jpeg_yolovx.cpp).
About post-process,  you can refer [here](https://github.com/Xilinx/Vitis-AI/blob/06a72491bd9fc72bbc743ea1753d005cbeb6acc8/src/Vitis-AI-Library/yolovx/src/yolovx_imp.cpp#L80). For futher code, you can read VitisAi source cc code.

**Comment by Shreyas-NR** [comment]
Thank you so much @LorenzoSun-V for your response. I'll get back if I get stuck anywhere.

**Comment by LorenzoSun-V** [comment]
You are welcome @Shreyas-NR.
YOLOX README.md provided by Xilinx is so outdated that it confused me for a long time.
You'd better follow the up-to-date document like `ug1414-vitis-ai-v2.5` when coding.
