### ISSUE TITLE
Is it possible to use vaitrace on AWS F1 instance?

### ISSUE THREAD

**Issue by williamliao28** [Xilinx/Vitis-AI#982]
Hello,

I have tried to run vaitrace with AWS F1 instance and always get the following error

```
ERROR:root:[]
ERROR:root:xmodel info raw info error
```

So I would like to know if there is any way to do profiling with vaitrace on AWS F1 instance because I need more detailed information on how the operations are executed on DPU circuits.

**Comment by SuZhan0322** [comment]
Hi @williamliao28 ,
The vaitrace tool is supported on AWS F1 instance, But the xclbin needs an update to run 2.5 models on F1 instance. We are working on it and will release another AMI soon. thanks~

**Comment by SuZhan0322** [comment]
Hi @williamliao28,
Please reopen this issue if you have any other questions. thanks!
