### ISSUE TITLE
Does VCK5000 support int16 quantization quantization CNN model？

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#985]
Hello xilinx,

As far as I know, currently xilinx devices do not support fp16, But I want to know what models support int16 quantization, including transformer models?

**Comment by jia0511** [comment]
Hello xilinx,

Does vitis-ai2.5 support int16 quantization? Associated questions are here：https://github.com/Xilinx/Vitis-AI/issues/712

**Comment by niuxjxlnx** [comment]
Quantizer in Vitis-AI 2.5 supports int16 quantization.

**Comment by jia0511** [comment]
@niuxjxlnx 

Do all CNN weights support in16 quantization? How does the user end perform int16 format model quantization? It is necessary to modify the quantization value of the weight and activation function in the quantization code api.py? Or the activation function of LSTM and RNN only supports int16 quantization？

**Comment by niuxjxlnx** [comment]
@jia0511 :

For how to control bits number of quantization, please refer to Vitis-AI 2.5 user guide [ug1414, ](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Configuration-of-Quantization-Strategy).

LSTM/RNN also support any bits number of quantization in tool, but for deployment of acceptable accuracy, only int16 quantization for activation makes sense.

**Comment by jia0511** [comment]
@niuxjxlnx

I reopened the question. After the model is quantized to INT16, I have encountered some problems during deployment and need help to answer.

**Comment by jzymessi** [comment]
Hi @niuxjxlnx :

  I already quant and compile int16  resnet50 model in Vitis Ai 2.5 . But when I run classification jpeg demo，I found accuracy is error. 
  
  Is there anything else that needs to be changed during deploy?

![image](https://user-images.githubusercontent.com/51226649/187165655-d3f84576-4ded-4788-8800-e62a2434b9a4.png)

**Comment by niuxjxlnx** [comment]
@jia0511 , @jzymessi :

In Vitis-AI 2.5, for CNN model, only qunatizer supports int16 quantization, compiler and runtime does not support it.

**Comment by jzymessi** [comment]
@niuxjxlnx ：
   Thanks.
   May I ask when compiler and runtime can support it?

**Comment by jia0511** [comment]
@niuxjxlnx 

We would like to know whether the vitis-ai3.0 version, which will be released next year, supports the deployment of INT16, or whether it supports fp16 for quantitative deployment on hardware?

**Comment by niuxjxlnx** [comment]
> @niuxjxlnx ： Thanks. May I ask when compiler and runtime can support it?

So far, for CNN model, compiler and runtime has no plan to support INT16 deployment.

**Comment by niuxjxlnx** [comment]
> @niuxjxlnx
> 
> We would like to know whether the vitis-ai3.0 version, which will be released next year, supports the deployment of INT16, or whether it supports fp16 for quantitative deployment on hardware?

fp16 model to int8 deployment will be supported in VAI 3.0, but no plan of int16 deployment for CNN model.
