### ISSUE TITLE
How to change xmodel's input shape

### ISSUE THREAD

**Issue by HappyOgreMagi** [Xilinx/Vitis-AI#987]
I want to change the input shape of pt_SESR-S_DIV2K_360_640_7.48G_2.0 to 360*640，but it is always 256*256. I have tried change "dummy_input "in main_qat.py,but it  is not work .
![mmexport1661330873258](https://user-images.githubusercontent.com/54392588/186374060-fa411ab5-8482-4301-8772-4f67a29b20cb.png)

**Comment by wangxd-xlnx** [comment]
Hi @HappyOgreMagi 

If you want to change the input shape of xmodel, you need to change the data you use for dumping xmodel. 
Just change "dummy_input " parameter in QAT scripts won't work. According to logic of tool, the first image of the given data is used by default.

**Comment by HappyOgreMagi** [comment]
> Hi @HappyOgreMagi
> 
> If you want to change the input shape of xmodel, you need to change the data you use for dumping xmodel. Just change "dummy_input " parameter in QAT scripts won't work. According to logic of tool, the first image of the given data is used by default.

**Comment by HappyOgreMagi** [comment]
thanks，its worked
