### ISSUE TITLE
Vitis-AI profile error

### ISSUE THREAD

**Issue by CharlesChen1024** [Xilinx/Vitis-AI#989]
Hi, 
When I profile the .xmodel, I got some error messages.
![image](https://user-images.githubusercontent.com/89010229/186585068-32622cf7-42e5-46ca-b1a2-e3d93cb1c913.png)
How to solve them?

**Comment by li900309** [comment]
hi @CharlesChen1024 , i think this information implies that the xmodel is not loaded correctly, you can try run the program without vaitrace first, make sure everything related to vitis-ai is working properly, then start the program with vaitrace to profile

**Comment by CharlesChen1024** [comment]
@li900309 ,thanks for your reply. I solved the problem.
