### ISSUE TITLE
Yocto recipe of your toolchain

### ISSUE THREAD

**Issue by finn-ball** [Xilinx/Vitis-AI#99]
So it seems pretty clear that your toolchain is built with Yocto. Is this recipe available somewhere to download?

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball,
I think you can find what you need in the following link.
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms/zcu102_dpu

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
Hope your issue has been solved. If not, find recipe in the following link. 
https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/2019.2/Xilinx_Official_Platforms/zcu102_dpu/petalinux
The "sdk.sh" is generated by the following command.
![image](https://user-images.githubusercontent.com/58016351/83111397-1bae5e80-a0f7-11ea-8655-01656e0c6330.png)

**Comment by finn-ball** [comment]
Thanks, this information is what I was looking for. Perhaps add a link to this in your README for other users?

**Comment by qianglin-xlnx** [comment]
What you said can be found in TRD section especially for the user who want to customize the sysroot. For most users, we provide an off-the-shelf cross-tool chain installation package that they don't have to regenerate themselves.

https://github.com/Xilinx/Vitis-AI/tree/master/DPU-TRD/prj/Vitis
![image](https://user-images.githubusercontent.com/58016351/83122053-ad24cd00-a105-11ea-95c0-d3a6879d4ab6.png)

**Comment by qianglin-xlnx** [comment]
Hi @finn-ball 
Since this issue has been resolved and I haven't received your feedback for a long time, I will close the issue.
