### ISSUE TITLE
DPU debug with VART

### ISSUE THREAD

**Issue by OxygenFunction** [Xilinx/Vitis-AI#991]
I have generated a quantized inference model and reference result. also DPU xmodel.
However, error was occurred when generating the DPU inference result,.
![1a649278674ae38e5063a55c3f3fa91](https://user-images.githubusercontent.com/59855741/186900648-f40d7017-6f28-46b2-9359-fd96d36b06ec.jpg)
I wonder what is this "Check failed. !the_factory_methods.empty()" mean.

**Comment by qianglin-xlnx** [comment]
Hi @OxygenFunction 
Which target board do you use?

**Comment by OxygenFunction** [comment]
> Hi @OxygenFunction Which target board do you use?

It would be DPUCZDX8G_ISA1_B4096 on zcu102

**Comment by qianglin-xlnx** [comment]
Hi @OxygenFunction 
For zcu102, please run the xdputil command on the board, not in the docker on the host.
